### ISSUE TITLE
Burial Mound & Fairy Pool Config or Removal Scheme

### ISSUE THREAD

**Issue by MokahTGS** [EpicSquid/Roots#1]
Now that this is being maintained again, can we get configs for the burial mounds and fairy pools so that you can either turn them off or somehow destroy them if you want to terraform an area that they are in.

Currently, even if you get rid of an entire mound or pool, the mobs still spawn, even if you light it up.  There doesn't seem to be anything you can do to change this in the current setup.

**Comment by EpicSquid** [comment]
I'll look into it, that sounds like a good change though

**Comment by MokahTGS** [comment]
Truth be told, I'd rather see an in-game way of removing them that has something to do with the mod.  Like a ritual, or spell that can be performed at the site.

**Comment by Mario90900** [comment]
I'm glad to see that this is under consideration, as I got a funny situation myself. I dug one up and filled it in, and while I expected it spawned mobs from being a structure, it keeps spawning them despite it being filled in with cobble and dirt. So now I have a free mob farm that just spits out the drops onto the forest floor.

**Comment by EpicSquid** [comment]
This is completely redone in Roots, going to close the issue
