### ISSUE TITLE
Living tool self-repair interferes with tool use.

### ISSUE THREAD

**Issue by Teibidh** [EpicSquid/Roots#103]
Mostly noticeable on the pick because one tends to use these on long runs at a time, but, when the tool is repairing itself it stops whatever left click action it's doing. I've seen this happen in combat with the sword but not often enough to care that much. With the pickaxe, though, when clearing out a room below ground, quite the annoyance.

Possible workarounds:
1) Only allow the tools to self-repair when they're not in hand. If you're not holding it, it can't be interrupted. You could, potentially, up the repair rate a bit if this option was chosen.

2) Reduce the frequency of repair and increase the repair amount.

3) I can't imagine this being easier to implement than the other two, but, not allowing a repair tick for a couple of seconds after the last time the tool is used. This wouldn't cause anyone to have to behave that much differently but you'd have to then know when the tool was last used which would (I imagine) suck. It would avoid the action interruption, though.

**Comment by duely** [comment]
^ This is one of my TODOs.

**Comment by duely** [comment]
Fixed in 2e6d7a8ee30 hopefully!
