### ISSUE TITLE
Cascading worldgen lag

### ISSUE THREAD

**Issue by heatseeker0** [EpicSquid/Roots#104]
Keep getting messages similar to this in my server logs:

> Roots 2 loaded a new chunk [-14, 23] in dimension 0 (overworld) while populating chunk [-13, 23], causing cascading worldgen lag.

Forge version: 1.12.2-14.23.5.2836
Roots 2 version: roots-2-0.104

**Comment by duely** [comment]
It simply means that a structure was generated too close to the edge of the chunk and it caused the chunk next to it to also be loaded. You can safely ignore it.

Additionally, Roots 2 is no longer supported.
