### ISSUE TITLE
[Roots 3] Component Pouch equipped as a bauble not being prioritized when using the 'open pouch' hotkey

### ISSUE THREAD

**Issue by Febilian** [EpicSquid/Roots#105]
Was curious about whether some variant of Soulbound would apply to the pouch, so I put it in an enchanting table with Quark Oddities' enchanting system enabled, scrolled through a few enchants before running out of exp and giving up, put it back in the baubles slot.

Checked the pouch later with a hotkey and everything that was in it is now gone.

I would guess this has something to do with the NBT data being changed by Quark(in regards to 'pending enchantments') and the storage somehow being messed up, but don't really know for sure.

**Comment by Febilian** [comment]
A follow-up: I took the pouch out of my bauble slot and opened it manually and the stuff is still in there just fine. But if I put it back on, and then open it with the assigned hotkey, it still appears completely empty.

**Comment by Febilian** [comment]
Okay, follow-up to the follow-up: I forgot I had a second pouch in my inventory because I was going to craft the bigger one soon to compare. The hotkey was opening that before the one in my baubles slot because it was in a top inventory slot.

Changing this issue to be "make the component pouch hotkey prioritize the one you're wearing as a bauble, if you are wearing it as a bauble."

**Comment by duely** [comment]
That does happen, yeah. The code primarily checks for the inventory first, but I can easily reverse that check. When I discussed it last with @EpicSquid the main idea was that it was only recommended to have one pouch. So... yeah.

**Comment by Febilian** [comment]
Yeah just a bit strange to me that something expressly equipped does not take priority when opening with a hotkey.

**Comment by duely** [comment]
Agreed, and the logic has been reversed to prioritize the Bauble pouch first if Baubles is installed.
