### ISSUE TITLE
[Roots 3] Patchouli guide should mention that Sylvan Armor passively uses herbs from your pouch while worn

### ISSUE THREAD

**Issue by Febilian** [EpicSquid/Roots#107]
This is more of a documentation enhancement suggestion; there is nothing in the entry for Sylvan Armor that suggests it will consume the herb you created it with, nor is there any indication of what each herb imbue even does.

This could easily discourage a new player from using the armor once they realize that it's draining their spellcasting resources for an unknown purpose at all times, especially given its low protection value and diamond-inclusive cost. Since the biggest draw to using this armor would probably be the unique effects(which the herbs being consumed would contribute to, I imagine), not giving even hints as per what they are makes it just not seem worth it.

**Comment by duely** [comment]
I think there's an intention of removing this mechanic. @EpicSquid ?

**Comment by Davoleo** [comment]
Yeah, the effect isn't finished yet, by now the only thing that the different imbuement recipes do is linking that specific item to the herb in NBT

**Comment by Davoleo** [comment]
this was fixed by nooby, i think

**Comment by duely** [comment]
Yep, they now provide a flat cost reduction to all herb usage.
