### ISSUE TITLE
Shift-clicking item from Component Pouch inventory to main inventory fails if all of the top slots in the main inventory are filled

### ISSUE THREAD

**Issue by Febilian** [EpicSquid/Roots#108]
Not sure how else to describe this - it just acts like your entire inventory is full even if it's just the top row of slots that are filled, and thus you cannot shift-click anything out of the pouch into your inventory at that point. I believe the upgraded pouch also exhibits this behavior.

**Comment by duely** [comment]
I believe this was resolved. Please comment if it wasn't.
