### ISSUE TITLE
[Roots 3] Suggestion: Put the "Spell Slot" messages on the hotbar toast instead of in chat

### ISSUE THREAD

**Issue by Febilian** [EpicSquid/Roots#109]
The reason being this:

https://i.imgur.com/vnssbKM.png

It just fills up the chat very quickly when cycling spells, so kind of off in multiplayer. The space where the bed-relevant messages in vanilla are displayed would probably work better for this, IMO.

**Comment by Davoleo** [comment]
oh lol, I've just realized there was an issue a linked issue to that TODO 
Anyways I fixed it in this commit: https://github.com/EpicSquid/Roots/commit/5b52b0d7b0969c5b474b2bc8def34ed582ab4559
