### ISSUE TITLE
[1.12.2 Roots 2] Tinkers Crafting Station pestle Dupe

### ISSUE THREAD

**Issue by Column01** [EpicSquid/Roots#11]
Hey Roots Developers, 
When using the pestle in the tinker's crafting station, it dupes the items in the bottom two rows of the table.I have attached a video to this post showing the process of duping the items, but I will also try to explain it.

If the items are placed in the top row of the table it works fine, but if you place any item in the rows below, they will get duped. I suspect this happens in other non-vanilla crafting tables, but I only tested with AE2 and was unable to re-produce this issue. I also know it is an issue with the roots mod since no other recipes have this flaw in the Tinker's Crafting Station. 
It should be noted that this was not reproducible in a single player world, and was noticed on a server running SpongeForge, and was not tested on a strictly forge server. In my opinion, this is not an issue with Sponge because this would happen to other recipes if it was. This is likely how the recipe handles the Pestle in the table once the craft is complete (I don't want to tell you how its broken because you are the developers and you know more than I do, but this is my first suspicion).
Thanks for your time, and please let me know if I can give you any more info to help you guys.
**~Colin**
[Video](https://www.dropbox.com/s/pfoxmlzrjeb3w2c/2019-01-06_20-20-46.mp4?dl=0)

**Mod Version:** 0.104
**Forge Version:** 2768

**Comment by EpicSquid** [comment]
This is an issue that will no longer be relevant in roots 3. Going to close it for now
