### ISSUE TITLE
[Roots 3] Client crash on attempting to use Patchouli structure preview

### ISSUE THREAD

**Issue by Febilian** [EpicSquid/Roots#117]
Not sure if this is a Patchouli issue or a Roots 3 issue or something else, to be honest.

https://gist.github.com/Febilian/c54077b029ea2b51eb5cbec744bdb2b3

I was trying to preview the structure for the 'Animal Harvest' ritual in-world.

**Comment by Davoleo** [comment]
Duplicate of #79

**Comment by Febilian** [comment]
Oops. I'll be more careful about that going forward, but I guess this at least a reminder it's still a thing?
