### ISSUE TITLE
Barrow spawners spawn hundreds of mobs and crash server if chunkloaded

### ISSUE THREAD

**Issue by JoshuaWalsh** [EpicSquid/Roots#119]
If a barrow spawner is present in a chunk that is kept loaded (via FTB Utilities or another chunkloading mod) then it will continuously spawn mobs that don't despawn unless a player is online. This eventually causes the server to experience severe lag, and if "max-tick-time" is configured then the server will eventually crash. The mobs persist even through a server reboot, so the problem can be tricky to fix. (Especially if you don't realise what's causing it!)

I initially encountered this issue [here](https://www.reddit.com/r/allthemods/comments/c42zw6/loaded_chunks_via_ftb_utilities_cause_hundreds_of/) and a commenter pointed out that this behaviour is caused by the Roots barrow spawners.

I think a simple fix would be to check if at least one player is in the dimension before spawning any mobs, as the mobs will despawn if no players are nearby as long as at least one player is within the dimension.

Or if you want to allow mob grinders to continue to work with chunkloaders, you could make it check how many mobs are nearby and only spawn more if it's under a reasonable amount.

**Comment by duely** [comment]
Hi there, if this is specifically referring to the entity that spawns mobs in Roots 2, then I'm afraid Roots 2 is no longer under development. The old barrow structure has been removed and been replaced with a standard mob spawner in the next version of Roots (Roots 3) + Mystical World -- which will hopefully be released soon.

**Comment by duely** [comment]
(Sorry if this wasn't the answer you were looking for!)

**Comment by JoshuaWalsh** [comment]
Dang, sorry to hear that. I can understand Roots 2 not being in active development anymore, but is there any chance this could be provided as a hotfix/patch version for it? Many modpacks still use Roots 2 and this affects server stability.
