### ISSUE TITLE
[Roots 3] Crash When Using Purify Ritual

### ISSUE THREAD

**Issue by TechnoMysterio** [EpicSquid/Roots#127]
Testing out the Pyre Rituals, managed to get a crash with the purify ritual.

To test, I inflicted a nearby pig with slowness and weakness upon myself with some splash potions. I started the ritual, and after a moment or two the game crashed. Crashlog:
https://pastebin.com/Z39nxWGn

**Comment by duely** [comment]
I just realised this is like, one of two rituals that I didn't test extensively before-hand. I'll look into ti -- thanks
