### ISSUE TITLE
Creating magmatic soil in flowing lava destroys the soil

### ISSUE THREAD

**Issue by duely** [EpicSquid/Roots#128]
Need to take what I learnt doing the mountaintear and apply it to the entity item.

**Comment by Davoleo** [comment]
:thonk:

**Comment by duely** [comment]
@Davoleo It's an easy fix -- sorta -- you have to create a new EntityItem class that is immune to fire damage, and then when an EntityItem spawns with that item, you destroy it and replace it with a new instance of your fire-immune entity item.

Example code: https://github.com/AranaiRa/ArcaneArchives/blob/master/src/main/java/com/aranaira/arcanearchives/entity/EntityItemMountaintear.java

Entity Joined World example code: https://github.com/AranaiRa/ArcaneArchives/blob/master/src/main/java/com/aranaira/arcanearchives/events/AAEventHandler.java#L297

**Comment by duely** [comment]
I'm gonna steal this off you @Davoleo  as I want to put it in the next release.
