### ISSUE TITLE
Grove Stone turns cropless farmland into grass.

### ISSUE THREAD

**Issue by AnotherVagabond** [EpicSquid/Roots#129]
I placed a Grove Stone over top of the water hole for my starter farm that was fully tilled, but only had a few slots with crops in them at that point. When I came back later, the stone had turned all of the farmland without crops into grass, and I've been told that that's not intended behavior, and to post an issue here.

**Comment by duely** [comment]
Fixed in dev, I just referenced the wrong bug ID in the commit message.
