### ISSUE TITLE
[Roots 3] Custom Pyre crafting recipe crashes

### ISSUE THREAD

**Issue by al132mc** [EpicSquid/Roots#130]
Hello, me again. I am trying to add a pyre crafting recipe (as seen in [this issue](https://github.com/EpicSquid/Roots/issues/121)). I have managed to add the recipe successfully and it shows up fine in the guidebook, but it crashes when I try to light the pyre.

```
mods.roots.Pyre.removeRecipe(<roots:stalicripe>*3);
mods.roots.Pyre.addRecipe("stalicripe",<roots:stalicripe>*2,
 [<minecraft:flint>,
  <contenttweaker:ice_crystal>,
  <roots:terra_moss>,
  <quark:root_dye>,
  <pyrotech:material:13>]);
```

[crash-2019-07-03_09.43.21-server.txt](https://github.com/EpicSquid/Roots/files/3355684/crash-2019-07-03_09.43.21-server.txt)

![2019-07-03_10 22 01](https://user-images.githubusercontent.com/39097092/60604738-d4e8a500-9d7d-11e9-9e99-4074b77755ce.png)

**Comment by duely** [comment]
That is not the bug I was expecting! Looking into it.
