### ISSUE TITLE
[Roots 3] [Suggestion] CraftTweaker support for existing pyre ritual recipes

### ISSUE THREAD

**Issue by al132mc** [EpicSquid/Roots#140]
It would be useful if there was CraftTweaker support for modifying the recipes for the existing pyre rituals.

My usecase: I would like to disable the vanilla furnace in my modpack, and i'd also like to be able to use the transmutation ritual, but it requires a vanilla furnace, so I have to either not disable the vanilla furnace or not use the transmutation ritual.

I'm assuming that I am unable to do this with the pyre crafting support, but maybe that's foolish of me.

![image](https://user-images.githubusercontent.com/39097092/60735476-19f50e80-9f19-11e9-9ed8-e008a2cabda1.png)

**Comment by duely** [comment]
I would actually classify this as a bug amongst the other missing CraftTweaker integrations.
