### ISSUE TITLE
[Suggestion] Combine Unending Bowl & Sure-footed stone

### ISSUE THREAD

**Issue by VallenFrostweaver** [EpicSquid/Roots#141]
This could make a new little bird bath or fountain that would be a perfect center piece in every garden. Upon combining them they could then hydrate /properly/ for a large radius or even a regular radius as well as prevent crop stamping.

**Comment by duely** [comment]
Ideally, the sure-footed stone should have nothing to do with hydration. The previous implementation did it "properly" but caused issues when placed next to water (as it was itself considered a water source). It's entirely possible that we can create something that resorts back to the previous mechanism and properly implements the relevant functions without causing a crash -- which is the reason why it got so dramatically & quickly changed.

**Comment by duely** [comment]
I've decided to undo my horribly hack-y fix and make it *work* in the same way it did previously without crashing, hopefully. I'm going to be adjusting the recipe to require an unending bowl as the thing that it works off.
