### ISSUE TITLE
Bug: with anyone 2 items making leather

### ISSUE THREAD

**Issue by Arctic90x** [EpicSquid/Roots#142]
I know it might be something on my end how I did tweak the configs, so I'm not 100% sure what happened, but I moved the ones tweaked configs then restarted Minecraft and the Bug was gone.

Here are my config files for everything
[Configs.zip](https://github.com/EpicSquid/Roots/files/3364206/Configs.zip)

**Comment by duely** [comment]
Just to clarify, did this actually make leather, or did it just show leather in the output which you were unable to pick up? 

The only situation I think that could be relevant would be the recipe to convert fox pelt into leather, but I'm not sure how that recipe could become corrupted as it's just a simple, standard Minecraft recipe.

**Comment by Arctic90x** [comment]
It was making full-on leather, any 2 items from in the crafting table

**Comment by Arctic90x** [comment]
I was even able to tale it

**Comment by duely** [comment]
All right, I'll look into it further!

**Comment by Arctic90x** [comment]
Here are some screenshots to show you what is going on just view them in order
[Screenshots.zip](https://github.com/EpicSquid/Roots/files/3364271/Screenshots.zip)
I mean everything was working fine until I played around in the config files

**Comment by duely** [comment]
I've yet to see this reproduced outside of this one report. If it happens again and you are able to provide more information (or it continues past restarting the client), then please open a new issue. Otherwise, I think this might just be a glitch with another mod or with Minecraft.
