### ISSUE TITLE
[Suggestion] Shatter spell has a consistent result

### ISSUE THREAD

**Issue by VallenFrostweaver** [EpicSquid/Roots#152]
Currently, the Shatter spell will randomly break generally 1-3 blocks but this can be very difficult to try to actually use practically as it keeps mining lower than I want in one use and higher for the next one. I would recommend that it simply mines the block it hits and one face directionally down from the face you aimed at.
Example: 
[c] is a block of cobble
[x] is blocks to be broken
[X] is block to be broken and aimed at

[c] [c] [c]
[c] [X] [c]
[c] [x] [c]

The above works horizontally as well as it would mine the center block and the one closest to the player effectively averaging the random block break to 2 and making a simple 2 block tall player path and also allowing a quick and easy stairway to be dug as well.

**Comment by duely** [comment]
Honestly, I'm for this.

**Comment by VallenFrostweaver** [comment]
If changes are made this is just a reminder that the text in the book would need to be updated as well as it talks about no pattern being discerned.

**Comment by Davoleo** [comment]
Do you mean like this?
![ezgif-2-428e9bfead79](https://user-images.githubusercontent.com/24458276/61581853-1d48e680-ab24-11e9-979d-12524ff4d112.gif)
or like this?
https://i.imgur.com/c5qoLcb.gif

**Comment by VallenFrostweaver** [comment]
I guess neither but I like both better than the existing. >.>
To use an existing mechanic for comparison:A Tinkers Construct hammer will mine a 3x3 area depending on the face at a 90° angle. I am talking about the same manner but a 1x2.

**Comment by duely** [comment]
So, if I understand properly:

- if your facing to the block is DOWN but your horizontal facing is NORTH, it would break the block and the one SOUTH of it
- if your facing to the block is NORTH (horizontal), it would break the block and the block DOWN from it?
- however if your facing to the block is DOWN but your horizontal facing is EAST, it would break the block and the one WEST of it?

**Comment by VallenFrostweaver** [comment]
I think that's right... I'm trying to get it from that. If I'm facing a standing wall and facing north (the side of a block) it would always break that block and the one below it.
If I'm facing a floor below me or ceiling above, you could have it go like this:
I'm facing north (and looking up or down) looking at the top or bottom of a block and it would always break it and the block south of it. If I'm facing east, it breaks it and west of it.

**Comment by Davoleo** [comment]
here's a demo of the reworked effect https://streamable.com/r9xeq this issue will be closed once I push the commit, although feel free to give me feedback and/or critiques about it

**Comment by VallenFrostweaver** [comment]
Perfection!
