### ISSUE TITLE
Sanctuary repells all things

### ISSUE THREAD

**Issue by VallenFrostweaver** [EpicSquid/Roots#153]
Minecraft 1.12.2
Forge: 14.23.5.2836
Roots: 3.0.0 (3.0.2)
This may be as intended but the description in the book reads "creatures" and "projectiles that attempt to hit the caster." I prefer that it repels all things but this might not be intended behavior.
Example image shows xp orbs being repelled. Works on dropped items and armor stands too.
![xp](https://user-images.githubusercontent.com/13642054/61369960-3b46ea80-a889-11e9-9171-679c0e15b3e5.png)
![armor stand](https://user-images.githubusercontent.com/13642054/61369966-3e41db00-a889-11e9-8bdc-6d7e764f8488.png)

**Comment by duely** [comment]
re: 5e688ba

a) It should be checking EntityLivingBase
b) We need to stick with Entity and skip anything that isn't EntityLivingBase, and then have a configuration option that allows the specification of classes which should specifically be included/excluded and consult that
b) In addition, this current change will let arrows pass through (as well as any other type of projectile), so we should definitely be special-casing to make sure projectiles aren't allowed in

**Comment by duely** [comment]
Further, it looks like anything that implements IProjectile should be rejected.

**Comment by Davoleo** [comment]
oof, big fail
