### ISSUE TITLE
[Roots 3] Method of obtaining different soils unclear in guide book

### ISSUE THREAD

**Issue by duely** [EpicSquid/Roots#22]
It's really unclear exactly what you need to do. I get the impression now that you hold the bulb in your off-hand and then use the knife on the soil, but I'm not 100% certain.

![](https://i.imgur.com/NpAFeU3.png)

**Comment by Martacus** [comment]
Yes, that's how it works. Let's make that more clear in the book.

**Comment by EpicSquid** [comment]
Fixed, now explains how to get them on each page, and runic carving uses the herb directly rather than with a pouch
