### ISSUE TITLE
[Roots 3] Lit pyre does not melt snow blocks

### ISSUE THREAD

**Issue by duely** [EpicSquid/Roots#26]
I'd recommend stealing something from the torch implementation that melts layers of snow while the pyre is active -- but certainly at an accelerated rate.

**Comment by EpicSquid** [comment]
Fixed by melting snow

**Comment by duely** [comment]
!()[https://thumbs.gfycat.com/ImmediateHelpfulAmericanpainthorse-size_restricted.gif]

Nope

**Comment by tyler489** [comment]
Hmm this could possibly be fixed with the request from #78

**Comment by Davoleo** [comment]
umh, I think they're two different things, since the other one would be fixed by setting the player on fire that doesn't involve snow melting

**Comment by tyler489** [comment]
Making it fire would probably mean making it emit light which would melt snow.. right?

**Comment by Martacus** [comment]
Making it fire is impossible without it looking like this. So that's not happening. Snow is being melted now so this issue can be closed.
