### ISSUE TITLE
[Roots 3/Mystical Worlds] Mod ID unclear

### ISSUE THREAD

**Issue by duely** [EpicSquid/Roots#27]
It's really unclear in some cases what belongs to roots and what's in Mystical Worlds. I honestly don't understand why Mystical Worlds exists, but when I go looking for "@roots" in JEI I get hardly anything at all, but when I loot terra moss spores... it says it's from "Mystical Worlds". The confusion way not be as bad for sane people unlike me.

**Comment by EpicSquid** [comment]
Fixed by just refactoring everything
