### ISSUE TITLE
Terran Soil BUG

### ISSUE THREAD

**Issue by RainEffect** [EpicSquid/Roots#362]
### General Information

**Describe the bug:**
Terran Soil will yield much more for the crop, but digging just after the crop is planted is also possible too.

**To Reproduce:**
1. Place a Terran Soil;
2. Plant any crop;
3. Dig it
4. Repeat 2-3

**Expected behavior:**
Normal drop crop when it wasn't mature.

***

### Environment Versions
- Roots: 3.0.13

**Mystic Mods Versions**
- MysticalLib: 1.1.1

**Other Versions:**
- MineCraft: 1.12.2
- Forge: 14.23.5.2847
- Modpack (if available): [EnigTech2](https://github.com/ET-Team/EnigTech2)

**Comment by noobanidus** [comment]
Hm, that's unexpected. Thanks! I'll have a look into it.

**Comment by RainEffect** [comment]
Hope it will fix at next version soon, because that is more users was using this bug now.

**Comment by RainEffect** [comment]
I make a GIF image to show this bug.
![Terran Soil Bug Gif](https://user-images.githubusercontent.com/14258727/70990807-408eb680-2101-11ea-8460-f73e673726a8.gif)

**Comment by noobanidus** [comment]
This will be fixed in 3.0.22.
