### ISSUE TITLE
Adding Animania Entities to Runic Shears does not seem to work

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#363]
### General Information

**Describe the bug:**
Using CraftTweaker, I added all flavors of Animania Cow and Bull to the fey leather list.  The script in question can be found here: https://pastebin.com/biiwwbWT
However, right-clicking with Runic Shears doesn't do anything. To confirm they are not blocking any and all right click behaviors, I tested by holding an ender pearl and a bow in my hand and trying to use them on the cows and bulls, which does work. (Draft Horses are another matter entirely)
Adding a Better Animals Plus Badger to the list of Fey Leather entites does result in the Badger dropping Ley Leather.

### Environment Versions
Roots 3.0.21

**Mystic Mods Versions**

- MysticalLib: 1.4.0 (reports as 1.1.1 to MultiMC for some reason)
- Mystical World 1.6.1

**Other Versions:**
- Conflicting mod: Animania 1.7.3
- Forge: 14.23.5.2838
- Minecraft: 1.12.2

***
### Additional Information
**Additional context (optional):**
The issue was reported to Animania and a developer closed the issue, stating that it was not on their end.  However, I remain doubtful. https://github.com/capnkirok/animaniamod/issues/385

**Comment by noobanidus** [comment]
Have you tested this in an environment with just Roots & Animania? I know there are a few mods that are actually preventing the Runic Shears from functioning properly due to right-click handlers. 

Also, looking at your script, I'm pretty sure that keys should be unique; I'd suggest checking an Animania mooshroom to see if it functions with that, as it's possible that everything is overriding every other thing. If that is the case, you'll need to number them *and* I'll need to print out an error when something is overwritten.

**Comment by DoomRater** [comment]
Sounds like a testing plan. I will give each of these ideas a shot and let you know what happens.

When I tested badgers, it was added to the end of the script- if I add it to the beginning to the script, and I can't shear them, I'll make sure to report back. If I can shear the badgers despite adding them to the beginning, I'll re-test with just Animania and Roots.

**Comment by noobanidus** [comment]
Awesome! It'll be good to find out. I might need to re-code runic shears to catch cancelled events or some such... the current system for handling right-click interacts is unfortunately problematic, and I still haven't managed to derive a complete list of mods that seem to cancel it willy-nilly.

**Comment by DoomRater** [comment]
When I tested putting badgers at the beginning, they indeed stopped being able to be sheared.  So now I know the names do collide.
So I isolated the two mods (and dependencies), and re-wrote the fey leather Craft...Tweaker.... wait. I forgot to make sure CraftTweaker was running.  One moment. Running CraftTweaker with the two mods does in fact cause fey leather to drop from horses and cows.

My configs were simply set up incorrectly, then.
Edit: Here's a config that works: https://pastebin.com/dCG2GCU3

**Comment by noobanidus** [comment]
Awesome, I'm glad it was that simple. I'll still add something to note "overrode recipe blah blah" in the errors so it's at least less obtuse/obfuscated what the issue might be for others.

**Comment by noobanidus** [comment]
I've added a CraftTweaker error (which should show up on screen when you launch/execute the script) that will hopefully make this less of an obfuscated issue in the future. This should be in 3.0.22, which I aim to have out this weekend.
