### ISSUE TITLE
Crashing on starting the Ritual of Spreading Forest

### ISSUE THREAD

**Issue by Timeslice42** [EpicSquid/Roots#364]
### General Information

**Describe the bug:**
Starting the ritual of The Spreading Forest causes a crash. https://paste.dimdev.org/xufefocehi.mccrash

**To Reproduce:**
Dynamic Trees and Bewitchment are both installed. Both vanilla and DT birch trees were near the pyre when the ritual started.

**Expected behavior:**
The ritual should at least work on vanilla trees, if not both vanilla *and* Dynamic trees.

***

### Environment Versions

(All mod versions are listed in the crash log.)

**Mod Versions**
- MysticalLib: 1.4.0
- Mystical World: 1.6.1
- Roots: 3.0.21
- Dynamic Trees: 0.9.6
- Bewitchment: 0.0.21.3
- Forge: 2847
- Minecraft: 1.12.2
- Modpack: (Custom)

***

### Logging Information
Crash Report:
https://paste.dimdev.org/xufefocehi.mccrash

***

**Comment by noobanidus** [comment]
Something (presumably Dynamic Trees) is either preventing vanilla trees from dropping their normal saplings, or there's a growable item block nearby that is dropping air; this is mostly an oversight on my place in that I'm not checking the stack before checking the ore dictionary...

**Comment by Timeslice42** [comment]
I would guess it's because the DT trees are technically a multiblock structure that uses fancy block states, which then drops the appropriate leaves when sheared, or pretends to break the corresponding leaves when broken or chopped down. You may need to talk to @SkyHawkB to find out how to query the trees correctly.

**Comment by noobanidus** [comment]
I think what's more likely is that there's an IGrowable nearby that doesn't drop itself for whatever reason.

EDIT: It should be fixed in 3.0.22 which I'll try to release this weekend.

**Comment by Timeslice42** [comment]
I'm pretty sure DT trees are IGrowable, as I can use various mod fertilizers and spells to grow them from the first stage to the second stage. But it's possible. I can't tell for sure since the log doesn't say which block it was trying to access, unless it's in ``debug.log``?

**Comment by noobanidus** [comment]
It's not particularly an issue either way, as it never gets reported it just makes the assumption that the block will never return `Items.AIR` or `ItemStack.EMPTY`, both of which are perfectly valid results for the `getDrops` function. It's my fault for failing to check the validity before consulting the OreDictionary.

**Comment by Timeslice42** [comment]
Either way, thanks for the fast turn-around.

**Comment by noobanidus** [comment]
This will be resolved when I release 3.0.22 (hopefully soon).

**Comment by kierajreed** [comment]
Awesome! Thank you for being a wonderful Bug Detective! :)
