### ISSUE TITLE
[Request] Add config to disable all soil particles

### ISSUE THREAD

**Issue by ErnestoPeroPezzi** [EpicSquid/Roots#366]
**Describe your suggestion:**

As the title says, add a config option to disable all soil particles

**Additional context:**
Using them for big farms amounts to huge amounts of particles, slowing down older machines

**Comment by noobanidus** [comment]
I'll have to triple check to see if this is done client-side or not. I believe it is, in which case it should be possible to make it a configurable value.

**Comment by Davoleo** [comment]
otherwise we could also make it work together with vanilla particles setting (just putting this down as an alternative idea)

**Comment by noobanidus** [comment]
This now exists with within the General subheading under Disable Particles.
