### ISSUE TITLE
Imbuer causes server to crash

### ISSUE THREAD

**Issue by CammiePone** [EpicSquid/Roots#369]
### General Information

**Describe the bug:**
It's causing our server to crash whenever someone loads the chunk it's in.

**To Reproduce:**

1. Start up a dedicated server
2. Imbue iron boots with iced touch
3. Crash

**Expected behavior:**
We expected it to imbue the boots.

***

### Environment Versions
3.0.21

**Mystic Mods Versions**

- MysticalLib: 1.4.0
- Mystical World: 1.6.1

**Other Versions:**
- Conflicting mod (if regarding mod integration): none
- Other mods you think could cause issues: none
- Forge: 14.23.5.2847
- Minecraft: 1.12.2
- Modpack (if available): The Pack Pack created by Camellias_

***

### Logging Information

**Crash Report (if available):**
https://pastebin.com/s1GG9V68

**Latest Log (if necessary):**
https://pastebin.com/UD0iciZb

***

### Additional Information
**Screenshots (if available):**
none

**Additional context (optional):**
none

**Comment by noobanidus** [comment]
This is rather odd. Just to clarify, did you put the iron boots in first, or did you put the spell powder in first?

Before doing so, is there any chance you can upload the 0.0 region file somewhere? This appears to contain the affected chunk and I'd be interested in examining the NBT to see what's actually going wrong here.

After that point, you will need to go into the Forge/FML config file and enable "remove erroring tile entities", launch the server, then shutdown and disable that option, and launch again. I don't see any other way of preventing your server from crashing apart from doing that.

**Comment by CammiePone** [comment]
> 
> 
> This is rather odd. Just to clarify, did you put the iron boots in first, or did you put the spell powder in first?
> 
> Before doing so, is there any chance you can upload the 0.0 region file somewhere? This appears to contain the affected chunk and I'd be interested in examining the NBT to see what's actually going wrong here.
> 
> After that point, you will need to go into the Forge/FML config file and enable "remove erroring tile entities", launch the server, then shutdown and disable that option, and launch again. I don't see any other way of preventing your server from crashing apart from doing that.

They did the spell first, boots second.

As for the proposed fix, we've already done the config change for Forge, as we've dealt with erroring tile entities in the past. We've confirmed it's only with that one spell, and not with any others.

**Comment by noobanidus** [comment]
Thanks for the update! I'll definitely have to look into it. Currently I'm planning on an overhaul of the modifier system, but at the very least I can put some safety checks in.

**Comment by noobanidus** [comment]
So, I'm unable to actually replicate this in single player... I'll add a work-around so it just rejects the item instead of crashing.
