### ISSUE TITLE
CraftTweaker complains about null file running script

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#371]
### General Information
This CraftTweaker file seems to work fine, but I still receive a null error on line 0 upon loading my world. Pastebin: https://pastebin.com/ZUzu26Jp
**Describe the issue:**
[20:27:11] [Client thread/INFO] [minecraft/GuiNewChat]: [CHAT] ERROR: [crafttweaker]: Error executing {[0:crafttweaker]: RootsAnimalHarvest.zs}: null

Have I simply done something incorrectly? I have a similar script for Untrue Pacifist entries which also yields the same result, regardless of whether I use an include method or prefix every command.

**Comment by noobanidus** [comment]
One of your entity names is incorrect then and is resulting in a null value being passed i n.

**Comment by DoomRater** [comment]
I'll scan through and try to find what is causing it, since I don't get a line number.  My only clue is that one of the entities is in both files. Thanks for the help!

Edit: I don't know how to spell pheasant.
