### ISSUE TITLE
Some way to generate or regenerate ores?

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#373]
**Describe your suggestion:**
TekTopia has a Druid villager that performs, among other things, an earth rejuvenation spell that actually generates ores in mineshafts once more.  It'd be neat if there was some way to accomplish the same thing in Roots.

**Additional context:**
Look at these absolute champions of protecting mother earth:
[link removed as it doesn't work]

**Comment by noobanidus** [comment]
From the look of it, this is specifically an interaction between a TekTopia entity/villager and a TekTopia structure, which already has the capacity programmed in for it. I think there could definitely be interesting applications for a similar concept, ritual or spell (perhaps an "earth magnet" spell that pulls ore from the ground, similar to how the mining tree works in Twilight Forest might work).

Unfortunately, this most likely will not happen in 1.12, as I'm past the point of major new features/spells/etc.

I'd keep open as a future suggestion, but I'm trying to cut down on what's on the tracker.
