### ISSUE TITLE
Wildwood Leaves don't set Decayable=false on placement by players.

### ISSUE THREAD

**Issue by SiliconEnt** [EpicSquid/Roots#375]
### General Information

**Describe the bug:**
When most leaves (Vanilla and from mods) are placed in the world by a player, both the "check_decay" and "decayable" blockstates are set to false.
When Wildwood Leaves are placed in the world, "check_decay" is set to false, but "decayable" is set to true. As a consequence, any structure (e.g. hedges) made of wildwood leaves is destroyed by breaking a single block and letting leaf decay take over.

**To Reproduce:**
1. Obtain Wildwood Leaves. The consequences are the same whether they are acquired with shears or from the creative menu.
2. Place one in the world.
3. Open the F3 Debug overlay. The overlay will show "decayable: true".
4. Place more wildwood leaves to create a continuous mass. (Out of range of any logs)
5. Break one block in the continuous mass of wildwood leaves, in Survivial Mode. Any wildwood leaves adjacent to the broken block will have a chance for "check_decay" to be set to true. When this leaf decays, it sets off a chain reaction. Other leaves in the mass will not have "check_decay" set to true, so far as I can tell, but they will decay anyway.

**Expected behavior:**
Wildwood Leaves should have both "check_decay" and "decayable" set to false when placed by means other than sapling growth. They should match the decay behavior of Vanilla and other Modded leaves, unless there is a lore-based reason for them to behave differently.

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 1.1.1
- MysticalWorld: 1.12.2-1.7.0
- Roots: 1.12.2-3.0.23

**Other Versions:**
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Baubles: 1.12-1.5.2
- While the issue was discovered in a modpack with fast leaf decay, testing was conducted in a purpose-built instance. No other mods were present and no changes were made to config.

***

### Logging Information

**Latest Log (if necessary):**
- Latest.log: https://gist.github.com/SiliconEnt/c0235bc90b415ff652aef2db855c5207
- Debug.log: https://gist.github.com/SiliconEnt/9128e740d126c3d281d483dfdfe26514

***

### Additional Information
**Screenshots (if available):**
![01_single_block](https://user-images.githubusercontent.com/46073934/72837141-73fdbd00-3c3a-11ea-8638-0a9b0939c401.png)
Single block – decayable: true
***

![02_hedge](https://user-images.githubusercontent.com/46073934/72837252-a8717900-3c3a-11ea-8f35-1a9ae091f43a.png)
Continuous mass of blocks – decayable: true
***

![03_check_decay_true](https://user-images.githubusercontent.com/46073934/72837315-c939ce80-3c3a-11ea-85aa-0c28a6ba84a9.png)
Block next to broken block – check_decay: true
***

![04_check_decay_false](https://user-images.githubusercontent.com/46073934/72837394-e1115280-3c3a-11ea-9feb-6b1d239823b7.png)
Block next to broken block – check_decay: false. Not all blocks adjacent to the broken block have check_decay set.
***

![05_decaying_leaves](https://user-images.githubusercontent.com/46073934/72837507-10c05a80-3c3b-11ea-9f99-c8220b1e2e6b.png)
Leaves decaying.
***

![06_leaves_gone](https://user-images.githubusercontent.com/46073934/72837558-1fa70d00-3c3b-11ea-8609-b53ae4fed6b3.png)
Leaves are gone.

**Comment by noobanidus** [comment]
Oh wow! Thank you for the extensively detailed write-up, I had no idea this was actually a feature for Vanilla leaves that needed to be manually implemented. I'll look into it.

**Comment by noobanidus** [comment]
What's interesting is that I can't actually find an instance where this actually happens in Vanilla -- the place where I expected it to happen would be getStateForPlacement, but there doesn't actually appear to be an implementation of that for BlockLeaves, which is the default; the old/new leaves also don't seem to have anything. 

I'll dig further.

EDIT: HAH! It's hiding in the itemblock. Okay, I think I can fix this with a simple update to MysticalLib.

**Comment by SiliconEnt** [comment]
I think this can be closed. The most recent released updates to MysticalLib, MysticalWorld, and Roots appear to have fixed the issue; decay behavior is now identical to Vanilla leaves.

**Comment by noobanidus** [comment]
Ty, forgot to close it.
