### ISSUE TITLE
[Informational] Ritual of the Spreading Forest not working with Dynamic Trees

### ISSUE THREAD

**Issue by Timeslice42** [EpicSquid/Roots#376]
https://github.com/ferreusveritas/DynamicTrees/issues/394

In case you need to ask for more specific information.

**Comment by noobanidus** [comment]
Someone would specifically need to code in Dynamic Trees support, perhaps with an addon. At this time, I'd recommend just disabling the ritual as it doesn't function properly, and I have too much on my plate to do it now.

**Comment by Timeslice42** [comment]
This is not specifically a task for you. This is to let you know that DT is going to add the appropriate sapling drops to the leaves on the trees. I'm just linking you the issue in case you need to ask for more specific information to be returned.

~~Ideally you'd tell them which method you're calling on their leaves that isn't returning what the ritual is expecting.~~

**Comment by noobanidus** [comment]
I understand now, but I really don't need to ask them for more specific information to be returned. Dynamic Trees is a significant overhaul of a vanilla system and, without Dynamic Trees, Roots seems to function without issue; that means that it's really upon Dynamic Trees to ask for more information, or even just read through the source code.

I can understand you wanting compatibility and I applaud that, but unless you're actually helming some form of compatibility yourself (as someone else did with the Wildwood trees/Wildroot Growth ritual), I again don't have time to ask them for more specific information to be returned/tell them what they can easily glean just by reading the source code (which is freely available).

**Comment by Timeslice42** [comment]
Yeah, I went ahead and already did that. BlockLeaves.getDrops() should return an instance of BlockSapling OR a block in the oredict as a sapling, instead of the "Air" or null that they're currently returning.

I just wanted to verify that I wasn't telling them lies, or giving incomplete information. This isn't really an issue for a third party compatibility mod, as their leaves *should* be returning the correct information.

**Comment by noobanidus** [comment]
That's fine, good on you for being conscientious about it! 

I think I may have been channeling all the frustrations I've felt when asked to add compatibility with other mods and found it difficult to explain to people that it's not something *I* can necessarily do (or *just* do), but that it's a complex process and *generally* requires the other mod to do most of the work.

Sorry for sounding like a bitch!

**Comment by Timeslice42** [comment]
No worries, and thanks for the explanation. :) Mod interactions are frustrating for everyone involved. Thanks for the quick responses.

I was prepared anyways for you to initially dismiss this out of hand since the issue is specifically in your "Known Issues" list as something you can't fix.

**Comment by Timeslice42** [comment]
Can you explain this bit?
`private static int SAPLING_OREDICT = -1;`
...
https://github.com/MysticMods/Roots/blob/3e1a6bdac7747bcdaa63228146497b9b0ef6ffd5/src/main/java/epicsquid/roots/entity/ritual/EntityRitualSpreadingForest.java#L111-L116

**Comment by Timeslice42** [comment]
Okay, so here's the problem: DT trees spread via seeds, not saplings, so even if they return those seeds in the drops list, your ritual isn't going to plant them correctly, right?

To a player (and most planter machines) there's no difference between planting a seed and planting a sapling, but it looks like your ritual is explicitly looking to place stage 1 sapling blocks.

**Comment by noobanidus** [comment]
That could indeed be a problem. I could potentially outsource to a registry where add-on mods could register a function to determine placement types... but yes, I'm specifically looking for saplings.

**Comment by Timeslice42** [comment]
The seeds are in the oredict as "treeSapling". They aren't showing up in your ritual list though because they aren't blocks, right? In theory, if they do get returned in the BlockLeaves.getDrops() list then your ritual could do special handling for "saplings" that aren't blocks, right? I _might_ be able to do a PR for that.

**Comment by noobanidus** [comment]
I don't honestly know how the seeds work. It's probably because they don't extend the BlockSapling block and aren't a blockitem instance of that...
