### ISSUE TITLE
Wierd Graphical Glitch

### ISSUE THREAD

**Issue by FoxHound-s** [EpicSquid/Roots#377]
### General Information

**Describe the bug:**
Every time i open the druic arts book the graphics start to look wierd like when mipmaps its on 0 and the lighting start to flicker 
**To Reproduce:**
Open the druic arts book and check on any ritual ,close the book and the graphics start to look funny 

I start notice that at random that start to happen restarting the game fixit ,Dunno if its this mod but so far its the only way i find to reproduce the glitch . Iits driving me crazy

**Comment by noobanidus** [comment]
a) Can you reproduce this with any other Patchouli book, especially the one from Mystical World?
b) Can you provide screenshots of what's going on? I recommend ShareX if you don't have a program already installed that can upload screenshots for you automatically.
c) What other mods are you running in combination with Roots, besides Mystical World and Mystical Lib?
d) What version of Roots? (you can get these from the mods directory from the filename)
e) What version of Mystical World?
f) What version of MysticalLib? 
g) What version of Forge are you running?

**Comment by FoxHound-s** [comment]
a) It didnt happen with the MW Patchouli book
b) Before i open the book https://i.imgur.com/x60EuSQ.jpg
     after   https://i.imgur.com/MC0m0Nn.jpg   
      Its not very noticeable  in the screens ,especialy the flickering lights 
c) Have alot but i test with just roots   MW  ML AND Patchouli and stil happens
e) mysticalworld-1.12.2-1.7.1
f)mysticallib-1.12.2-1.6.0
g) forge1.12.2 - 14.23.5.2847

**Comment by noobanidus** [comment]
Does it happen when you open to a specific entry or do a specific thing, like view a multiblock structure, or does it happen when you open the index page?

I really don't know what Roots could possibly be doing (actually, there isn't anything) that's different compared with other mods outside of the background that's being rendered -- and even that is being specifically handled by Patchouli.

Is it possible that the issue is specific to your set-up, that you have graphics card issues or some of your settings are misconfigured?

**Comment by FoxHound-s** [comment]
Sorry for the late response, didn't have time to play yesterday, i did more testing today and its patchouli ,theres nothing wrong with roots , i tested with only patchouli and natures aura (another mod that use patchouli book) and the same thing happen it happen only when i open the book in some multiblock structure like a ritual where u can see the structure spining , i tested with other mod books like IG , thaumcraft and astral and didnt hapen it just patchouli .sorry for open this here when its not a roots issue

**Comment by noobanidus** [comment]
Okay, good to know. I'd recommend asking about this on the Patchouli issue tracker.
