### ISSUE TITLE
Pyre Crash

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#378]
### General Information

**Describe the bug:**
A pyre grabbed 4 items to cook out of the container and then... threw this wibbly.  This was on a multiplayer server.

**To Reproduce:**
1. place 9 pereskia bulbs in a chest under a pyre
2. start ritual
3. wait for it to finish cooking

**Expected behavior:**
I'm not sure what should happen here... just pull up the goods?  Fail to pull any goods?

***

### Environment Versions
Roots: 3.0.21
Mystical Lib: 1.4.0 (reports internally as 1.1.1 for some reason)
Mystical World: 1.6.1

**Other Versions:**
- Forge: 14.23.5.2838
- Minecraft: 1.12.2

**Crash Report:**
https://pastebin.com/QewiMeur

**Comment by noobanidus** [comment]
I believe this was fixed in .22, .23 or .24

**Comment by DoomRater** [comment]
Yikes, I need to pay more attention when updates come out.  Will update shortly to confirm whether it's fixed!

**Comment by noobanidus** [comment]
That's fine! I just specifically remember rewriting a bunch of code to ensure that this wouldn't happen any more, so I'm really hopeful that it's resolved your issue as well.
