### ISSUE TITLE
Issues with Safe-Footed Stone

### ISSUE THREAD

**Issue by Ainobara** [EpicSquid/Roots#379]
### **General Information**

**Describe the bug:**
The ''Sure-Footed Stone'' doesn't apply water on farmland in equal direction. 4 blocks for two directions and 3 blocks for the other two directions.
[Picture](https://drive.google.com/file/d/1_9nV2xdD2DVD964M-eDA5izFbTsn5kmh/view?usp=sharing)

### **Environment Versions**
Roots: 3.0.24
Mystical Lib: 1.6.0
Mystical World: 1.7.1

**Other Versions:**

- Forge: 14.23.5.2847
- Minecraft: 1.12.2

**Comment by DoomRater** [comment]
Which way is it biased towards in cardinal directions?  For those of us who want to be aware of the issue while it's being fixed.

**Comment by Ainobara** [comment]
After 2 test on 2 differents maps with and without other mod, it's seem to be 4 blocks facing West and North and 3 blocks facing East and South. (sorry for my bad english)
