### ISSUE TITLE
Light Drifter return order

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#380]
### General Information

**Describe the bug:**
Light Drifter changes game mode back to survival before player's world position has been reset.  If a player is in solid rock, or (more dangerously) near an Ice and Fire Dragon, bad things happen to the player.

**To Reproduce:**
1. Cast Light Drifter in survival
2. stop within solid rock
3. wait for end of spell duration

**Expected behavior:**
Return back to previous position unharmed

**What Actually happened:**
Player takes a hit of suffocation damage while returning to previous position
***

**Mystic Mods Versions**
Roots: 1.12.2-3.0.24

**Other Versions:**
- Other mods you think could cause issues: Ice and Fire Dragons can grab you during this vulnerable state, meaning you do NOT get teleported back to where you were!

**Comment by noobanidus** [comment]
That is ... odd. I'll definitely have to take a look into it, as unfortunately the code is quite old and I don't fully understand its intricacies. I'll definitely try to improve it though, and this would explain why some people were managing to catch fire.

**Comment by Bluberry-Kat** [comment]
the response here makes me believe you didn't mean to close this.

**Comment by noobanidus** [comment]
Oops! Thank you. I want to say my finger slipped 'cos of tremor but it's entirely possible I just brainlessly clicked close and comment.

**Comment by DoomRater** [comment]
My own pouring over the code leads me only to here:
https://github.com/MysticMods/Roots/blob/3e1a6bdac7747bcdaa63228146497b9b0ef6ffd5/src/main/java/epicsquid/roots/network/fx/MessageLightDrifterSync.java#L73
Swapping with line 74 might fix it?  It's the only place I can see where position and game mode are updated in reverse order.

**Comment by noobanidus** [comment]
Yes, I think that would about do it. I'll see if there's any other small issues that can be fixed and release 3.0.25.

**Comment by DoomRater** [comment]
I got to testing it and while I still take suffocation damage if I'm flying fast enough or far enough, I no longer take damage if I'm stationary.  Haven't been set on fire yet though!

**Comment by noobanidus** [comment]
Just of note, this is only fixed in the 3.1.0 branch, not the most recent release. I'm not sure if you meant that you had compiled 3.1.0 locally and were testing that -- if you have, I greatly appreciate it! I may need to remove the player's velocity as well.

**Comment by DoomRater** [comment]
Oh my bad- no I have not compiled 3.1.0 myself to test, so that was done on .25.

**Comment by noobanidus** [comment]
Yeah, apologies, I should've made that clearer. 3.0.25 is going to be the last release for 3.0, and I'm going to be trying to release a beta at the very least (or an alpha on Discord at the worst) for 3.1 this week.
