### ISSUE TITLE
Ritual icons become black when looking it at a certain position

### ISSUE THREAD

**Issue by RisingInIris2017** [EpicSquid/Roots#381]
### General Information

**Describe the bug:**
Walk round the Pyre with a ritual icon, and see that icon becomes a black square.

**To Reproduce:**

1. Place some materials on a Pyre, making a Ritual icon displayed above it.
2. Walk round the Pyre, and see the icon becomes a black square, and then recovers.

**Expected behavior:**

Ritual icon should be displayed when player is at any position.

### Environment Versions

OS: Windows 10 Home, 
Java: JRE 1.8.0.231
**Mystic Mods Versions**

- MysticalLib: mysticallib-1.12.2-1.6.0
- MysticalWorld: mysticalworld-1.12.2-1.7.1
- Roots: Roots-1.12.2-3.0.24

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 14.23.5.2847   
- Minecraft: 1.12.2

***
### Additional Information
**Screenshots (if available):**

I have a screen record for my issue post.
https://imgur.com/gallery/36yWzN4

**Comment by noobanidus** [comment]
Are you using Optifine or any other form of mod that modifies graphics? Shaders, FoamFix, Vanilla Fix, etc?

**Comment by RisingInIris2017** [comment]
Oh, I forgot to bring a mod list for you.
https://paste.ubuntu.com/p/TRZDWRjXNp/
OptiFine Version: 1.12.2_HD_U_F5
 OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 441.87, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz

**Comment by noobanidus** [comment]
Can you verify if this occurs without Optifine being installed?

**Comment by RisingInIris2017** [comment]
Sorry for bothering you! 
> Can you verify if this occurs without Optifine being installed?

Yes.
All of mods installed are listed in this picture, those mods which may modify game rendering are renamed into .dis files. I believe by doing this, those files will not be recognized as mods by Forge.
![modlist](https://user-images.githubusercontent.com/28519848/74580866-5f1b0c00-4fe3-11ea-8972-58184b691501.png)

**Comment by noobanidus** [comment]
Okay, thanks! I just wanted clarification for that, I'll start digging into it further now and see if I can reproduce it without any other mods installed.

**Comment by noobanidus** [comment]
Unfortunately, I'm not able to replicate this in my dev environment.

This means that, most likely, another mod is responsible for this. Perhaps there is a tile entity renderer in view or an entity renderer in view that is corrupting the OpenGL state, hence why it only happens some of the time.

Example: 

![](https://thumbs.gfycat.com/BlankTenderBlacklab-size_restricted.gif)

**Comment by RisingInIris2017** [comment]
> Unfortunately, I'm not able to replicate this in my dev environment.

Have you ever tried to look at the icon from the other side?
This issue exactly is: the icon will be shown normally from one side, but turn into a black square when being looked at from another side.
If you did have tried to look at the icon from both sides and found nothing, *just ignore this comment*.

**Comment by noobanidus** [comment]
I was actually finally able to replicate this: it has something to do with the method of selecting the baked model and it being in close proximity to BlockPos.ORIGIN (i.e., 0, 0, 0). I've changed the render system to automatically pick the baked model and this works.

Just need to tweak the alpha.
