### ISSUE TITLE
pyre cooking consumes all inputs, only finishes crafting the last set

### ISSUE THREAD

**Issue by majijn** [EpicSquid/Roots#382]
this can be reproduced by hand or via storage below the pyre

have a pyre with a fire that is always on.
input five items that can be cooked, like squid, then while its cooking place another 5 , can be the same or a different type of food.  if you stop adding food to the pyre it will successfully craft the last set of items only

if you keep adding food it will stop processing the previous set, voiding the items, and start the new set of items.

forge 14.23.5.2847
roots 1.12.2-3.0.24

**Comment by noobanidus** [comment]
Okay, so that means that while it is processing, adding items to the pyre is causing it to reset the currently stored inventory/current recipe... okay, I'll dig into that once I finish beating rotations into submission with a right-angle shotgun.

**Comment by noobanidus** [comment]
Okay, I can reproduce it.
