### ISSUE TITLE
About Healing Aura ritual's Patchouli guidebook visualization misleading

### ISSUE THREAD

**Issue by RisingInIris2017** [EpicSquid/Roots#384]
### General Information
**Describe the bug:**

Even though all blocks shown by The Druidic Arts are placed at there respective correct positions,
and ritual is started normally, there is still a progress bar shows "6/16".

**To Reproduce:**

1. Use The Druidic Arts to show Healing Aura ritual's visualization.
2. Place Pyre, Birch logs and leaves, Runic Stones according to the visualization.
3. You will find that progress bar shows "6/16".
4. Put all items needed for starting the ritual, and kindle the Pyre.
5. You will find that though ritual is started successfully, the progress above is still shows "6/16".

**Expected behavior:**

The visualization should show "Finish" instead of showing what I described above.

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: mysticallib-1.12.2-1.6.0
- mysticalworld-1.12.2-1.7.1
- Roots-1.12.2-3.0.24

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 14.23.5.2847
- Minecraft: 1.12.2

***

### Additional Information
**Screenshots (if available):**

![](https://user-images.githubusercontent.com/28519848/74723360-68bba280-5275-11ea-81f7-cf8ae9359af2.png)

![](https://user-images.githubusercontent.com/28519848/74723375-6ce7c000-5275-11ea-8ee1-6b9d01cf42b2.png)
**Additional context (optional):**
I have found that, those 10 missing blocks is Birch leaves.
Ritual can be started without those leaves, so the altar is finished when it is still showing 6/16.
But I think this may be misleading, and that progress bar is quite annoying.
Would you like to change this? 
Maybe this post is a suggestion instead of bug report?

Thanks for your consistently warm-hearted help!
Look forward to your reply!

**Comment by noobanidus** [comment]
If you go back into the Patchouli guide and click the "eye" again, it will "unvisualise" and remove the progress bar. (It's a bit unclear in Patchouli itself)
