### ISSUE TITLE
Oversight related to Light Drifter in multiplayer.

### ISSUE THREAD

**Issue by KingEdward9830** [EpicSquid/Roots#387]
### General Information

**Describe the bug:**
Spectator mode doesn't *just* let you fly fast, if you press middle click in multiplayer it also lets you teleport to other players. Normally not an issue, but the problem lies in the fact that this teleport works cross-dimensionally while your "recall" teleport does NOT.

**To Reproduce:**
1. Play Multiplayer with at least one other player, who is in a different dimension from you
2. Cast light drifter
3. Use middle click&scroll to teleport to them while in spectator
4. Observe as you get teleported to some random place, for me it was in a wall in the Nether, when light drifter ends.

**Expected behavior:**
Being teleported back to my starting dimesnion rather than into a wall.

***

### Environment Versions
Roots-1.12.2-3.0.25

**Mystic Mods Versions**

- MysticalLib: 1.12,2-1.6.0
- Mystical World 1.12.2-1.7.1

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 14.23.5.2847
- Minecraft: 1.12.2
- Modpack (if available):

***

### Logging Information

**Latest Log (if necessary):**
Let me know if you need it.

**Comment by noobanidus** [comment]
Ooh, I hadn't considered that before. I believe this is the same implementation (Core functionality-wise) as was used in the original Roots, so it's possible that it was just an oversight along the way. I'll have to think of a way to handle it, thanks!

**Comment by KingEdward9830** [comment]
Lost my stuff in the process of finding this out, so I'm glad to hear the report was helpful :stuck_out_tongue_closed_eyes:

**Comment by noobanidus** [comment]
Sorry that your server admin is a bit of a douche/didn't install a gravestone mod.

I've come up with a potential solution which is to remove access to the GUI. It still won't stop people from spoofing it with packets, which is pretty difficult, but I don't want to even begin trying to handle dimension transit.
