### ISSUE TITLE
Life Essence is... enchantable?

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#388]
I'm not sure if you meant to do this, and I'll fully admit I haven't tested this without PiTweaks yet to make sure, but JEI says Life Essences can take both Unbreaking and Mending enchantments.  Mending is Forever... and it wouldn't surprise me in the slightest if Manabound works on it too.

Immersive Engineering dealt with this on its hammer by making the damage attribute an NBT tag instead of using the damage property.  Even with PiTweaks installed, and forcibly adding Unbreaking and Mending to an IE hammer, I can't repair it or slow the damage it takes that way.

**Comment by noobanidus** [comment]
Hm, Mending shouldn't be possible and probably won't work but Unbreaking was intentional.

**Comment by noobanidus** [comment]
Okay, looking into it more, it's the fact that the item is damageable that automatically makes it enchantable (and the fact that it only stacks up to one). Those automatic enchantments that are allowed include Mending and Unbreaking, or anything else that is classified as "BREAKABLE".

I've modified it to only work with the Unbreaking enchant specifically.

**Comment by noobanidus** [comment]
In the interim, you can actually use CraftTweaker to change the recipe for the ritual if you need a temporary solution as documented [here](https://docs.blamejared.com/1.12/en/#Mods/Roots_3/ritual/).
