### ISSUE TITLE
Use ore:egg for Summon Animal ritual

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#389]
If Animania is installed, chickens lay eggs.  Animania eggs.  Also Animania likes to disable egg drops and vanilla chickens.  However, currently the Summon Creatures ritual ingredient uses vanilla eggs only.  It looks like summoning vanilla chickens only requires an oreDict egg though.

In the meantime, I'll fix this in my modpack by letting players craft Animania eggs to vanilla ones.

**Comment by noobanidus** [comment]
I wasn't aware that egg had an ore dictionary entry; I'll adjust it presently.
