### ISSUE TITLE
NOOO I AM SET ON FIRE

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#397]
### General Information

**Describe the bug:**
Using 3.1.0 alpha 2 build, I used the Light Drifter spell to chill underground and I seem to return without taking suffocation damage just fine, even when moving really fast.  But the log that I "moved wrongly!" worried me so I also attempted to chill in lava with Light Drifter and..... I indeed seem to have been set on fire.

### Environment Versions
Roots 1.12.2-3.1.0-alpha

**Mystic Mods Versions**
Mystical Lib 1.12.2-1.7.0-alpha (reports internally as 1.1.1...)
Mystical World 1.12.2-1.8.0-alpha

**Comment by noobanidus** [comment]
Argh! That's the whole point of the extinguish call. I wonder whether I can make a flag that just flat otu makes the player immune to fire...

**Comment by SpoilersMC** [comment]
@DoomRater you asked about the mod showing the tooltip on dropped items on my last issue, its called world tooltips.

**Comment by noobanidus** [comment]
Turns out this is handled in multiple places.
