### ISSUE TITLE
Current 3.1.0 alpha issues

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#404]
Here's everything I've noticed so far with the 3.1.0 alpha 2 build:
-Chrysopoeia name in JEI is currently tagged as "container.roots.transustantiation.name"
-Spell Recipes has a bad link to Herbs
-Saturate's warning text falls off the bottom of the book
-Scatter's ending punctuation is missing
-The bottom of Spring Storm's text is running into the book edge
-Shift-right-clicking a Pyre in creative mode overwrites what's in the Pyre
-Grove Supplication Ritual's name is currently tagged as "item.ritual_grove_supplication.name"
-Offering Plate text falls off the bottom of the block
-Offering Plate has a bad link to rituals
-Fey Fire's grammar structure unclear. Suggestion: change "...hostile creatures, animals and items unaffected." to "...hostile creatures, with animals and items left unaffected."
-Sylvan Armor text runs into the book edge
-Natural Resources has a bad link to rituals
Slightly bigger issues:
-Right-clicking any variant of Elemental Soil with any variant of Elemental Soil gives the player a dirt block(?) and doesn't consume the existing block, and can be repeated with the same type of elemental block to gain infinite dirt

**Comment by noobanidus** [comment]
Thanks!

The latter is something I'm aware of, I might file a separate issue for it.

**Comment by noobanidus** [comment]
Final point has been addressed.

**Comment by noobanidus** [comment]
Turns out Patchouli doesn't have the ability to link to categories directly, you must link to an entry. That's... so dumb.

**Comment by noobanidus** [comment]
> -Shift-right-clicking a Pyre in creative mode overwrites what's in the Pyre

This is actually intentional, do you think it's problematic?

EDIT: So, I've addressed everything else and I'll do alpha3 some time tonight; curious about this question though.

**Comment by DoomRater** [comment]
In creative, not so much since anything accidentally lost that way can be rebuilt (say, accidentally adding off hand items to the Pyre).  That might be something to raise as a separate issue- I don't think Botania or Thaumcraft put what's in the off hand directly onto their pedestals and altars.  I need to double check what they do as I can't recall at the moment.
