### ISSUE TITLE
[Inquiry] [Mystical World] Resource pack incompatibility or am I missing something?

### ISSUE THREAD

**Issue by Azure-Flame** [EpicSquid/Roots#407]
I've been working on a modpack and in turn messing around with a resource pack to have it extend into Mystical World. The block in question is the Amethyst Ore.
I am attempting to add a model to the Ore that makes it appear as a stone block (texture pulled from Minecrafts default stone) with rectangles poking out of it to look like ore chunks (using Mystical Worlds 'Amethyst Block' texture.)
The model is meant to use the same name as the ore block itself, however- even checking and double checking the ores name ingame and via the textures of the mod it does not apply the model. Am I missing something here, or is the asset named something completely different in the mod that I'm not finding?
The name I have found and am using for the resource pack is:
amethyst_ore
and in the resource pack the path is:
assets/mysticalworld/models/block

**Comment by noobanidus** [comment]
Most of the blocks are currently made short-hand with a blockstate. You'll need to modify the blockstate to point to the new model in question, as there isn't one for you to override; it should just be a matter of setting the default model from "cube-all" to whatever model you specify.

**Comment by Azure-Flame** [comment]
Sorry, I am going to be honest- I have no idea what any of that means. I have no experience in the deeper details of Minecraft or Modding, so can you please explain that to me?

**Comment by noobanidus** [comment]
Okay, so, you'd need to create a "blockstates" folder in your folder, and copy in something like ([from the blockstate already existing](https://github.com/MysticMods/MysticalWorld/blob/master/src/main/resources/assets/mysticalworld/blockstates/amethyst_ore.json)):

```json
{
  "forge_marker": 1,
  "defaults": {
    "model": "mysticalworld:amethyst_ore",
    "uvlock": true
  },
  "variants": {
    "normal": [
      {}
    ],
    "inventory": [
      {}
    ],
    "handlers": [
      {}
    ]
  }
}
```

At this point, it should point at the model in `assets/mysticalworld/block/amethyst_ore` that you're created.
