### ISSUE TITLE
check balance on healing aura

### ISSUE THREAD

**Issue by majijn** [EpicSquid/Roots#408]
with the amount it heals and the length of time it heals this ritual feels to me like it shouldnt require the standing stones or the tree , and serve as a portable healing ritual.

with perhaps having some kind of boost to the amount healed if there are standing stones/trees in the area. or just an entirely different ritual deeper in the progression that either heals for longer periods of time/heals for more hp in total.

**Comment by noobanidus** [comment]
I've tweaked this slightly and allowed it to heal non-players for more than it heals players for, and also have it heal non-players more regularly. Should make it only heal non-hostiles as well?

**Comment by majijn** [comment]
probably, yeah, if its boosted on non-players it shouldnt heal hostiles, or maybe hostile undeads
