### ISSUE TITLE
[Roots 3] "Cancel" ongoing rituals by dousing them with a bucket of water

### ISSUE THREAD

**Issue by duely** [EpicSquid/Roots#41]
Alternately to just right clicking to place a single item, additionally allowing to shift-right click with an item stack in hand to insert the entire item. Once the recipes is completed, it would just decrement the items and begin all over again (without having to be lit).

This would obligate some way to see how many items are left in the pyre.

Additionally, there would need to be some method of "dousing" the flames and stopping the ritual. I recommend simply right-clicking with a bucket of water.

**Comment by EpicSquid** [comment]
Mart, worth looking into the bucket dousing idea as well.

**Comment by duely** [comment]
I'm classing this as a bug because there isn't actually a way to cancel rituals.
