### ISSUE TITLE
airborne feylights 

### ISSUE THREAD

**Issue by majijn** [EpicSquid/Roots#418]
it might be nicer to use feylight if it didnt fizzle if there's no blocks for it to place the lights against and simply placed them midair at the end of its range instead, or having an imbuement that lets them be placed without the need of a block being targetted

**Comment by noobanidus** [comment]
This should definitely be possible.

**Comment by noobanidus** [comment]
If we just find the end-point of the actual ray-trace and check if it's an air block or not, we can place there instead of relying on a hit. I think a miss actually guarantees that it's an air block, so it's a matter of getting what blockpos it is?
