### ISSUE TITLE
Alpha Test weapon balance

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#431]
I like where the damage is going.  The Runic Claymore has a lovely damage output and feels good in the hands.  Yes, hands, you've got the first person render showing Steve kinda showing the point to anyone dumb enough to challenge him.  That'd be cool to follow up on and see a custom animation for as well.  The only caveat is that I'd want the render to work with Armourer's Workshop.

But let's take a second pass at the numbers on the Runic Shovel.  Attack Damage for it and the Runic Smasher seem like they were swapped, and the Attack Speed wasn't reduced on the Runic Shovel either.  Swapping those numbers and a .5 attack speed on the Runic Shovel bring it in line with the DPS of the Claymore, but still allow plenty of BONK.  I can jump strike kill most hostile mobs with one hit with 13.5 damage, and 18.5 damage will off zombies with a jump strike.

One more thing- The hoe has an attack speed of 5.5? Vanilla's mercy invincibility will cause most of those hits to not deal any damage. Honestly anything faster than 2 seems to be wasteful unless you're hitting multiple targets, fairly hard to do without being surrounded.

**Comment by noobanidus** [comment]
Yeah, I'm not actually sure why those values are what they are. Custom animations are unlikely to happen as it's literally something I've no experience with, unfortunately.

The Runic Shovel is not supposed to be that high. Part of the issue with high numbers is that, even with low speed, the hammer can still be spammed in a non-effective way to do more damage than swords -- in some instances. 

I don't know why the hoe attack speed is that. That does not make sense.

**Comment by noobanidus** [comment]
Okay, so the majority of these issues simply come from Vanilla's calculations. The hoe's base speed is calculated off the tool attack damage, for some reason. I'm not sure why the shovel is doing what it's doing, but I think I'll need to override some values.

**Comment by DoomRater** [comment]
My main modpack uses Combat Refined, which shuts down click spam under all but some edge cases.  It's also made me prefer my Ex Nihilo Hammer, simply because it has a 4 attack speed.

Thaumic Augmentation said its base damage for the Primal Cutter it adds is a little wonky and there's a damage calculation issue going on with it, so the number someone puts in only relates to the final damage result in some way.  It's supposed to be a sword and an axe as one, like how the Primal Crusher is a pickaxe and shovel in one.  I'm not sure if there's something with vanilla that causes their value to be wonky compared to what you get, or if it's just a result of the tool being both a sword and axe at once.

**Comment by noobanidus** [comment]
The shovel was easily adjusted... working on the hoe now, which is slightly more complex.
