### ISSUE TITLE
[Alpha Test] Runic Claymore in left hand looks different

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#434]
![2020-03-21_10 25 31](https://user-images.githubusercontent.com/53404970/77231803-e1c85580-6ba5-11ea-85b3-17a366459854.png)
It's looks cool....

**Comment by DoomRater** [comment]
For the record, left hand is my main hand!

**Comment by noobanidus** [comment]
Whoops. I'll see if I can fix that. I inverted my logic somewhere along the lines.

**Comment by DoomRater** [comment]
Oh the Great Axe does this in the left hand as well.

**Comment by noobanidus** [comment]
Ah, this was fixed.
