### ISSUE TITLE
Terrastone and Runic Tool regeneration seems inconsistent

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#439]
I watched the numbers on a tool go up by two, then take a while, then go up another.... and sometimes even go back down.  Here's a video.
https://imgur.com/a/8TUp0gW

**Comment by noobanidus** [comment]
~~They're both randomised and use the same algorithm as living tools; I need to tweak all of them though so there's a bit more sequence.~~

It's triggering on both sides for some reason but using random values, hence the desync.
