### ISSUE TITLE
Unreliable pouch opening when bound to a mouse button

### ISSUE THREAD

**Issue by ChiefLogan3010** [EpicSquid/Roots#441]
### General Information

**Describe the bug:**
With open pouch bound to one of my mouse buttons (tested with middle click, button 4 and button 5), opening the pouch is unreliable. For every 10 or so clicks it might actually open.

**To Reproduce:**
1. Bind "open pouch" to a mouse button.
2. Try to open the pouch using this button.

**Expected behavior:**
The pouch will open every time I click

### Environment Versions
- Roots: 1.12.2-3.0.26
- MysticalLib: 1.12.2-1.7.0
- Mystical World: 1.12.2-1.8.1

### Logging Information
Nothing relevant in log

**Comment by ChiefLogan3010** [comment]
After submitting this I decided to try some of the other keybinds on the mouse buttons and it seems to be the same for all the ones I tested (next slot, previous slot, first slot, second slot). What's stranger is that it seems to be more reliable when the player is moving compared to when they're stationary.

**Comment by noobanidus** [comment]
Can you clarify if you have any other mods running that might be interfering with keybinds?

Also, does it happen with normal keys or just the mouse keys? From what I gather the behaviour you're describing is purely with mouse buttons.

**Comment by ChiefLogan3010** [comment]
Apologies for the late reply, I just loaded up an instance with only the mods required to run roots (plus JEI) and I had the same problem. It's just the mouse buttons that the issue occurs with.

**Comment by noobanidus** [comment]
Okay, so digging a little further, it seems that the mouse buttons themselves don't, for some reason, trigger the standard key event that we're using to detect if a keybind has been pressed. I'm going to attempt to adjust it to just accept the standard InputEvent, mouse or keyboard.
