### ISSUE TITLE
Crash when digging flower (ender daisy) from the enderman evolution mod

### ISSUE THREAD

**Issue by SAIANBY** [EpicSquid/Roots#447]
Crash when digging flower (ender daisy) from the enderman evolution mod.

Forge version 1.12.2-14.23.5.2847
mysticallib-1.12.2-1.7.0
mysticalworld-1.12.2-1.8.3.jar
Roots-1.12.2-3.0.26.jar

EndermanEvolution-1.12.2-1.0.33.jar
Patchouli-1.0-20.jar

[Crash report](https://paste.dimdev.org/odokasocaz.mccrash)
[Full log](https://paste.ee/p/55yeq)

**Comment by noobanidus** [comment]
Issue is with Enderman Evolution mod. They need to be registing their custom plant type in static initialization and loaded it ASAP. Something is causing a look up of "hey what are the custom plant types" *before* theirs is registered, and that locks the list at that point.
