### ISSUE TITLE
[1.12.2] Pouches can delete items.

### ISSUE THREAD

**Issue by SonicX8000** [EpicSquid/Roots#448]
Minecraft: 1.12.2
Forge: 14.23.5.2847

Mods: 5
jei_1.12.2-4.15.0.291
mysticallib-1.12.2-1.7.0
mysticalworld-1.12.2-1.8.2
Patchouli-1.0-20
Roots-1.12.2-3.0.26

=====

GIF:
https://cdn.discordapp.com/attachments/377171551155650560/697297524796424394/rootspouchbug.gif

This occurs with any pouch.

Open it with either a key press or right-click and put in for example... 32 Sand Blocks, close it... and reopen it and store some more sand blocks on the same stack & close it. Now... when you reopen it... you'll noticed that your stacksize of Sand Blocks is still 32.

This also happens with any herb materials pouch in the other slots.

**Comment by noobanidus** [comment]
Hm. This ... means something isn't firing somewhere.

**Comment by noobanidus** [comment]
Oh, but the fix *is* in the unreleased 3.1 branch. So yeah, this should be fixed when 3.1 comes out.

**Comment by DoomRater** [comment]
Can confirm in 3.0.25 as well... Looks like shift clicking protects the stack, so that should be a usable workaround until the fix comes out.

**Comment by noobanidus** [comment]
Yeah, I'm going to aim to get a 3.1 release out soon even if I don't have the modifier overhaul/staff library change

**Comment by noobanidus** [comment]
@DoomRater is it resolved in 3.1 though?

**Comment by DoomRater** [comment]
Everything looks good in the 3.1 alpha6 build I have here.
