### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#449]
[crash-2020-04-11_12.12.26-client.txt](https://github.com/MysticMods/Roots/files/4464324/crash-2020-04-11_12.12.26-client.txt)

**Comment by noobanidus** [comment]
Please update your version of Roots. 3.0.2 is ancient. 3.0.26 is the most recent release.

**Comment by noobanidus** [comment]
(And possibly Mystical World.)

**Comment by guide-for-you** [comment]
So,something strange happened, as if something new appeared in the releases tab and I downloaded the old version thinking it was new
