### ISSUE TITLE
Pyre Item Dupe

### ISSUE THREAD

**Issue by Drathonix** [EpicSquid/Roots#450]
Upon breaking the pyre when the pyre contains items, the items double on drop.

How to reproduce:
1. Place down the pyre
2. Put the items into the pyre
3. Break the pyre
4. Items drop doubled, besides the pyre.

Installed: 
forge-14.23.5.2847
mysticallib-1.12.2-1.7.0
mysticalworld-1.12.2-1.8.4
Roots-1.12.2-3.0.26

**Comment by noobanidus** [comment]
That is unexpected. Thanks! I'll test to see whether this is still the case in 3.1.

**Comment by DoomRater** [comment]
I tried in a single player world using 3.1.0 alpha6, with both types of pyres, and so far I can't seem to reproduce it.

**Comment by noobanidus** [comment]
Yeah, I think this is something that I've inadvertently fixed along the way. I'll keep an eye on it though.

**Comment by Drathonix** [comment]
OK I've found the actual problem and its not on your part. This is an issue with MultiMine, it has dupes with a number of modded blocks each one tending to double as shown by this one, so now you know.

**Comment by noobanidus** [comment]
Ah, interesting! I'll keep that noted.

**Comment by ubergarm** [comment]
I came across this when googling, and yeah was multimine for me too! Adding this bit of `multimine.cfg` fixed it for me for all of these blocks (i left bonsai trees in there in case anyone wanted to see a regex example):
```
bannedblocks {
    B:"^bonsaitrees"=true
    B:"^botanicbonsai"=true
    B:"roots:mortar"=true
    B:"roots:bonfire"=true
    B:"roots:incense_burner"=true
    B:"roots:imbuer"=true
    B:"roots:fey_crafter"=true
}
```
