### ISSUE TITLE
[Roots 3] Cloud Berry can be grown on normal soil

### ISSUE THREAD

**Issue by duely** [EpicSquid/Roots#46]
I was attempting to "carve" the runic soil with a knife in my main hand and the cloud berries in my off-hand, and instead if simply planted it directly on the soil. I thought this was strange. I tried planting it in the fertile farmland to the right, and it planted -- and then what was on the runic soil "popped off".

I can now plant all three of my cloud berry seeds on normal farm land and water them with a watering can to cause their growth stage to progress.

![](https://i.imgur.com/GLkMLrk.png)

![](https://i.imgur.com/XGjfm2H.png)

**Comment by duely** [comment]
Additionally it's possible to plant Cloud Berry in mid-air. I ... definitely think there is a problem somewhere.

![](https://i.imgur.com/2PstBuO.png)

**Comment by tyler489** [comment]
HEH.... "cloud" berry.... i see no issue here

**Comment by Davoleo** [comment]
afaik it happens with Infernal Bulb, Dewgonia and Stalicripe too

**Comment by duely** [comment]
@tyler489 LOL

@Davoleo It happens with every IPlantable atm, I think.

**Comment by EpicSquid** [comment]
Fixed by being mad at Block being the repository for all crop stuff
