### ISSUE TITLE
(alpha7) unending bowl doesnt fill or empty buckets, crashes when an empty bottle is used upon it.

### ISSUE THREAD

**Issue by majijn** [EpicSquid/Roots#485]
pastebin.com/zh5eX3ib

**Comment by Davoleo** [comment]
I couldn't reproduce the crash
the vanilla bucket fills correctly when in survival mode (in creative the empty bucket never fills and the water bucket never empties)
Video of some of the tests: https://streamable.com/bb14hp

(glass bottles don't fill or empty though, even in gm 0)
