### ISSUE TITLE
check client pouch handler

### ISSUE THREAD

**Issue by majijn** [EpicSquid/Roots#487]
fully emptying a herb pouch of any colour by shift clicking everything out seems to cause all other pouches to not contain anything in them until a spell is cast

**Comment by DoomRater** [comment]
I'm trying to reproduce but I can't seem to.  Do you have a creative pouch in your inventory somewhere?  For some reason, it has a pouch inventory but only when opened with the hotkey, which could be confusing.

**Comment by noobanidus** [comment]
Was anyone able to reproduce this? I'll leave it for alpha8.

**Comment by majijn** [comment]
ah in the end this was caused by a third mod duping the pouch i had and me dying them different colours and not understanding where the herbs were saved 

im gonna close this
