### ISSUE TITLE
(Roots 3/Mystical World)Model problems

### ISSUE THREAD

**Issue by Wotzinator** [EpicSquid/Roots#49]
im using:
   forge:14.23.5.2815
   mystical lib:1.1.1
   mystical world:1.2.0
   patchouli:1.0-17
   roots:3.0.0-2

ok there are a few problems with models .firstly the knives from mystical world and the 2 from roots have the normal item model not the tool one.the tool from roots(living hoe,axe etc)suffer from the same problem.and also all armors that should have 3d armors just show the "no texture"texture on the default armor model.

**Comment by Martacus** [comment]
The armors dont yet have models indeed, thats a known issue.

**Comment by Martacus** [comment]
Also what do you mean that there is something wrong with the models. Eveyrthing looks fine, can you provide pictures?

**Comment by Wotzinator** [comment]
they are held like normal items(cakes,cookies etc) and not like tools.

**Comment by Martacus** [comment]
Oh like that, I'll take a look
