### ISSUE TITLE
Renaming knives internally will break Dynamic Surroundings support

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#490]
Currently DS looks for itemDruidKnife, not itemMageKnife.  If you change it internally, Dynamic Surroundings will need to update to reflect this change.  Not critical, but you said to remind you if it didn't happen that night.

**Comment by noobanidus** [comment]
Ty, this issue will help me remember to change it back. I umm'd and ahh'd before renaming and then decided to just go ahead with it, but with this knowledge, I'll revert back, as it doesn't really cause any issues internally.

**Comment by noobanidus** [comment]
Oh, I undid this.
