### ISSUE TITLE
Gathering ritual dupe items

### ISSUE THREAD

**Issue by Serega007RU** [EpicSquid/Roots#491]
### General Information

**Describe the bug:**
Gathering ritual dupe items

**To Reproduce:**
1. Activate two side-by-side Gathering rituals
2. Very quickly drop items

**Expected behavior:**
Items must not be duplicated

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 1.12.2-1.7.0
- Mysticalworld: 1.12.2-1.8.4

### Additional Information
https://youtu.be/U6x7fGMyMV0?t=209

**Comment by noobanidus** [comment]
Whoops.

**Comment by noobanidus** [comment]
Pretty sure I know exactly what this is, and pretty sure I should've known better.

**Comment by noobanidus** [comment]
Pushing 3.0.28 shortly, thanks for the heads up!
