### ISSUE TITLE
Component pouch dupe

### ISSUE THREAD

**Issue by ChromaPIE** [EpicSquid/Roots#492]
### General Information

**Describe the bug:**
Way to duplicate things with component pouch. The apothecary pouch may have the same problem, anyway this is not tested.

**To Reproduce:**

1. Right click quickly after pressing Q, almost at the same time.
2. The GUI of the pouch would be opened, if everything went right, the pouch should be on the ground now, but things in it could be taken out via the GUI.
3. Pick the pouch up and there would be one more copy of all the things in it at the beginning.

**Expected behavior:**

The dupe is fixed.
***

### Environment Versions
Roots-1.12.2-3.0.21

**Mystic Mods Versions**

- mysticallib-1.12.2-1.4.0
- mysticalworld-1.12.2-1.6.1

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by Davoleo** [comment]
I am pretty sure this has been fixed in one of the future versions, try updating Roots

**Comment by noobanidus** [comment]
It's also fixed in 3.1 which will hopefully be released soon.
