### ISSUE TITLE
starting up erro

### ISSUE THREAD

**Issue by Protodragon01** [EpicSquid/Roots#494]
https://paste.dimdev.org/uzigipikeg.mccrash

When my minecraft is starting up it gets an error and it says that roots is the one causing the error

**Comment by noobanidus** [comment]
That URL is invalid.

I would recommend ensuring that you have:

a) Updated MysticalLib to the latest version for 1.12.2
b) Updated MysticalWorld to the latest version for 1.12.2
c) likewise updated Roots to the latest version for 1.12.2

These are generally the causes of issues that people tend to have.
