### ISSUE TITLE
crashes on startup (1.12.2) even with newest version of everything

### ISSUE THREAD

**Issue by anonymus411** [EpicSquid/Roots#495]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  wings (wings-1.1.6-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.0-pre198_mc1.12.2.jar)
  Quark Plugin (Quark-r1.6-177.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  CorePlugin (ForgeEndertech-1.12.2.jar)
  FutureMC (future-mc-0.1.13.jar)
  FMLPlugin (elulib-0.1.12.jar)
  llibrary (llibrary-1.7.7-1.12.2.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  monstersandpets (ldshadowlady-monstersandpets-1.0.1-1.12.jar)
  LoadingPlugin (Xaeros_Minimap_20.3.0_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 5/7/20 10:42 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Roots (roots)
Caused by: java.lang.NoClassDefFoundError: epicsquid/roots/capability/runic_shears/RunicShearsCapability
	at epicsquid.roots.Roots.preInit(Roots.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.GeneratedMethodAccessor8.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: epicsquid.roots.capability.runic_shears.RunicShearsCapability
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 41 more
Caused by: java.lang.NoClassDefFoundError: epicsquid/mysticallib/capability/EntityCooldownCapability
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 43 more
Caused by: java.lang.ClassNotFoundException: epicsquid.mysticallib.capability.EntityCooldownCapability
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 412850072 bytes (393 MB) / 939524096 bytes (896 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_E3 85 mods loaded, 83 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                      | Version           | Source                                                | Signature                                |
	|:----- |:----------------------- |:----------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft               | 1.12.2            | minecraft.jar                                         | None                                     |
	| LCH   | mcp                     | 9.42              | minecraft.jar                                         | None                                     |
	| LCH   | FML                     | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                         | None                                     |
	| LCH   | forge                   | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                         | None                                     |
	| LCH   | creativecoredummy       | 1.0.0             | minecraft.jar                                         | None                                     |
	| LCH   | littletilescore         | 1.0.0             | minecraft.jar                                         | None                                     |
	| LCH   | xaerominimap_core       | 1.12.2-1.0        | minecraft.jar                                         | None                                     |
	| LCH   | srm-hooks               | 1.12.2-1.0.0      | minecraft.jar                                         | None                                     |
	| LCH   | futuremccore            | 0.1.12            | minecraft.jar                                         | None                                     |
	| LCH   | elucore                 | 1.0               | minecraft.jar                                         | None                                     |
	| LCH   | advancedcombat          | 1.1.2             | advancedcombat-1.1.2-[1.12].jar                       | None                                     |
	| LCH   | baubles                 | 1.5.2             | Baubles-1.12-1.5.2.jar                                | None                                     |
	| LCH   | atum                    | 2.0.17            | Atum-1.12.2-2.0.17.jar                                | None                                     |
	| LCH   | jei                     | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                             | None                                     |
	| LCH   | quark                   | r1.6-177          | Quark-r1.6-177.jar                                    | None                                     |
	| LCH   | autoreglib              | 1.3-32            | AutoRegLib-1.3-32 (1).jar                             | None                                     |
	| LCH   | babymobs                | 1.5.5             | BabyMobs-1.12-1.5.5.jar                               | None                                     |
	| LCH   | bno                     | 1.12.2-1.0.4.0    | BasicNetherOres-1.12.2-1.0.4.0.jar                    | None                                     |
	| LCH   | bibliocraft             | 2.4.5             | BiblioCraft[v2.4.5][MC1.12.2].jar                     | None                                     |
	| LCH   | bloodmoon               | 1.5.3             | Bloodmoon-MC1.12.2-1.5.3.jar                          | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LCH   | bonsaitrees             | 1.1.4             | bonsaitrees-1.1.4-b170.jar                            | None                                     |
	| LCH   | bookshelf               | 2.3.585           | Bookshelf-1.12.2-2.3.585.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | bookworm                | 1.12.2-2.5.1      | bookworm-1.12.2-2.5.1.jar                             | None                                     |
	| LCH   | carryon                 | 1.12.1            | CarryOn MC1.12.2 v1.12.1.jar                          | 55e88f24d04398481ae6f1ce76f65fd776f14227 |
	| LCH   | chameleon               | 1.12-4.1.3        | Chameleon-1.12-4.1.3.jar                              | None                                     |
	| LCH   | chickens                | 6.0.4             | chickens-6.0.4 (2).jar                                | None                                     |
	| LCH   | ctm                     | MC1.12.2-1.0.1.30 | CTM-MC1.12.2-1.0.1.30.jar                             | None                                     |
	| LCE   | roots                   | 1.12.2-3.0.28     | Roots-1.12.2-3.0.28 (1).jar                           | None                                     |
	| LC    | mysticalworld           | 1.12.2-1.8.4      | mysticalworld-1.12.2-1.8.4.jar                        | None                                     |
	| LC    | chisel                  | MC1.12.2-1.0.1.44 | Chisel-MC1.12.2-1.0.1.44 (1).jar                      | None                                     |
	| LC    | chiselsandbits          | 14.33             | chiselsandbits-14.33 (1).jar                          | None                                     |
	| LC    | cookingforblockheads    | 6.5.0             | CookingForBlockheads_1.12.2-6.5.0.jar                 | None                                     |
	| LC    | craftstudioapi          | 1.0.0             | CraftStudioAPI-universal-1.0.1.95-mc1.12-alpha.jar    | None                                     |
	| LC    | creativecore            | 1.9.9             | CreativeCore_v1.9.90_mc1.12.2.jar                     | None                                     |
	| LC    | customspawner           | 3.11.4            | CustomMobSpawner-3.11.4.jar                           | None                                     |
	| LC    | ptrmodellib             | 1.0.4             | PTRLib-1.0.4.jar                                      | None                                     |
	| LC    | props                   | 2.6.3             | Decocraft-2.6.3_1.12.2 (1).jar                        | None                                     |
	| LC    | mocreatures             | 12.0.5            | DrZharks MoCreatures Mod-12.0.5.jar                   | None                                     |
	| LC    | enderzoo                | 1.12.1-1.4.0.49   | EnderZoo-1.12.1-1.4.0.49.jar                          | None                                     |
	| LC    | golems                  | 7.1.8             | Extra-Golems-Mod-1.12.2.jar                           | None                                     |
	| LC    | extrautils2             | 1.0               | extrautils2-1.12-1.9.9.jar                            | None                                     |
	| LC    | fairylights             | 2.1.6             | fairylights-2.1.6-1.12.2.jar                          | None                                     |
	| LC    | forgeendertech          | 1.12.2-4.5.0.0    | ForgeEndertech-1.12.2.jar                             | None                                     |
	| LC    | cfm                     | 6.3.1             | furniture-6.3.1-1.12.2.jar                            | None                                     |
	| LC    | minecraftfuture         | 0.1.13            | future-mc-0.1.13.jar                                  | None                                     |
	| LC    | gardenstuff             | 1.12-2.1.1        | GardenStuff-1.12-2.1.1.jar                            | None                                     |
	| LC    | gravestone              | 1.10.2            | gravestone-1.10.2.jar                                 | None                                     |
	| LC    | waila                   | 1.8.26            | Hwyla-1.8.26-B41_1.12.2.jar                           | None                                     |
	| LC    | japaricraftmod          | 5.5.0             | japaricraftmod-1.12.2-5.5.0.jar                       | None                                     |
	| LC    | chickendungeons         | 1.0.1             | ldshadowlady-chickendungeons-1.0.1.jar                | None                                     |
	| LC    | customcraftingtables    | 1.0.0             | ldshadowlady-customcraftingtables-1.0.jar             | None                                     |
	| LC    | llibrary                | 1.7.7             | llibrary-1.7.7-1.12.2.jar                             | None                                     |
	| LC    | monstersandpets         | 1.0.1             | ldshadowlady-monstersandpets-1.0.1-1.12.jar           | None                                     |
	| LC    | disney                  | 1.0.0             | ldshadowlady-disney-1.0.jar                           | None                                     |
	| LC    | youtuberzombies         | 1.0.0             | ldshadowlady-youtuberzombies-1.0.jar                  | None                                     |
	| LC    | littletiles             | 1.5.0             | LittleTiles_v1.5.0-pre198_mc1.12.2.jar                | None                                     |
	| LC    | magicclover             | 1.12-0.7.8        | magicclover-1.12-0.7.8.jar                            | None                                     |
	| LC    | maidensmaterials        | 3.3               | Maiden's+Marvelous+Materials-3.3.jar                  | None                                     |
	| LC    | mopickaxes              | 10.0: Final BETA  | Mo-Pickaxes-Mod-1.12.2.jar                            | None                                     |
	| LC    | morechickens            | 3.1.0             | morechickens-1.12.2-3.1.0 (1).jar                     | None                                     |
	| LC    | naturescompass          | 1.8.3             | Natures-Compass-Mod-1.12.2.jar                        | None                                     |
	| LC    | neverenoughcandy        | 1.2.3             | NeverEnoughCandy-1.12.2-1.2.3.jar                     | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | outfox                  | 0.1.4             | outfox-0.1.4-mc1.12.2.jar                             | None                                     |
	| LC    | patchouli               | 1.0-20            | Patchouli-1.0-20.jar                                  | None                                     |
	| LC    | placeableitems          | 3.3               | placeableitems-3.3.jar                                | None                                     |
	| LC    | roost                   | 2.0.10            | roost-1.12.2-2.0.10.jar                               | None                                     |
	| LC    | scollectibles           | demo              | scollectibles-1.1.jar                                 | None                                     |
	| LC    | secretroomsmod          | 5.6.4             | secretroomsmod-1.12.2-5.6.4.jar                       | None                                     |
	| LC    | storagedrawers          | 1.12.2-5.4.0      | StorageDrawers-1.12.2-5.4.0.jar                       | None                                     |
	| LC    | unlimitedchiselworks    | 0.3.1             | UnlimitedChiselWorks-0.3.1.jar                        | None                                     |
	| LC    | storagedrawersunlimited | 1.12.2-1.3.0      | StorageDrawersUnlimited-1.12.2-1.3.0.jar              | None                                     |
	| LC    | travellersbackpack      | 1.0.22.22         | TravellersBackpack-1.12.2-1.0.22.22.jar               | None                                     |
	| LC    | treechopper             | 1.2.4             | TreeChopper-1.12.2-1.2.4.jar                          | None                                     |
	| LC    | twilightforest          | 3.10.1013         | twilightforest-1.12.2-3.10.1013-universal (2).jar     | None                                     |
	| LC    | ultimate_unicorn_mod    | 1.5.16            | ultimate_unicorn_mod-1.12.2-1.5.16.jar                | None                                     |
	| LC    | wearablebackpacks       | 3.1.4             | WearableBackpacks-1.12.2-3.1.4.jar                    | None                                     |
	| LC    | wings                   | 1.1.6             | wings-1.1.6-1.12.2.jar                                | None                                     |
	| LC    | bauble_wings            | 1.0.0             | wings-1.1.6-1.12.2.jar                                | None                                     |
	| LC    | worldedit               | 6.1.10-SNAPSHOT   | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist (1).jar | None                                     |
	| LC    | worleycaves             | 1.5.1             | Worley-Caves-Mod-1.12.2.jar                           | None                                     |
	| LC    | xaerominimap            | 20.3.0            | Xaeros_Minimap_20.3.0_Forge_1.12.jar                  | None                                     |
	| LC    | elulib                  | 0.1.12            | elulib-0.1.12.jar                                     | None                                     |
	| LC    | mysticallib             | 1.12.2-1.1.1      | mysticallib-1.12.2-1.1.1.jar                          | None                                     |
	| UD    | mowzies_wings           | 1.0.0             | wings-1.1.6-1.12.2.jar                                | None                                     |
	| UD    | mobends_wings           | 1.0.0             | wings-1.1.6-1.12.2.jar                                | None                                     |

	Loaded coremods (and transformers): 
wings (wings-1.1.6-1.12.2.jar)
  me.paulf.wings.server.asm.WingsRuntimePatcher
  me.paulf.wings.server.asm.mobends.WingsMoBendsRuntimePatcher
CreativePatchingLoader (CreativeCore_v1.9.90_mc1.12.2.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.0-pre198_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
Quark Plugin (Quark-r1.6-177.jar)
  vazkii.quark.base.asm.ClassTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.1.30.jar)
  team.chisel.ctm.client.asm.CTMTransformer
LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3.jar)
  lumien.bloodmoon.asm.ClassTransformer
CorePlugin (ForgeEndertech-1.12.2.jar)
  
FutureMC (future-mc-0.1.13.jar)
  thedarkcolour.futuremc.asm.CoreTransformer
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
llibrary (llibrary-1.7.7-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.4.jar)
  com.wynprice.secretroomsmod.core.SecretRoomsTransformer
monstersandpets (ldshadowlady-monstersandpets-1.0.1-1.12.jar)
  com.ldshadowlady.monstersandpets.asm.PlayerPassengerPatchRuntimePatcher
LoadingPlugin (Xaeros_Minimap_20.3.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
	GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.5069' Renderer: 'Intel(R) HD Graphics 4000'

**Comment by Bluberry-Kat** [comment]
Roots and Mystical World here are up-to-date.

The version of MysticalLib you have installed is 1.12.2-1,1.1, which is _over a year old._
Please [install the most recent version here](https://www.curseforge.com/minecraft/mc-mods/mysticallib/files/2912859) and re-open this issue if you're still crashing.

**Comment by anonymus411** [comment]
that worked thank you so much!
