### ISSUE TITLE
Client diconnected after using rune shear

### ISSUE THREAD

**Issue by dong031001** [EpicSquid/Roots#496]
### General Information

**Describe the bug:**
Client diconnected after using rune shear

**To Reproduce:**

1. Use runic shear on entities that drop leather in a server
2. Players in near chunks forcily disconnected.
**Expected behavior:**

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 1.6.0
- Ecc...

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge:2847
- Minecraft:1.12.2
- Modpack (if available):EnigTech 2

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**
No CR available

**Latest Log (if necessary):**
https://paste.ubuntu.com/p/ByBT6BDFvv/

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by DoomRater** [comment]
The Roots version in this modpack is 3.0.25.  Toss an issue to the modpack author that Roots has updated with some critical fixes.
