### ISSUE TITLE
Crash when reading book

### ISSUE THREAD

**Issue by VladoCC** [EpicSquid/Roots#5]
Pushed "Next" button some times and then crashed.

https://pastebin.com/BfQdCmB6

**Comment by VladoCC** [comment]
And it crashes everytime when I push "Next" on page about hammer

**Comment by EpicSquid** [comment]
I'll have a look into it for roots 3

**Comment by EpicSquid** [comment]
Will do, good spotting

**Comment by EpicSquid** [comment]
Roots 3 uses patchouli, so this is no longer an issue
