### ISSUE TITLE
Sound effects on spell casting

### ISSUE THREAD

**Issue by ScrewyMacGyver** [EpicSquid/Roots#501]
Spellcasting is a bit odd without any sounds. It would be great to have an accustical feedback on spellcasting, does not even have to be self created sound. There are many sounds already included in Minecraft Vanilla that can be used for this.

Alternately there are free databases from where you can get sound effects like this ones:

[freesound.org](https://freesound.org/search/?g=1&f=tag%3A%22fantasy%22&q=magic+spell&s=score+desc&advanced=0&page=1#sound)

[zapsaplat.com](https://www.zapsplat.com/?s=spell&post_type=music&sound-effect-category-id)

I would even offer you my help in selecting the most fitting sounds for each spell.

Anyway this feature would extremely enhence the emersion of doing magic.

**Comment by DoomRater** [comment]
Reusing sounds from Minecraft sounds great until you realize that they also inherit the subtitles.  Every time I use my freeze focus effect on something I see the words "Zombie Snuffles" on my screen.  That's a Thaumcraft thing I don't think will be fixed anytime soon.

**Comment by ScrewyMacGyver** [comment]
Makes sense... Would it be lots of work to build in a config file where I could define sounds from a seperate folder for each event?
Such as:

soundDir = ./sounds

roots.event.wildfire = sound.fire1.wav
roots.event.feylight = sound.chimes3.wav
roots.event.harvest = sound.chop2.wav
...

and so on (and sorry for not having a clue about how things are structured in this mod).
So I could build my own soundpack and send it to you as a suggestion. That would be great!

**Comment by noobanidus** [comment]
This is actually something that can be resolved through the config file as you describe -- by creating new sound events but re-using existing Minecraft sounds.

It would be great, but if you were super-interested in something like this, going through the relevant sound files and finding appropriate sounds for each spell would be even greater.

This isn't necessarily an easy task, I'll hit you up on discord about it.

**Comment by noobanidus** [comment]
Implemented as discussed although some of them might need a tweak.
