### ISSUE TITLE
Disarm spell does not have a radius

### ISSUE THREAD

**Issue by ScrewyMacGyver** [EpicSquid/Roots#502]
The disarm spell does not affect mobs in an area, just the ones you are directly touching.

If you stand in midst of skeletons and cast the spell, none of them will drop their bow.
If you directly touch one of them while casting the spell, this one drops its bow.

Same is with armed zombies as far as I found out.

I expected all the zombies an skeletons in an area of 20 blocks to drop their bows and swords.

Mod versions:
1.12.2-forge-14.23.5.2854
Roots-1.12.2-3.1.0-alpha7
mysticalworld-1.12.2-1.8.4-alpha1
mysticallib-1.12.2-1.8.0-alpha1
Patchouli-1.0-20

**Comment by Davoleo** [comment]
that's weird, the code does check for entities in a square area...
although there's a random chance for entities in that radius to drop their equipment

**Comment by noobanidus** [comment]
Oh, yeah, that should definitely be clarified: the chance to drop a weapon is the chance to drop them upon death. The disarm doesn't guarantee that the item will be dropped. (That might need to be tweaked.)
