### ISSUE TITLE
Again gathering ritual dupe items

### ISSUE THREAD

**Issue by Serega007RU** [EpicSquid/Roots#506]
All information on the video

https://drive.google.com/file/d/1brBQjTeoI8nivLmdjvIhht3H0Lnqmqy_/view?usp=sharing

**Comment by noobanidus** [comment]
Ah, thank you, I understand the issue going on here. I'm not properly modifying the existing item entities.

**Comment by noobanidus** [comment]
I believe this is a simple fix; I'll hopefully have a new version out presently.
