### ISSUE TITLE
LAN world "Druidic Arts" book reset and won't show new chapters now.

### ISSUE THREAD

**Issue by afolk2** [EpicSquid/Roots#512]
### General Information
Started up the world with my wife today and my roots guide book only shows the basic information. I tried resetting advancements and going through the chapters to no avail.

**Describe the bug:**

Druidic Arts book won't populate new chapters

**To Reproduce:**

1. Open LAN world on different client.
2. Join LAN and progress some in Roots
3. Close LAN
4. Re-open and join LAN.

**Expected behavior:**

The guide book does not reset and keeps my progress.
***

### Environment Versions

1.12.2 - 3.0.26 (From MC Eternal)

**Mystic Mods Versions**

- MysticalLib: 1.1.1
- Mystical World 1.12.2-1.8.3

**Other Versions:**
- Forge: 14.23.5.2847
- Minecraft: 1.12.2
- Modpack (if available): MC Eternal

***

**Comment by noobanidus** [comment]
Ooh, now *that* is very interesting! Thank you so much, we haven't actually been able to reproduce this yet to properly test it.

**Comment by afolk2** [comment]
Update: It seems that my wife can't populate the book either. She didn't start any of Roots until just now and I've tried picking up the entry items and reading the chapters. Crafted a stone knife and collected some oak bark as well as crafting a staff. Nothing seems to be working. I will try on a single player world and also a new LAN world as well.

Update 2: I've just realized that I'm missing a lot of chapters in the LAN world
"The Roots of Druidry" Chapter is entirely gone ( not even visible or it is one of the locked chapters)
"Spell Recipes" ( same as above )
"Tools of a Druid" ( "Component Pouch" and "Mortar and Pestle" are both missing)

This may have something to do with the problem?

**Comment by afolk2** [comment]
Further testing shows that every singleplayer world my wife makes has this issue. Is there anything I can give you that would help?

**Comment by noobanidus** [comment]
Are you using the latest version of Patchouli from CurseForge, just as a note?

Basically, what happens is that the advancements just stop registering for some reason so Patchouli doesn't recognise them as being unlocked.

**Comment by noobanidus** [comment]
Could you open your patchouli_data.json files to gist.github.com? Both yours and your wife's, if possible. These are found in the root directory of Minecraft of whatever pack you're running.

**Comment by afolk2** [comment]
We are running Patchouli 1.0-20 and the newest is 1.0-21

https://gist.github.com/afolk2/eb7d0371de67dbdaa49fb9886857bfef

https://gist.github.com/afolk2/92ed6c7e184e835230f2bfba673d0a57

I can see now that she is missing a bunch of entries that I am assuming is the problem. Do you have any idea what could have caused that?

**Comment by noobanidus** [comment]
Can you also check to see if the files are read-only or have any odd permissions that might prevent Minecraft from reading them?

I'm trying to gather as much information to give back to the Patchouli devs as possible, as this has been an ongoing annoying issue.

For the record, the only current solution is to go into the configuration for Patchouli and disable entry locking.

**Comment by afolk2** [comment]
Neither are read-only and the permissions are all allow except Special permissions

**Comment by noobanidus** [comment]
I'm waiting to hear back from Hubry on this as I believe this is still related to Patchouli.

**Comment by AtomicWaffle14** [comment]
I've also just encountered this issue, however I haven't recently opened the world to LAN. (I only did once, at the very start before starting Roots, to change a gamerule.) The book has reset and now only contains the mortar and pestle, some basic herbs, and the knife entry. All of my rituals and other things are gone. I'm running Mystical World 1.9.2,  Patchouli 1.0.21, and Roots 3.0.32 with some other mods in Minecraft 1.12.2 on Forge 14.23.5.2854.

**Comment by AtomicWaffle14** [comment]
Strangely, restarting minecraft fixed the problem for me.

Edit: ...only temporarily...

**Comment by FryoKnight** [comment]
I can confirm that this is still a issue. I have even tried restarting and checking with no avail.

Minecraft 1.12.2
Forge-14.23.5.2854
Patchouli-1.0-21
mysticallib-1.12.2-1.9.0
mysticalworld-1.12.2-1.9.2
Roots-1.12.2-3.0.32

**Comment by AtomicWaffle14** [comment]
It kept happening for me so I simply downgraded my Patchouli installation to version 1.0-19, hasn't happened since.

**Comment by Hubry** [comment]
Try this custom build of Patchouli (extract the zip, can't send jar files directly in issues):
[Patchouli-1.0-21-debug2.jar.zip](https://github.com/MysticMods/Roots/files/5358036/Patchouli-1.0-21-debug2.jar.zip)

If you still experience issues, set `B:"Lots of debug logging"` to `true` in the config, try to reproduce the thing, then run `/patchouli-dump` and post the console log.

**Comment by noobanidus** [comment]
There's now a new release of Patchouli on CurseForge that hopefully resolves this.
