### ISSUE TITLE
Runic Shears Crash

### ISSUE THREAD

**Issue by nyanlathotep** [EpicSquid/Roots#513]
### General Information

**Describe the bug:**
Shearing with runic shears causes a network exception and disconnect (#496 is not fixed).

**To Reproduce:**
Shear an entity with the runic shears and be a sufficient distance away (about 5 chunks) to be affected.
Either have two players in multiplayer or use automation (we used modular routers in part when discovering the issue in multiplayer and to reproduce it in single player).

**Expected behavior:**
Not a crash.

***

### Environment Versions

**Mystic Mods Versions**
- MysticalLib: 1.12.2-1.7.0
- Mystical World: 1.12.2-1.8.4
- Roots: 1.12.2-3.0.30

**Other Versions:**
- Modular Routers (for testing automation in single player): 1.12.2-3.3.0-33
- Forge: 14.23.5.2854
- Minecraft: 1.12.2

***

### Logging Information

**Latest Log (from singleplayer with modular routers):**
https://hastebin.com/fexupesumu.rb

**Comment by noobanidus** [comment]
Thanks for the reproduction steps! I'm not in a position to deal with it now, unfortunately, but it'll be my first priority after the weekend.

**Comment by noobanidus** [comment]
I'm unable to replicate this in the 3.1 alpha, but I think I know what the root issue might be.
