### ISSUE TITLE
Hang up those shears

### ISSUE THREAD

**Issue by Seth0067** [EpicSquid/Roots#527]
**Describe your suggestion:**
Would be great if Runic Shears could be hung up on "Cooking for Blockheads" tool racks

**Describe alternatives you've considered:**
May want to check other common gear-hanging mods like Bibliocraft as well.

Thank you for your consideration!

**Comment by DoomRater** [comment]
To hang Runic Shears on the tool rack in Bibliocraft, you can add the shears keyword in its configuration and it will automatically understand that runic shears are meant to be placed on the tool rack.  That's assuming it doesn't already rack up.

**Comment by Seth0067** [comment]
Hey there! Personally more concerned with the CfB tool rack. Thanks!

**Comment by noobanidus** [comment]
I'd also recommend asking on the Cooking for Blockheads page. I'm not actually sure what I need to do in order to make it compatible; they might also be a configuration option for it.

**Comment by Seth0067** [comment]
There is not - i've really never seen a tool not work with this (I even hang all my TC smeltery casts on them!), so i figured you might be handling there shears differently somehow in an obvious way. I'll see if I can chase up Blaytheninth, but maybe see the notes on this page? [here.](https://github.com/blay09/CookingForBlockheads)

**Comment by noobanidus** [comment]
Ah, okay, it's an IMC process. Can do then! Strangely enough they do just extend the standard shears item, so I'm not sure what it is that's preventing them from functioning. If it can be forced though, that's good enough.
