### ISSUE TITLE
[Roots 3] Crop trampling is a cancer upon minecraft

### ISSUE THREAD

**Issue by duely** [EpicSquid/Roots#53]
Given this mod is heavily crop-based, an option to disable crop trampling entirely would be nice -- disabled by default of course.

**Comment by EpicSquid** [comment]
There is a mod that already exists to solve this issue. That's a better solution then having to maintain the problem ourselves.

**Comment by duely** [comment]
"Maintain the problem ourselves": 

```java
    @SubscribeEvent
    public static void onTrampleEvent(BlockEvent.FarmlandTrampleEvent event) {
        event.setCanceled(true);
    }
```

That is literally all that is required; a boolean flag from the config would have to be added, of course, but it's not that huge of a deal and adding an extra mod for it is frustrating -- especially when those extra mods require configuration to define what TYPE of trampling is allowed (and the one I tried defaulted to "feather fall doesns't trample but everything else does).

Currently I'm running a custom mod in all of my packs to do it.

If you still don't want to, that's fine, but it's not exactly something difficult to maintain.
