### ISSUE TITLE
Animal Harvest want to work more

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#533]
### General Information

**Describe the bug:**
Animal Harvest work some time after u stop ritual

**To Reproduce:**
1.Start Animal Harvest
2.Stop Animal Harvest with bucket of water
3.Just look on free animal harvesting

**Expected behavior:**
I think it's need to end up.

***

### Environment Versions
Roots 1.12.2-3.0.31

**Mystic Mods Versions**

- Mystical Lib:version 1.9.0
-Mystical World:version 1.9.1

**Comment by noobanidus** [comment]
As this pre-dates the alpha I'm closing it. Please re-open with a new alpha issue if it's replicatable in 3.1 alpha.
