### ISSUE TITLE
[1.12.2] Crasher because of conflict between Roots and Bamboozled?

### ISSUE THREAD

**Issue by gchpaco** [EpicSquid/Roots#537]
### General Information

**Describe the bug:**

Created a new world, opened a starter chest, world crashed with attached crash report.

**To Reproduce:**

Not really sure, honestly.  I think it was bamboozled bamboo shoots trying to grow.

**Expected behavior:**
Not crashing.

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 1.9.0
- Roots: 3.0.32

**Other Versions:**
- Conflicting mod (if regarding mod integration): Bamboozled 1.1.0
- Forge: 14.23.5.2854
- Minecraft: 1.12.2
- Modpack (if available): private

***

### Logging Information
**Crash Report (if available):**
[crash-2020-09-17_17.53.16-server.txt](https://github.com/MysticMods/Roots/files/5242353/crash-2020-09-17_17.53.16-server.txt)

**Comment by noobanidus** [comment]
This is on Bamboozled to fix, I'm afraid. They know about the issue, they know exactly how to fix it and have known for multiple months.
