### ISSUE TITLE
Component pouch deletes herbs when stacking

### ISSUE THREAD

**Issue by sekelsta** [EpicSquid/Roots#538]
### General Information

**Describe the bug:**
When there is a partial stack of an herb in the herb part of the component pouch, adding more herbs to that stack deletes the new herbs so that the stack is the same size as before. The only way to refill the stack is to move it to a different part of the inventory first.

**To Reproduce:**
1. Place a stack of two wildroots (or other herb) in the herb section of the component pouch
2. Add another wildroot to the stack to make it three
3. Close the inventory
4. Reopen the pouch, there are only two wildroots

**Expected behavior:**
Adding more herbs to a stack should increase the stack count

***

### Environment Versions

**Mystic Mods Versions**
- MysticalLib: 1.9.0
- Mystical world: 1.9.2
- Roots: 3.0.32

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 14.23.5.2847
- Minecraft: 1.12.2
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by noobanidus** [comment]
Goddamn, this bug is insufferable sometimes. I think it has something to do with the interface increasing the stack size and decreasing what you have, but then not actually telling the item that the contents have changed so it's never saved... I'll investigate further, thanks.

**Comment by SonicX8000** [comment]
I wonder if this is related to this bug?
https://github.com/MysticMods/Roots/issues/448

If so, the same thing occurs when you increase the item stack for an item. It deletes the new stack with the stack that it had before, although... if you update two item stacks... only stack that was updated last gets reverted back.

Say you have a stack of 16 Cobble, 16 Sand, and 16 Pereskia inside the pouch and you add in 8 items for the Cobble, Sand and Pereskia in that order and you close the pouch. When you reopen it... you will have 24 Cobble, 24 Sand but still 16 Perskia meaning 8 of them went missing as it was the last one to be stored when the pouch was closed.

**Comment by noobanidus** [comment]
Sorry, I've been super-busy, I think this has actually been fixed in the 3.1 branch. I forget if I ported i t back to the 3.0 branch.

**Comment by SonicX8000** [comment]
3.0.32 still has the deletion bug. Both for Herb & Item stacks.

**Comment by noobanidus** [comment]
What I meant is that I think this may have been fixed in the ***3.1*** branch which is unreleased. I'm not sure if I backported it and, thus, the fix doesn't work and needs to be looked at further.

**Comment by noobanidus** [comment]
Yeah, unfortunately this hasn't been merged back into 3.0 branch. I'll see what I can do, but as I'm trying to complete the 3.1 release it might need to remain a known bug until that comes out.

**Comment by noobanidus** [comment]
As the 3.0 branch is closed for now, given that 3.1 will be out soon, I'm closing this issue as I know it's fixed in 3.1.
