### ISSUE TITLE
Automating Cooking "Ritual" Deletes raw food from chest

### ISSUE THREAD

**Issue by AtomicWaffle14** [EpicSquid/Roots#540]
### General Information

**Describe the bug:**
Attempting to automate cooking "ritual" will result in 5 items being cooked, and any of that item in the chest being deleted with no cooked equivalent being returned. You can even have the chest open while it deletes the items.

**To Reproduce:**
1. Place a chest under the Pyre
2. Set up a cooking "ritual", can be any raw food
3. Place more of the raw food in the chest under the pyre. Let's say a stack
4. Start the ritual by lighting the pyre

**Expected behavior:**
I would expect the Pyre to cook 5 of the item, then take 5 more from the chest and start again.

***

### Environment Versions
Java 8 Update 251

**Mystic Mods Versions**
- MysticalLib: mysticallib-1.12.2-1.9.0
- MysticalMechanics: 0.18
- MysticalWorld: 1.12.2-1.9.2
- Roots: 1.12.2-3.0.32

**Other Versions:**
- Forge: 14.23.5.2854
- Minecraft: 1.12.2
- Modpack (if available): custom

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by AtomicWaffle14** [comment]
This seems to happen with all Pyre Crafting rituals.

**Comment by noobanidus** [comment]
@AtomicWaffle14 Thanks! Unfortunately, the 3.0 -> 3.1 switch has changed the way the ritual pyre functions. I don't think this is something I'll be looking into for the 3.0 branch as I'm focused on getting the 3.1 release out.

If you are interested or get a chance, you can [check out the new alpha on the Mystic Modding Discord](https://discord.gg/hKjkMbf) by checking the `#testing-admin` channel. You can also select a role to be pinged for future alpha updates in `#testing-role`. I recently did a [preview post](https://www.patreon.com/posts/roots-3-1-alpha-42978578) with images of the new features/effects that were coming for 3.1 on my patreon (post visible to all though).

**Comment by noobanidus** [comment]
I'm closing this for now in favor of the 3.1 alpha release, as the 3.0 code branch has been retired.
