### ISSUE TITLE
Documentation needs to be completed

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#542]
![2020-10-15_09 27 56](https://user-images.githubusercontent.com/53404970/96085073-ebf6cc00-0ec8-11eb-8109-2510beef2e2d.png)
![2020-10-15_08 53 22](https://user-images.githubusercontent.com/53404970/96084422-b7cedb80-0ec7-11eb-98fd-2856fcd7ec98.png)
![2020-10-15_08 53 24](https://user-images.githubusercontent.com/53404970/96084426-b9000880-0ec7-11eb-84a2-edc98cf46a10.png)

**Comment by noobanidus** [comment]
Yes, book is currently non-functional.

**Comment by noobanidus** [comment]
Update: book is now in template form.

**Comment by noobanidus** [comment]
Cross-reference #469.

**Comment by noobanidus** [comment]
Close in favor of #678.
