### ISSUE TITLE
[alpha8] Empty spell library results in library container crash

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#544]
**To Reproduce:**
1.Just click on emtpy icon in your library
2.LAAAGS
3.CRASH

Crash report:
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 10/15/20 1:38 PM
Description: Updating screen events

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:120)
	at epicsquid.roots.container.ContainerLibrary.func_184996_a(ContainerLibrary.java:275)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at net.minecraft.inventory.Container.func_75139_a(Container.java:120)
	at epicsquid.roots.container.ContainerLibrary.func_184996_a(ContainerLibrary.java:275)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:566)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:392)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: epicsquid.roots.client.gui.GuiLibrary

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DinarNaMamky'/28, l='MpServer', x=-947.37, y=4.00, z=393.21]]
	Chunk stats: MultiplayerChunkCache: 361, 361
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-985,4,435), Chunk: (at 7,0,3 in -62,27; contains blocks -992,0,432 to -977,255,447), Region: (-2,0; contains chunks -64,0 to -33,31, blocks -1024,0,0 to -513,255,511)
	Level time: 7064 game time, 7064 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 88 total; [EntitySheep['Sheep'/69633, l='MpServer', x=-884.50, y=4.00, z=443.50], EntityVillager['Villager'/0, l='MpServer', x=-894.50, y=5.00, z=320.50], EntitySheep['Sheep'/69632, l='MpServer', x=-882.52, y=4.00, z=434.65], EntitySlime['Slime'/794893, l='MpServer', x=-941.40, y=4.53, z=426.39], EntityVillager['Villager'/1, l='MpServer', x=-891.50, y=5.00, z=328.50], EntityItem['item.item.wheat'/711944, l='MpServer', x=-890.03, y=4.94, z=391.69], EntityVillager['Villager'/2, l='MpServer', x=-897.30, y=4.00, z=320.24], EntityPig['Pig'/69634, l='MpServer', x=-882.50, y=4.00, z=442.50], EntityVillager['Villager'/3, l='MpServer', x=-891.50, y=5.00, z=332.50], EntityItem['item.item.seeds'/711945, l='MpServer', x=-888.56, y=5.00, z=392.11], EntityVillager['Villager'/4, l='MpServer', x=-891.50, y=5.00, z=343.50], EntityVillager['Villager'/5, l='MpServer', x=-891.50, y=5.00, z=344.50], EntityVillager['Villager'/6, l='MpServer', x=-888.50, y=5.00, z=355.50], EntityHorse['Horse'/69639, l='MpServer', x=-999.29, y=4.00, z=412.26], EntitySlime['Slime'/1181204, l='MpServer', x=-947.32, y=4.00, z=343.07], EntityVillager['Villager'/7, l='MpServer', x=-881.50, y=5.00, z=320.50], EntityVillager['Villager'/8, l='MpServer', x=-883.37, y=5.00, z=321.51], EntityVillager['Villager'/9, l='MpServer', x=-881.50, y=5.00, z=355.50], EntityChicken['Chicken'/69643, l='MpServer', x=-986.69, y=4.00, z=413.33], EntitySlime['Slime'/886023, l='MpServer', x=-1002.76, y=4.14, z=386.25], EntitySlime['Slime'/1250073, l='MpServer', x=-883.67, y=4.00, z=453.96], EntityHorse['Horse'/69642, l='MpServer', x=-998.05, y=4.00, z=411.17], EntityChicken['Chicken'/69645, l='MpServer', x=-933.80, y=4.00, z=471.81], EntityCow['Cow'/69644, l='MpServer', x=-992.16, y=4.00, z=404.24], EntityChicken['Chicken'/69647, l='MpServer', x=-938.12, y=4.00, z=467.21], EntityChicken['Chicken'/69646, l='MpServer', x=-933.67, y=4.00, z=467.97], EntityHorse['Horse'/69649, l='MpServer', x=-928.72, y=4.00, z=470.40], EntityHorse['Horse'/69648, l='MpServer', x=-921.10, y=4.00, z=465.11], EntityCow['Cow'/69651, l='MpServer', x=-948.85, y=4.00, z=461.16], EntitySlime['Slime'/1175811, l='MpServer', x=-939.89, y=4.00, z=332.33], EntityChicken['Chicken'/69650, l='MpServer', x=-933.57, y=4.00, z=466.84], EntityDeer['Deer'/69653, l='MpServer', x=-934.89, y=4.00, z=451.78], EntityDeer['Deer'/69654, l='MpServer', x=-962.66, y=4.00, z=457.14], EntitySlime['Slime'/1185586, l='MpServer', x=-990.76, y=4.00, z=418.03], EntityItem['item.item.seeds'/318246, l='MpServer', x=-890.60, y=4.94, z=395.50], EntityItem['item.item.carrots'/967724, l='MpServer', x=-892.57, y=5.00, z=392.09], EntitySlime['Slime'/1185585, l='MpServer', x=-1023.37, y=4.00, z=370.78], EntityChicken['Chicken'/69669, l='MpServer', x=-928.50, y=4.00, z=435.50], EntityItem['item.item.carrots'/493091, l='MpServer', x=-893.37, y=4.94, z=394.91], EntityChicken['Chicken'/69668, l='MpServer', x=-927.51, y=4.00, z=441.79], EntitySlime['Slime'/920107, l='MpServer', x=-1023.98, y=4.00, z=415.12], EntityChicken['Chicken'/69671, l='MpServer', x=-925.34, y=4.00, z=432.53], EntityChicken['Chicken'/69670, l='MpServer', x=-925.76, y=4.00, z=426.73], EntityItem['item.item.seeds'/850468, l='MpServer', x=-890.58, y=5.00, z=393.85], EntitySlime['Slime'/1204799, l='MpServer', x=-1013.35, y=4.00, z=417.56], EntityItem['item.item.wheat'/850467, l='MpServer', x=-890.40, y=4.94, z=394.13], EntitySlime['Slime'/877375, l='MpServer', x=-943.93, y=5.17, z=396.32], EntitySlime['Slime'/1153114, l='MpServer', x=-909.08, y=4.00, z=431.01], EntitySlime['Slime'/781383, l='MpServer', x=-909.13, y=4.00, z=355.39], EntitySlime['Slime'/1210718, l='MpServer', x=-973.94, y=4.08, z=382.56], EntitySlime['Slime'/711003, l='MpServer', x=-955.21, y=4.00, z=404.55], EntitySlime['Slime'/1271118, l='MpServer', x=-936.04, y=4.00, z=336.34], EntitySlime['Slime'/1108849, l='MpServer', x=-890.85, y=5.00, z=396.37], EntitySlime['Slime'/1134963, l='MpServer', x=-907.84, y=4.00, z=345.28], EntityPlayerSP['DinarNaMamky'/28, l='MpServer', x=-947.37, y=4.00, z=393.21], EntitySlime['Slime'/1280124, l='MpServer', x=-884.65, y=4.00, z=403.16], EntitySlime['Slime'/1204065, l='MpServer', x=-935.02, y=4.00, z=326.42], EntitySlime['Slime'/857461, l='MpServer', x=-935.97, y=4.95, z=389.53], EntitySlime['Slime'/1164648, l='MpServer', x=-923.69, y=4.00, z=334.60], EntityItem['item.item.seeds'/1299091, l='MpServer', x=-889.14, y=5.00, z=396.75], EntitySlime['Slime'/466562, l='MpServer', x=-991.44, y=4.14, z=428.27], EntitySlime['Slime'/1108886, l='MpServer', x=-945.38, y=4.00, z=436.55], EntitySlime['Slime'/1027739, l='MpServer', x=-919.33, y=4.00, z=326.57], EntitySlime['Slime'/954011, l='MpServer', x=-877.36, y=5.08, z=404.37], EntityItem['item.item.potato'/975000, l='MpServer', x=-893.46, y=4.94, z=378.74], EntityItem['item.item.seeds'/481178, l='MpServer', x=-890.22, y=5.00, z=389.68], EntitySlime['Slime'/774824, l='MpServer', x=-927.89, y=4.67, z=395.06], EntitySlime['Slime'/1259958, l='MpServer', x=-892.16, y=4.00, z=415.74], EntitySlime['Slime'/1258938, l='MpServer', x=-1019.08, y=4.92, z=421.73], EntityItem['item.item.carrots'/391848, l='MpServer', x=-885.65, y=4.94, z=363.82], EntityItem['item.item.carrots'/305341, l='MpServer', x=-894.21, y=5.00, z=390.87], EntitySlime['Slime'/810184, l='MpServer', x=-945.30, y=4.00, z=373.41], EntitySlime['Slime'/1237717, l='MpServer', x=-938.43, y=4.92, z=323.79], EntitySlime['Slime'/1262804, l='MpServer', x=-959.38, y=5.10, z=419.25], EntitySlime['Slime'/1074649, l='MpServer', x=-924.82, y=4.33, z=434.09], EntityItem['item.item.carrots'/398540, l='MpServer', x=-886.88, y=5.00, z=367.66], EntityItem['item.item.potato'/1007838, l='MpServer', x=-892.71, y=4.94, z=384.53], EntitySlime['Slime'/1051078, l='MpServer', x=-949.44, y=5.02, z=454.06], EntityItem['item.item.seeds'/363736, l='MpServer', x=-884.39, y=5.00, z=375.03], EntitySlime['Slime'/449004, l='MpServer', x=-933.43, y=4.00, z=423.11], EntitySlime['Slime'/1164283, l='MpServer', x=-1022.49, y=4.00, z=427.32], EntityItem['item.item.carrots'/844000, l='MpServer', x=-891.60, y=4.00, z=392.26], EntityChicken['Chicken'/69615, l='MpServer', x=-921.86, y=4.00, z=388.93], EntitySheep['Sheep'/69617, l='MpServer', x=-934.25, y=4.00, z=408.22], EntitySheep['Sheep'/69616, l='MpServer', x=-912.81, y=4.00, z=408.54], EntitySheep['Sheep'/69618, l='MpServer', x=-929.56, y=4.00, z=412.32], EntitySlime['Slime'/1232366, l='MpServer', x=-929.06, y=4.00, z=317.12], EntitySheep['Sheep'/69631, l='MpServer', x=-884.50, y=4.00, z=440.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 371336352 bytes (354 MB) / 1040187392 bytes (992 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 9 mods loaded, 9 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version              | Source                                | Signature                                |
	|:------ |:------------- |:-------------------- |:------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft     | 1.12.2               | minecraft.jar                         | None                                     |
	| LCHIJA | mcp           | 9.42                 | minecraft.jar                         | None                                     |
	| LCHIJA | FML           | 8.0.99.99            | forge-1.12.2-14.23.5.2854.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge         | 14.23.5.2854         | forge-1.12.2-14.23.5.2854.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | jei           | 4.16.1.302           | jei_1.12.2-4.16.1.302.jar             | None                                     |
	| LCHIJA | roots         | 1.12.2-3.1.0-alpha8  | Roots-1.12.2-3.1.0-alpha8.jar         | None                                     |
	| LCHIJA | mysticalworld | 1.12.2-1.9.3-alpha1  | mysticalworld-1.12.2-1.9.3-alpha1.jar | None                                     |
	| LCHIJA | patchouli     | 1.0-21               | Patchouli-1.0-21-debug3.jar           | None                                     |
	| LCHIJA | mysticallib   | 1.12.2-1.10.0-alpha1 | mysticallib-1.12.2-1.10.0-alpha1.jar  | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GT 540M/PCIe/SSE2'
	Patchouli open book context: n/a
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GT 540M/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Pentium(R) CPU B950 @ 2.10GHz

**Comment by noobanidus** [comment]
Hm, that's a strange one. It might be because you have no spells in your library yet. I hadn't really tested that.
