### ISSUE TITLE
[alpha8] Ritual doesn't re-fire until it loads from a chest

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#555]
### General Information

**Describe the bug:**
The ritual absorbs items twice from chest.

**Comment by noobanidus** [comment]
This might be a bug with a specific ritual. Which one were you using?

**Comment by noobanidus** [comment]
Did we determine what was happening here?

**Comment by guide-for-you** [comment]
Yeah,consume items double from a chest

**Comment by noobanidus** [comment]
Do you remember which ritual it was? I wasn't able to duplicate this.

In theory, if there's no ingredients in the pyre, it'll pull a set in, then consume it, then pull another set in.

**Comment by guide-for-you** [comment]
Yes,this is how it works.But with this bug,it consume items in Pyre,then consume items from chest and only then continue working.

**Comment by noobanidus** [comment]
I can't seem to replicate this, sorry.

**Comment by noobanidus** [comment]
Close in favor of #629.
