### ISSUE TITLE
[alpha9] Elemental soil strange...

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#559]
### General Information

**Describe the bug:**
If you trying to replace farmland with elemental soil in creative,block just disappears from your hand and you can place him without having him.
![2020-10-19_13 06 03](https://user-images.githubusercontent.com/53404970/96431958-ee309180-120c-11eb-9e7b-977252f5082e.png)
**To Reproduce:**
1. Take your elemental soil.
2. Try to replace farmland with elemental soil.
3. Watch Harry!You can place elemental soil without having this

**Comment by guide-for-you** [comment]
I think it's because he become invisible in this slot if you did that

**Comment by Davoleo** [comment]
sounds like client/server desync

**Comment by noobanidus** [comment]
I think I may have fixed this but I'm not certain. The next alpha release will hopefully fix it.

**Comment by noobanidus** [comment]
@guide-for-you can you clarify if this is still happening for you or not?

**Comment by guide-for-you** [comment]
Oh,sorry,I forgot to close this.
