### ISSUE TITLE
[alpha9] Rendering bug in Imposer interface

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#561]
![2020-10-19_12 45 05](https://user-images.githubusercontent.com/53404970/96432800-b4ac5600-120d-11eb-803e-feff0a66b469.png)

**Comment by noobanidus** [comment]
I've done some work with this but I can't replicate it in dev so I'm not sure if it's fixed or not.

**Comment by guide-for-you** [comment]
I think it's functional normally
