### ISSUE TITLE
[alpha9] It's giant lags after pressing "k"(open library)

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#563]
**Latest Log (if necessary):**
[debug.log](https://github.com/MysticMods/Roots/files/5401237/debug.log)
[latest.log](https://github.com/MysticMods/Roots/files/5401240/latest.log)

**Comment by noobanidus** [comment]
That's interesting, going over the logs now. There shouldn't be a huge amount of data that's transferred, but there might be a bug somewhere.

**Comment by noobanidus** [comment]
The main error had to do with the rampant life infusion FX not being properly registered, which I've adjusted. We'll revisit this after the next alpha to see if that fixes it.

**Comment by guide-for-you** [comment]
It seems that it doesn't cause lags anymore
