### ISSUE TITLE
[alpha9] Speed modifiers do not decrease interval of Growth Infusion

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#565]
### General Information

**Describe the bug:**
Growth with those modifires,works really slow:
![2020-10-19_13 59 40](https://user-images.githubusercontent.com/53404970/96442437-cd1f6f00-1213-11eb-8843-77a72fb8278c.png)

**Expected behavior:**
I think that with those modifires he need to be REALLY FAST.

**Comment by noobanidus** [comment]
Hm, it's possible that growth infusion's interval isn't being properly modified by the speedy upgrades. They should at least decrease the spacing between ticks by 15%...

**Comment by noobanidus** [comment]
See #590
