### ISSUE TITLE
[alpha9] Silk Touch Modifier doesn't allow Shatter to break anything other than leaves

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#568]
### General Information

**Describe the bug:**
I can break leaves and get leaves with Shatter's Silk Touch modifier, but it fails to break anything else- even tall grass.  Tested in creative mode only.

**Comment by noobanidus** [comment]
Yup. Was checking for empty rather than not empty.

**Comment by noobanidus** [comment]
Issues with grass too though.

**Comment by noobanidus** [comment]
Grass fixed!
