### ISSUE TITLE
Modifiers bugs

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#572]
### All modifiers with no bug will not be included in the list!
- [x] **Geas**

- [x] Animal Servants:

Animal don't want to fight.

- [x] Weakened Response:

Doesn't give weakness to creatures.

- [x] Inferno:

Doesn't fires up any creature.
 

- [x] Waterfall:

Doesn't deal any damage to mobs.

- [x] Avalance:

Doesn't deal any damage to mobs.

- [x] Unholy Command:

If use spell with this modifier on undeads nearby with enemies,3 new mobs will appear from mob on which you used this spell.

- [x] Targeting Geas:

Don't work because when you use it,previous mob still have this effect.

- [x] **Rose's Thorns**

All modifiers work.

- [x] **Aqua Bubble**

- [x] Duumvirate:

I can't check this now

- [x] Faithful Shearing:

![Aqua Bubble](https://user-images.githubusercontent.com/53404970/96490476-89dff300-1249-11eb-804b-88b7dcda24a9.png)
It's after using spell with modfier [Faithful Shearing]
Work,but doesn't visualized

- [x] **Disarm**

- [x] Cows with Guns:

Doesn't work.Believe me

- [x] **Sanctuary**

- [x] Reject Nature:

Somehow,every mob is now peaseful(every creature can go through Sanctuary

- [x] Radius:

Without modifier:
![Радиус 1](https://user-images.githubusercontent.com/53404970/96491576-19d26c80-124b-11eb-8fde-a90d5ad7dd3b.png)
With modifier:
![Радиус 2](https://user-images.githubusercontent.com/53404970/96491608-248d0180-124b-11eb-8a67-b63dd3446078.png)
Not in length but in width

- [x] **Time Stop**

All modifiers work.

- [x] **Growth Infusion**

- [x] Incubation:

Doesn't work in range(on single directed target).

- [x] **Sky Soarer**

All modifiers work

- [x] **Saturate**

All modifiers works

- [x] **Wildfire**

- [x] Pyroclastic Cloud:

Leaves patches of fire only if you attack at low distance

- [x] Post-mortem Growth:

This is don't work.I burned out 40 villagers to test this.

- [x] **Nature's Scythe**

All modifiers work.

- [x] **Shatter**

All modifiers work

- [x] **Acid Cloud**

- [x] Cloud of Rocks:

Errr,this thing increase damage or what?

- [x] **Radiance**

All modiers work

- [x] **Fey Light**

All modifiers work.

- [x] **Desaturate**

- [x] Excess Purification:

1)Err...
![2020-10-26_20 01 23](https://user-images.githubusercontent.com/53404970/97210358-26644100-17c6-11eb-90cb-0cb835d13c71.png)

- [x] Excess Levitation:

Don't give you levitation.

- [x] **Life Drain**

All modifiers work.

- [x] **Extension**

All modifiers work.

- [x] **Augment**

All modifiers work.

- [x] **Storm Cloud**

All modfiers work.

- [x] **Dandelion Winds**

- [x] Fire Extinguisher:

Errrrrr....
![2020-10-26_20 29 37](https://user-images.githubusercontent.com/53404970/97213778-c1f7b080-17ca-11eb-84a8-ffca721dcb9a.png)

- [x] **Harvest**
All modfires work

- [x] **Petal Shell**

- [x] Mossy Leaves:

It not green actually
![2020-10-21_16 03 54](https://user-images.githubusercontent.com/53404970/96723465-44413880-13b7-11eb-97b3-47443050e5e2.png)

- [x] Poison:

Doesn't give poison to who attack you

- [x] Peaceful Dance:

Doesn't visualize petals on your pet
![2020-10-21_16 10 24](https://user-images.githubusercontent.com/53404970/96724228-448e0380-13b8-11eb-859c-80759919ae42.png)

- [x] **Chrysopoeia**

Repetition:

???

- [x] Any modifire:

After you activate any modifire,spell consume items,but doesn't transmutate them.
- - -

**Comment by guide-for-you** [comment]
Sorry if it's don't enough I will add all you want me to add.

**Comment by noobanidus** [comment]
I will say that the Repetition modifier for Chrysopoeia isn't implemented yet and I'm debating changing it.

**Comment by noobanidus** [comment]
I feel like I might change Animal Servants to do something else, this didn't function as well as I'd hoped.

**Comment by noobanidus** [comment]
Second Wind isn't intended to give you water breathing.

**Comment by guide-for-you** [comment]
> Second Wind isn't intended to give you water breathing.

Ok,sorry

**Comment by noobanidus** [comment]
Re: fortune on Nature's Scythe, it's set to 2 as in Fortune II. I think this is a fair value although I may look at ways of extending it.

**Comment by noobanidus** [comment]
Pyroclastic Cloud *sort* of work.

**Comment by noobanidus** [comment]
Incubation is an inaccurate description.

Also it needs to render particles.

EDIT: It should be changed to an aoe, targetting is too annoying.

**Comment by noobanidus** [comment]
Gonna remove Cloud of Rocks.

**Comment by noobanidus** [comment]
Incubation changed to an AoE (one target at a time), I might change the default growth times though.

**Comment by noobanidus** [comment]
Made the green fire use Terra Moss instead (more sensible), made Spirit Herb a now modifier called Duality: shoots two flames (but more expensive).

**Comment by noobanidus** [comment]
Cloud of Rocks is now a slow effect.

**Comment by noobanidus** [comment]
I'm going to be re-doing the Desaturate modifiers. Instead it will be a percentage of the healing done will be used to calculate the duration of a potion effect.

**Comment by noobanidus** [comment]
I think undead might be immune to poison... or maybe just skeletons. Either way, it works on Endermen now.

**Comment by noobanidus** [comment]
Duumvirate is a now a modifier that amplifies the effects of aqua bubble.

**Comment by noobanidus** [comment]
I'm closing this out now, thank you so much for the valuable feedback. Please open a new topic for any other issues in the next alpha just to keep them segregated properly.
