### ISSUE TITLE
[Roots 3] Reuse previous pyre recipe has problems with duplicates

### ISSUE THREAD

**Issue by duely** [EpicSquid/Roots#58]
I.e., the living pickaxe recipe is 2 oak bark, 1 wildroot, 1 gold, 1 wood pickaxe.

I performed the initial pyre spell, and then shift-right-clicked to have it refill 1 bark, 1 gold, 1 wildroot, 1 pickaxe. I'm not sure why the second bark got missed but I haven't looked into the implemetnation.

**Comment by Martacus** [comment]
I know why

**Comment by duely** [comment]
Fixed
