### ISSUE TITLE
Time Stop bug

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#587]
### General Information

**Describe the bug:**
After first hit in stopped time,you cannot hit creatures in stopped time until it ends.

**To Reproduce:**
1. Stop Time
2. Hit creature
3. You cannot hit it anymore until spell ends

**Comment by noobanidus** [comment]
I'll look into it, but given how it functions I believe this is actually intended. They literally stop ticking for the duration of the potion (except for the potion itself).

**Comment by noobanidus** [comment]
I'm pretty sure this is the intended behaviour.
