### ISSUE TITLE
[alpha11] Partricles broken

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#597]
**Describe the bug:**
Imbuer doesn't emit fire when you imbue staff with spell dust.
![2020-10-25_10 37 03](https://user-images.githubusercontent.com/53404970/97102548-11e15500-16af-11eb-913b-af9dc27a50f8.png)

**Comment by noobanidus** [comment]
Yeah, I noticed this in my stream. Particles are currently broken in this release.
