### ISSUE TITLE
[alpha11] JEI doesn't support 3 costs

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#599]
![2020-10-25_12 02 19](https://user-images.githubusercontent.com/53404970/97104314-9e921000-16bb-11eb-835b-f1f69df6e80f.png)
![2020-10-25_12 11 16](https://user-images.githubusercontent.com/53404970/97104317-a18d0080-16bb-11eb-818c-ea9d72a6a0a5.png)
![2020-10-25_12 11 34](https://user-images.githubusercontent.com/53404970/97104318-a356c400-16bb-11eb-9c2a-9770eaab8eca.png)

**Comment by noobanidus** [comment]
That's weird, also I forgot JEI doesn't support default triple costs.
