### ISSUE TITLE
[alpha11] Sanctuary,what duh heck?

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#600]
[debug.log](https://github.com/MysticMods/Roots/files/5434593/debug.log)
[latest.log](https://github.com/MysticMods/Roots/files/5434594/latest.log)
![2020-10-25_13 01 06](https://user-images.githubusercontent.com/53404970/97105377-ed8f7380-16c2-11eb-9734-b3ba21fdea7e.png)

**Comment by noobanidus** [comment]
Not fixed necessarily but the next release will have better handling of errors in packets.
