### ISSUE TITLE
[alpha12] Runestone and Runed Obsidian walls texture bug

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#614]
![2020-11-05_18 41 10](https://user-images.githubusercontent.com/53404970/98270006-19e6a200-1f97-11eb-96ce-e1b04b44b6e7.png)
![2020-11-05_18 41 12](https://user-images.githubusercontent.com/53404970/98270055-2965eb00-1f97-11eb-8b51-6ebbca35a477.png)
![2020-11-05_18 41 14](https://user-images.githubusercontent.com/53404970/98270068-2c60db80-1f97-11eb-887f-b1d7773024c3.png)
![2020-11-05_18 43 30](https://user-images.githubusercontent.com/53404970/98270074-2d920880-1f97-11eb-94c1-2ec708261807.png)
![2020-11-05_18 43 32](https://user-images.githubusercontent.com/53404970/98270078-2f5bcc00-1f97-11eb-9e42-46668bb8321a.png)
![2020-11-05_18 43 33](https://user-images.githubusercontent.com/53404970/98270080-308cf900-1f97-11eb-9112-0f15a8f5c44d.png)

**Comment by noobanidus** [comment]
That's interesting, I wonder if it's a persistent issue regardless.
