### ISSUE TITLE
[alpha12] Sanctuary crash

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#615]
---- Minecraft Crash Report ----
// There are four lights!

Time: 11/5/20 7:59 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at epicsquid.roots.network.fx.MessageSanctuaryRingFX$MessageHolder.handleMessage(MessageSanctuaryRingFX.java:58)
	at epicsquid.roots.network.fx.MessageSanctuaryRingFX$MessageHolder.handleMessage(MessageSanctuaryRingFX.java:52)
	at epicsquid.roots.network.MessageHandler.handleMessageInternal(MessageHandler.java:16)
	at epicsquid.roots.network.ClientMessageHandler.lambda$onMessage$0(ClientMessageHandler.java:10)
	at epicsquid.roots.network.ClientMessageHandler$$Lambda$590/1371693308.run(Unknown Source)
	at epicsquid.roots.event.ClientTickHandler.clientTick(ClientTickHandler.java:32)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_50_ClientTickHandler_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1911)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at epicsquid.roots.network.fx.MessageSanctuaryRingFX$MessageHolder.handleMessage(MessageSanctuaryRingFX.java:58)
	at epicsquid.roots.network.fx.MessageSanctuaryRingFX$MessageHolder.handleMessage(MessageSanctuaryRingFX.java:52)
	at epicsquid.roots.network.MessageHandler.handleMessageInternal(MessageHandler.java:16)
	at epicsquid.roots.network.ClientMessageHandler.lambda$onMessage$0(ClientMessageHandler.java:10)
	at epicsquid.roots.network.ClientMessageHandler$$Lambda$590/1371693308.run(Unknown Source)
	at epicsquid.roots.event.ClientTickHandler.clientTick(ClientTickHandler.java:32)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_50_ClientTickHandler_clientTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPostClientTick(FMLCommonHandler.java:349)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['DinarNaMamky'/740, l='MpServer', x=19.36, y=66.00, z=99.16]]
	Chunk stats: MultiplayerChunkCache: 361, 361
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (39,64,108), Chunk: (at 7,4,12 in 2,6; contains blocks 32,0,96 to 47,255,111), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 73160 game time, 6685 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 73 total; [EntityZombie['Zombie'/109573, l='MpServer', x=55.50, y=30.00, z=28.50], EntityCreeper['Creeper'/109579, l='MpServer', x=-6.50, y=21.00, z=83.50], EntityCreeper['Creeper'/111642, l='MpServer', x=-49.50, y=25.00, z=77.50], EntitySkeleton['Skeleton'/28703, l='MpServer', x=16.50, y=13.00, z=-70.50], EntityBat['Bat'/110634, l='MpServer', x=-51.07, y=26.49, z=78.01], EntityZombie['Zombie'/106548, l='MpServer', x=78.50, y=75.00, z=90.50], EntityRabbit['Rabbit'/58, l='MpServer', x=-60.51, y=69.00, z=58.56], EntityRabbit['Rabbit'/61, l='MpServer', x=-45.50, y=69.00, z=151.50], EntityRabbit['Rabbit'/62, l='MpServer', x=-47.60, y=69.00, z=151.40], EntityRabbit['Rabbit'/63, l='MpServer', x=-45.19, y=69.00, z=148.40], EntityBat['Bat'/109639, l='MpServer', x=-4.93, y=30.08, z=45.56], EntityPig['Pig'/72, l='MpServer', x=-57.29, y=70.00, z=25.80], EntityRabbit['Rabbit'/73, l='MpServer', x=-27.17, y=70.00, z=82.74], EntityRabbit['Rabbit'/74, l='MpServer', x=-43.20, y=69.00, z=103.22], EntityPig['Pig'/79, l='MpServer', x=14.20, y=68.00, z=30.17], EntityPig['Pig'/81, l='MpServer', x=-0.79, y=68.00, z=23.71], EntityRabbit['Rabbit'/92, l='MpServer', x=62.28, y=63.00, z=160.36], EntityRabbit['Rabbit'/93, l='MpServer', x=56.16, y=63.00, z=162.54], EntityPig['Pig'/94, l='MpServer', x=68.25, y=66.00, z=27.71], EntityPig['Pig'/95, l='MpServer', x=67.50, y=67.00, z=30.50], EntityPig['Pig'/96, l='MpServer', x=69.27, y=66.00, z=28.56], EntityPig['Pig'/97, l='MpServer', x=62.50, y=67.00, z=27.50], EntityPig['Pig'/98, l='MpServer', x=61.50, y=64.00, z=171.50], EntityPig['Pig'/99, l='MpServer', x=60.60, y=64.00, z=164.79], EntityPig['Pig'/100, l='MpServer', x=61.68, y=64.00, z=173.43], EntityPig['Pig'/101, l='MpServer', x=61.49, y=64.00, z=172.40], EntityRabbit['Rabbit'/102, l='MpServer', x=58.71, y=64.00, z=171.74], EntityRabbit['Rabbit'/106, l='MpServer', x=70.46, y=64.00, z=178.30], EntityChicken['Chicken'/108, l='MpServer', x=78.50, y=92.00, z=78.50], EntityChicken['Chicken'/109, l='MpServer', x=79.50, y=92.00, z=75.50], EntityChicken['Chicken'/110, l='MpServer', x=80.50, y=92.00, z=76.50], EntityChicken['Chicken'/111, l='MpServer', x=75.69, y=92.00, z=84.12], EntityRabbit['Rabbit'/119, l='MpServer', x=84.69, y=65.00, z=174.16], EntitySkeleton['Skeleton'/110741, l='MpServer', x=56.71, y=22.00, z=27.50], EntityZombie['Zombie'/109723, l='MpServer', x=97.50, y=78.00, z=107.50], EntityZombie['Zombie'/106684, l='MpServer', x=-15.50, y=25.00, z=47.50], EntitySkeleton['Skeleton'/108750, l='MpServer', x=-5.37, y=21.00, z=53.21], EntitySpider['Spider'/107732, l='MpServer', x=73.50, y=65.00, z=98.50], EntityEnderman['Enderman'/72924, l='MpServer', x=37.51, y=55.00, z=79.74], EntityItem['item.item.egg'/98595, l='MpServer', x=80.16, y=92.00, z=75.87], EntityBat['Bat'/109861, l='MpServer', x=92.47, y=19.03, z=85.22], EntityBat['Bat'/109860, l='MpServer', x=93.75, y=22.10, z=78.47], EntitySpider['Spider'/109870, l='MpServer', x=43.00, y=21.00, z=178.95], EntityZombie['Zombie'/111921, l='MpServer', x=87.50, y=56.00, z=130.50], EntityCreeper['Creeper'/111925, l='MpServer', x=66.55, y=19.00, z=117.74], EntityCreeper['Creeper'/109879, l='MpServer', x=94.50, y=39.00, z=148.50], EntityBat['Bat'/105782, l='MpServer', x=60.50, y=43.91, z=119.49], EntityBat['Bat'/109912, l='MpServer', x=92.51, y=59.92, z=99.75], EntityEnderman['Enderman'/112028, l='MpServer', x=26.50, y=17.00, z=62.50], EntityPlayerSP['DinarNaMamky'/740, l='MpServer', x=-31.70, y=70.00, z=6.10], EntityCreeper['Creeper'/112095, l='MpServer', x=47.50, y=46.00, z=93.50], EntitySkeleton['Skeleton'/109031, l='MpServer', x=-16.50, y=34.00, z=42.50], EntitySkeleton['Skeleton'/110064, l='MpServer', x=50.50, y=24.00, z=119.31], EntitySkeleton['Skeleton'/110068, l='MpServer', x=91.50, y=14.00, z=55.50], EntityItem['item.item.egg'/98863, l='MpServer', x=75.25, y=92.00, z=84.59], EntityZombie['Zombie'/109154, l='MpServer', x=67.50, y=20.00, z=121.50], EntityBat['Bat'/109162, l='MpServer', x=-1.37, y=23.10, z=52.44], EntityBat['Bat'/109165, l='MpServer', x=-18.93, y=35.87, z=36.73], EntityCreeper['Creeper'/109307, l='MpServer', x=36.52, y=46.00, z=85.83], EntityCreeper['Creeper'/108287, l='MpServer', x=36.54, y=68.00, z=100.70], EntityItem['item.item.egg'/100110, l='MpServer', x=79.08, y=92.00, z=78.89], EntitySkeleton['Skeleton'/107286, l='MpServer', x=-34.50, y=34.00, z=41.50], EntitySkeleton['Skeleton'/107289, l='MpServer', x=-3.50, y=24.00, z=45.50], EntitySpider['Spider'/107294, l='MpServer', x=87.50, y=59.00, z=117.50], EntityZombie['Zombie'/111395, l='MpServer', x=48.50, y=22.00, z=118.50], EntityZombie['Zombie'/109366, l='MpServer', x=93.26, y=51.00, z=135.55], EntityPlayerSP['DinarNaMamky'/740, l='MpServer', x=34.21, y=64.00, z=128.31], EntityBat['Bat'/109498, l='MpServer', x=57.42, y=32.92, z=25.63], EntitySkeleton['Skeleton'/107456, l='MpServer', x=-1.50, y=23.00, z=110.50], EntityBat['Bat'/109506, l='MpServer', x=0.65, y=24.52, z=43.71], EntityWitch['Witch'/109518, l='MpServer', x=-28.50, y=15.00, z=79.50], EntityPlayerSP['DinarNaMamky'/740, l='MpServer', x=19.36, y=66.00, z=99.16], EntitySkeleton['Skeleton'/111601, l='MpServer', x=0.21, y=21.00, z=46.55]]
	Retry entities: 52 total; [EntitySkeleton['Skeleton'/28703, l='MpServer', x=16.50, y=13.00, z=-70.50], EntitySheep['Sheep'/32, l='MpServer', x=-107.50, y=63.00, z=33.50], EntitySheep['Sheep'/33, l='MpServer', x=-109.50, y=63.00, z=36.50], EntityRabbit['Rabbit'/40, l='MpServer', x=-85.71, y=65.00, z=28.67], EntitySkeleton['Skeleton'/36910, l='MpServer', x=104.50, y=23.00, z=206.50], EntitySkeleton['Skeleton'/36911, l='MpServer', x=105.29, y=23.00, z=205.30], EntitySpider['Spider'/36912, l='MpServer', x=106.49, y=23.00, z=206.40], EntityPig['Pig'/23615, l='MpServer', x=-51.50, y=63.00, z=-50.50], EntityPig['Pig'/23616, l='MpServer', x=-49.58, y=64.00, z=-52.29], EntityPig['Pig'/23617, l='MpServer', x=-44.75, y=68.00, z=-49.49], EntityPig['Pig'/23618, l='MpServer', x=-47.70, y=66.00, z=-54.64], EntityPig['Pig'/23619, l='MpServer', x=26.51, y=70.00, z=-50.30], EntityPig['Pig'/23620, l='MpServer', x=18.61, y=70.00, z=-70.25], EntitySquid['Squid'/28997, l='MpServer', x=-77.57, y=60.00, z=-21.50], EntityPig['Pig'/23621, l='MpServer', x=29.31, y=70.00, z=-51.42], EntityPig['Pig'/71, l='MpServer', x=-10.75, y=68.00, z=-10.45], EntitySpider['Spider'/29006, l='MpServer', x=-81.50, y=69.00, z=41.50], EntitySkeleton['Skeleton'/28494, l='MpServer', x=17.50, y=70.00, z=-70.50], EntityBat['Bat'/29522, l='MpServer', x=5.75, y=42.82, z=-63.25], EntityBat['Bat'/29523, l='MpServer', x=0.96, y=40.23, z=-68.03], EntityBat['Bat'/29524, l='MpServer', x=7.39, y=43.23, z=-60.46], EntityItem['item.tile.decorative_pyre'/29536, l='MpServer', x=-30.02, y=70.00, z=7.54], EntityItem['item.item.staff'/29537, l='MpServer', x=-31.65, y=70.00, z=2.59], EntityItem['item.item.creative_pouch'/29538, l='MpServer', x=-28.88, y=70.00, z=5.54], EntityItem['item.tile.imbuer'/29539, l='MpServer', x=-28.85, y=70.00, z=5.90], EntityItem['item.item.golden_eye'/29540, l='MpServer', x=-31.62, y=70.00, z=5.52], EntityItem['item.item.fey_leather'/29541, l='MpServer', x=-32.44, y=70.00, z=6.88], EntityItem['item.tile.imposer'/29542, l='MpServer', x=-31.37, y=70.00, z=5.92], EntityItem['item.item.runed_dagger'/29543, l='MpServer', x=-35.26, y=71.00, z=1.77], EntityItem['item.tile.dirt.default'/29544, l='MpServer', x=-31.78, y=70.00, z=4.67], EntityItem['item.item.wildroot'/29545, l='MpServer', x=-30.41, y=70.00, z=7.87], EntityItem['item.item.seeds'/29546, l='MpServer', x=-28.93, y=70.00, z=7.13], EntityCreeper['Creeper'/28787, l='MpServer', x=21.50, y=70.00, z=-67.50], EntityZombie['Zombie'/28790, l='MpServer', x=21.50, y=70.00, z=-65.50], EntitySpider['Spider'/29306, l='MpServer', x=-54.50, y=69.00, z=59.50], EntityCreeper['Creeper'/29051, l='MpServer', x=-108.50, y=67.00, z=60.50], EntitySkeleton['Skeleton'/29307, l='MpServer', x=-54.50, y=68.85, z=59.50], EntityCreeper['Creeper'/38812, l='MpServer', x=107.51, y=22.00, z=204.84], EntityItem['item.tile.dirt.default'/28835, l='MpServer', x=-18.77, y=67.00, z=5.63], EntityItem['item.tile.dirt.default'/28837, l='MpServer', x=-16.73, y=67.00, z=6.88], EntityItem['item.tile.dirt.default'/28839, l='MpServer', x=-16.71, y=66.00, z=4.72], EntityItem['item.item.seeds'/28840, l='MpServer', x=-17.49, y=67.00, z=5.78], EntityItem['item.tile.dirt.default'/28842, l='MpServer', x=-18.88, y=67.00, z=3.36], EntityItem['item.item.wildroot'/28845, l='MpServer', x=-17.03, y=67.00, z=3.04], EntityItem['item.tile.dirt.default'/28846, l='MpServer', x=-16.79, y=67.00, z=2.45], EntityZombie['Zombie'/28600, l='MpServer', x=-25.48, y=70.00, z=7.27], EntitySkeleton['Skeleton'/28873, l='MpServer', x=36.50, y=66.00, z=-9.50], EntitySkeleton['Skeleton'/28880, l='MpServer', x=-63.50, y=70.00, z=50.50], EntityBat['Bat'/29137, l='MpServer', x=-64.25, y=25.76, z=-31.57], EntityBat['Bat'/29139, l='MpServer', x=-74.25, y=23.75, z=-26.48], EntityZombie['Zombie'/28923, l='MpServer', x=-26.77, y=70.00, z=6.48], EntityZombie['Zombie'/28925, l='MpServer', x=-15.00, y=68.00, z=0.06]]
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 467881104 bytes (446 MB) / 1644167168 bytes (1568 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID            | Version              | Source                                | Signature                                |
	|:------ |:------------- |:-------------------- |:------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft     | 1.12.2               | minecraft.jar                         | None                                     |
	| LCHIJA | mcp           | 9.42                 | minecraft.jar                         | None                                     |
	| LCHIJA | FML           | 8.0.99.99            | forge-1.12.2-14.23.5.2854.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge         | 14.23.5.2854         | forge-1.12.2-14.23.5.2854.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | baubles       | 1.5.2                | Baubles-1.12-1.5.2.jar                | None                                     |
	| LCHIJA | jei           | 4.16.1.302           | jei_1.12.2-4.16.1.302.jar             | None                                     |
	| LCHIJA | roots         | 1.12.2-3.1.0-alpha12 | Roots-1.12.2-3.1.0-alpha12.jar        | None                                     |
	| LCHIJA | mysticalworld | 1.12.2-1.9.3-alpha4  | mysticalworld-1.12.2-1.9.3-alpha4.jar | None                                     |
	| LCHIJA | patchouli     | 1.0-22               | Patchouli-1.0-22.jar                  | None                                     |
	| LCHIJA | mysticallib   | 1.12.2-1.10.0-alpha5 | mysticallib-1.12.2-1.10.0-alpha5.jar  | None                                     |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 391.35' Renderer: 'GeForce GT 540M/PCIe/SSE2'
	Patchouli open book context: n/a
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: GeForce GT 540M/PCIe/SSE2 GL version 4.6.0 NVIDIA 391.35, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 2x Intel(R) Pentium(R) CPU B950 @ 2.10GHz

**Comment by noobanidus** [comment]
Damn, I thought I'd resolved that.
