### ISSUE TITLE
[alpha12] Shatter too fast

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#622]

**Comment by noobanidus** [comment]
How fast is too fast? I deliberately removed the cooldown as I found the 20 tick delay too long; I can add it back in to 10, but I'm not sure what you're referring to.

**Comment by guide-for-you** [comment]
Shatter cooldown is like 2 in survival

**Comment by noobanidus** [comment]
That's actually intentional, do you think it's too powerful?

**Comment by guide-for-you** [comment]
So,I just tested this,and apply an modifires that decrease cooldown(and I thought that this is so fast because of this modifiers),and then I wanted to test how fast it can be without modifiref and this is the same like with "decrease cooldown" modifiers,too fast,like minigun

**Comment by noobanidus** [comment]
This is intentional. I'll experiment to consider the balance, but the responsiveness of the spell especially in combination with even mild lag made it ridiculously painful to use. I may increase the costs to compensate.
