### ISSUE TITLE
1.12.2-3.0.26 Guide book "The Druidic Arts" not reflecting player progression

### ISSUE THREAD

**Issue by WyattLuke** [EpicSquid/Roots#625]
Version: 1.12.2-3.0.26 (MC Eternal)
Issue: Guide book "The Druidic Arts" not reflecting player progression

Trouble shooting: 
-Updated/reinstalled java
-Uninstalled/reinstalled roots
-Uninstalled instance of minecraft
-Reset roots progression by commands.

The only thing I can think that may have caused the issue is that I changed my Username around the time I started having the problem but I doubt that could be the issue as I had been using it fine for a week or so after the change and have completely reinstalled the game since. I am mostly wondering if there are any files for roots progression not stored in the minecraft folder as that is the only thing I can think of.

Just to note, in the index I can only see the entry for:
-Terra Moss
-Wildroot
-Aubergine
-Knives
-Petals
-Tree Bark

**Comment by guide-for-you** [comment]
What does version of Patchouli you have?

**Comment by WyattLuke** [comment]
> 
> 
> What does version of Patchouli you have?

Patch 1.0-20

**Comment by guide-for-you** [comment]
> > What does version of Patchouli you have?
> 
> Patch 1.0-20

Install 1.0-22,it's will solve the problem
