### ISSUE TITLE
[alpha12] Monster dupe after Aqueous Soil harvested crop.

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#626]
There are no screenshot,because it lags a lot after Aqueous Soil harvested crop.

**Comment by noobanidus** [comment]
Do you remember specifically which crop it was?

**Comment by guide-for-you** [comment]
I test this in survival with Dewgonia and wheat too,both caused this thing

**Comment by noobanidus** [comment]
Was in natural growth or accelerated?

**Comment by guide-for-you** [comment]
Accelerated

**Comment by guide-for-you** [comment]
I test this now with sugar canes and stalicripe both caused this thing.

**Comment by noobanidus** [comment]
Yep, just tested it with Dewgonia. It definitely appears to be creating a ridiculous number of item entities. I'm not too sure why.

**Comment by noobanidus** [comment]
![](https://i.imgur.com/5LqE5H4.png)

**Comment by guide-for-you** [comment]
Maybe it's like when you use Floral Reproduction,it just make a lot of items from one flower
