### ISSUE TITLE
[alpha12] Unending Bowl doesn't fill or empty buckets(bottles) again.

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#627]

**Comment by noobanidus** [comment]
It won't fill buckets in creative mode, it does fill buckets in survival mode.

It's not filling bottles in either mode however.

**Comment by guide-for-you** [comment]
But I do this in survival mode((((

**Comment by noobanidus** [comment]
I may have fixed that in dev at some point.

Bottles are hard-coded so I'll need to hard-code it.
