### ISSUE TITLE
[alpha12] Ritual absorbs items twice again

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#629]
Before lit up Pyre:
![2020-11-11_14 53 44](https://user-images.githubusercontent.com/53404970/98814366-3e76ca00-242e-11eb-9778-53b64694c66f.png)
After lit up:
![2020-11-11_14 53 51](https://user-images.githubusercontent.com/53404970/98814415-4d5d7c80-242e-11eb-8cf6-106267bda392.png)
After Pyre absorbed item from the chest:
![2020-11-11_14 56 19](https://user-images.githubusercontent.com/53404970/98814488-6a924b00-242e-11eb-91c5-a5b832920167.png)
P.S.And doesn't fire up again.

**Comment by noobanidus** [comment]
Can confirm this now and replicate it.

**Comment by guide-for-you** [comment]
Sorry,I am in college now

**Comment by guide-for-you** [comment]
Oh,sorry,I just forgot about that.And...shame on me,because I just stupid and there are no problem.I just somehow thought that it looks like it takes items twice,but it firstly consumes items,and take them for next consuming(like it always be).

**Comment by noobanidus** [comment]
THAT was painful to track down but it should be fixed, thanks for finding it!
