### ISSUE TITLE
[Roots 3] Using a powder pouch in the offhand to perform runic carving makes the pouch unusable if the pouch had only 1 herb in it prior to carving

### ISSUE THREAD

**Issue by Febilian** [EpicSquid/Roots#63]
For example, let's say I have only 1 cloudberry in a powder pouch, and have that in my offhand for runic carving. I turn runic soil into aeros soil with it, but the pouch is now bugged and unusable - it appears empty, but cannot be refilled.

Neither the herb originally in the pouch nor any others will properly end up in the pouch; the recipe with the pestle will _kind of_ appear to work, but the output is just as empty as it was to begin with - this means all herbs put into the recipe to refill the pouch are voided in the process.

I have noticed this with at least cloudberries and dewgonia but suspect that all herbs used for runic carving are affected.

If you have more than 1 herb in the pouch when you runic carve, it's fine - it's just if the pouch is completely depleted in the carving process that this seems to happen.

**Comment by EpicSquid** [comment]
Since I'm reworking the pouch anyway the latest commits have changed it to just holding a stack of the herb in your offhand, thus fixing me having to do work :P
