### ISSUE TITLE
Moss config not working?

### ISSUE THREAD

**Issue by Wolfstar1010** [EpicSquid/Roots#633]
I've made edits to the moss.cfg file to add underground biomes mossy cobble -> their cobble variants and it's not producing any results in game. I was under the assumption that using a knife/runic shears on the added items would work to produce terramoss? Using the latest version of your mod. I tried including a picture of how I wrote out the config in case I messed up (most likely I messed up haha). Also, the betweenlands stone on there is also not working. 

![Screenshot 2020-11-15 170548](https://user-images.githubusercontent.com/66505198/99198179-d80ee600-2764-11eb-96b3-011a71d48453.png)

**Comment by noobanidus** [comment]
That's possibly an issue on my side. Is this the Roots 3.1 alpha or is this 3.0.34?

**Comment by Wolfstar1010** [comment]
Woah fast response!! Thanks! it's the 3.0.32 version. It's the newest version on curse currently.

**Comment by noobanidus** [comment]
Sorry, been a rough month. Can you confirm if the defaults are working and it's just what you added isn't working?

**Comment by Wolfstar1010** [comment]
No worries at all! It's definitely been a month. The defaults are working, it is only the additions not working. Thanks!

**Comment by noobanidus** [comment]
Are you able to copy/paste the configuration onto gist.github.com? Saves me typing it up for my tests.

**Comment by Wolfstar1010** [comment]
I believe I did this right... https://gist.github.com/Wolfstar1010/88816582601fac2ca580ae70556709c9

**Comment by noobanidus** [comment]
It appears some of them are working but some of them are not. This is strange, and I don't understand. There's at least an attempt to interact with them, but the replacement state doesn't seem to register and/or the recipe doesn't fire.

**Comment by noobanidus** [comment]
![](https://i.imgur.com/PGJgQS9.png)

It may or may not be a configuration issue, this is in the latest release (rather than the test release). It appears all the metamorphic ones work but none of the igenous ones work, and none of the betweenlands ones work.

**Comment by noobanidus** [comment]
Okay, I re-entered the configuration and was able to do the igneous rock as well:

![](https://i.imgur.com/6UIQqmv.png)

As well as one of the types of Betweenlands bricks...

So, attempt 2:

![](https://i.imgur.com/fLgnu9E.png)

And the result of attempt 2:

![](https://i.imgur.com/ozpvqva.png)

And attempt 3, converting them all back to mossy using adjacent water + terra spores:

![](https://i.imgur.com/MTkBB1J.png)

Unfortunately, I don't seem to be able to replicate the problem you're having. 

Are you able to try your configuration with an instance that just has Roots 3, Betweenlands and Underground Biomes as I did?

**Comment by Wolfstar1010** [comment]
Yes I can give that a shot. If you're able to get it to work then there must be some other mod conflicting with it and I have no idea where to even begin looking for it in our 200 mod list. But let me give it a shot.

**Comment by Wolfstar1010** [comment]
Alright, just tested it with only the three mods and it works perfectly! So unfortunately for me I'll have to figure out what could be causing it on our end. Sorry to raise the alarm I should have honestly tested it like this before hand.

**Comment by noobanidus** [comment]
I'm going to assume it's some mod interfering with right click. My suggestion would be to remove half the mods (excluding the essentials of course), and, if it's still doing it, remove another half until you end up with only 1 (i.e., binary search), or otherwise you swap the other half in and do the same.

**Comment by Wolfstar1010** [comment]
Thanks, I'll give that a try this weekend. Really appreciate your time and help!

**Comment by noobanidus** [comment]
No worries, sorry it took me so long! Like I said, I've had a really rough few weeks and avoided going up against "big bad" bugs and doing fun things instead.

**Comment by Wolfstar1010** [comment]
Hey there! Figured out the mod causing the issue and it's unlimited chisel works. I tried playing with their config to make it work but couldn't figure it out. But thought I'd let you know in case others have a similar issue! Thanks again for all your help!
