### ISSUE TITLE
[actually an old bug] Gathering can put items in chest below it(with ritual ingredients).

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#637]
So,there are ritual of Animal Harvest(and no chest near with Gathering ritual):
![2020-12-09_21 17 01](https://user-images.githubusercontent.com/53404970/101676775-4d1fc380-3a64-11eb-9aae-38ef264b1f96.png)
And items,that ritual gathered:
![2020-12-09_21 17 07](https://user-images.githubusercontent.com/53404970/101676861-6fb1dc80-3a64-11eb-96d9-3440fef4dd51.png)
So what the idea,it NEED to require chest in the same Y level with Pyre for structure(to put in it gathered things).And chest below cannot gather items,only take ritual ingredients.
P.S.As you see,I'm cheking this in alpha 12.
P.S.p.s..Do actually someone made bug report like this?

**Comment by noobanidus** [comment]
That was painful to track down. Should be fixed in the next alpha.

**Comment by noobanidus** [comment]
Agreed, I'll make gathering ignore the down spot.
