### ISSUE TITLE
Spell can still be crafted after being disabled in the config

### ISSUE THREAD

**Issue by Bonesteeler** [EpicSquid/Roots#638]
In my config I have disabled the rampant growth and growth infusion spells. However, I am still able to craft the spell dust using the mortar and pestle.

My spells.cfg file is here https://gist.github.com/Bonesteeler/110e4bed770954ad18380e564981f7d1
I tested this on a fresh curse profile with only Roots installed.
![image](https://user-images.githubusercontent.com/9273133/102005526-3d0b1c80-3cce-11eb-973b-0d9ae4c6c27e.png)

**Comment by noobanidus** [comment]
This will unfortunately not be fixed until the 3.1 release of Roots 3, soon(tm).
