### ISSUE TITLE
[alpha13] Fiery Harvest & Yield together,i think,need to make bread after using on fuly grown wheat.

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#644]
https://user-images.githubusercontent.com/53404970/103893653-4a150300-50f6-11eb-9b2a-9535db2fc05f.mp4

![2021-01-07_14 40 24](https://user-images.githubusercontent.com/53404970/103893670-55682e80-50f6-11eb-979e-ac41d005e33b.png)

**Comment by noobanidus** [comment]
Fixed in the next alpha:

![](https://i.imgur.com/mRCGgYX.png)
