### ISSUE TITLE
[alpha13] Infinite Germination ritual.

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#646]
https://user-images.githubusercontent.com/53404970/103916259-e0f0b800-5114-11eb-8250-59dad6460d8b.mp4

I extinguished this Pyre but it still works.
P.S.I think it's because I was flying a lot,far from this Pyre 
P.S. And it's still growing

**Comment by noobanidus** [comment]
That's confusing, I'm not able to replicte it but I'll look into it.

**Comment by noobanidus** [comment]
Also, have you been able to replicate this?

**Comment by noobanidus** [comment]
If you can replicate it with steps, please let me know.
