### ISSUE TITLE
[alpha13] Rampant Growth with using Pereskia or Spirit Herb {list of bugs}

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#648]
1)**Radius increasing:**
**Turned on only Spirit Herb,Rampant Growth:**
![2021-01-07_20 17 29](https://user-images.githubusercontent.com/53404970/103929075-63817380-5125-11eb-9b13-0db431f3ac7f.png)

https://user-images.githubusercontent.com/53404970/103929120-798f3400-5125-11eb-8e77-f172ddf80028.mp4

**Turned on only Pereskia,Rampant Growth:**
![2021-01-07_20 19 33](https://user-images.githubusercontent.com/53404970/103929236-b0654a00-5125-11eb-9aac-e9d17ade83c8.png)

https://user-images.githubusercontent.com/53404970/103929275-beb36600-5125-11eb-877b-fd9ad0ef65c5.mp4

**Turning on both**:
![2021-01-07_20 21 38](https://user-images.githubusercontent.com/53404970/103929427-fcb08a00-5125-11eb-8f5f-4b5cade1ae82.png)

https://user-images.githubusercontent.com/53404970/103929543-249fed80-5126-11eb-9d5f-9feedf560638.mp4

**Turned all Rampant Growths:**
![2021-01-07_20 26 09](https://user-images.githubusercontent.com/53404970/103929898-9bd58180-5126-11eb-924e-c353a4d4c066.png)

https://user-images.githubusercontent.com/53404970/103929987-ba3b7d00-5126-11eb-876f-48c7890089cc.mp4

**Problem: It's doesn't increase radius.**

2)Speed of growing increasing:

If you activating Rampant Growth(Spirit Herb or Pereskia,or both of them),they increasing speed of growing crop(obviously,it's works like old Rampant Growth,with same particles,even if it's activated only one of them,even Cloud Berries doesn't change particles).So,there comparing of speed with,and without modifier.
**Without modifier:**
![2021-01-07_20 35 28](https://user-images.githubusercontent.com/53404970/103930766-ec011380-5127-11eb-9eab-9f7549425f12.png)

https://user-images.githubusercontent.com/53404970/103930775-f15e5e00-5127-11eb-96a2-bcbced675985.mp4

**Only with Cloud Berry modifier:**
![2021-01-07_20 36 35](https://user-images.githubusercontent.com/53404970/103930943-31254580-5128-11eb-8c90-3597a4dfeba2.png)

https://user-images.githubusercontent.com/53404970/103931062-5ade6c80-5128-11eb-88a3-42e945e8f664.mp4

**With only Spirit Herb(only Pereskia or both or all of them,working same):**
![2021-01-07_20 40 08](https://user-images.githubusercontent.com/53404970/103931185-8eb99200-5128-11eb-9770-1eff523854a6.png)

https://user-images.githubusercontent.com/53404970/103931279-ba3c7c80-5128-11eb-91d0-e9029278e105.mp4

**Comment by noobanidus** [comment]
I think this should have been fixed in  b6baf67744, it was failing to recognise Cloud Berry as a radiuis modifier, and only increasing it by the base *if* a modifier was present, rather than increasing it for each modifier present.
