### ISSUE TITLE
[Roots 3] Impossible to legitimately acquire runestone variants/else method of acquirement is not documented

### ISSUE THREAD

**Issue by Febilian** [EpicSquid/Roots#65]
This is only really an issue because various rituals that already exist/future mechanics that have yet to be implemented will require the offering plate as far as I'm aware, and you cannot make the offering plate without at least the chiseled runestone variant.

I would assume that the method to obtain these either is not quite implemented yet, or the method of obtaining them is not yet documented, but either way thought it might be good to have a reminder here...

**Comment by EpicSquid** [comment]
There is no method currently, this needs to not be forgotten.

**Comment by duely** [comment]
This is actually done, recipes were added for runestone bricks and chiseled runestone, along with normal/brick slabs, normal/brick walls and normal/brick stairs.
