### ISSUE TITLE
Fairy

### ISSUE THREAD

**Issue by I3estOFF** [EpicSquid/Roots#651]
#**Suggestion:**
Option to add Fairy to the game, That was so magical mob, that adds pretty feature to the landscape.
In roots 3 its gone?! We want them back! :)))) or just a way to add them :))
![image](https://user-images.githubusercontent.com/63112899/104012144-9d975780-51af-11eb-9b82-76f6452076bb.png)

**Comment by noobanidus** [comment]
These are slated to be re-added in 3.2 in the 1.16.4 update; they won't make it into 3.1, but they are planned!

**Comment by I3estOFF** [comment]
Yea! <3 
Will 3.2 version be available on 1.12.2?

**Comment by noobanidus** [comment]
No, 3.1 will be the last version for 1.12.2. I'm sad that it's taken this long to finish it, but delaying the move to 1.16.4 will make the porting process *insane*.

**Comment by I3estOFF** [comment]
ohh :( 
that's so sad! 1.12.2 has so many great mods, that 1.16 hasn't!
I would add fairies by myself if i know how to do that! but i can't :(

**Comment by I3estOFF** [comment]
well, then see ya in 1.16! Maybe in 2025 when it'll has more great mods! :')
Thanks for the answer!
Appreciate it!
