### ISSUE TITLE
[alpha13] It's looks like Radiance doesn't use herbs

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#652]
![2021-01-09_14 40 05](https://user-images.githubusercontent.com/53404970/104091943-7319cd00-5289-11eb-97e8-520ddb82cef5.png)
(I've checked several times,it's really doesn't take any herbs)
Oh,it's using herbs only when touch someone

**Comment by noobanidus** [comment]
So, I'm going to make it be dimmer if you don't hit anything, so at least you'd see the path of it.
