### ISSUE TITLE
Sky soarer fall damage always mitigated

### ISSUE THREAD

**Issue by noobanidus** [EpicSquid/Roots#660]

**Comment by Vaelzan** [comment]
Somebody should close this issue report for not filling out the template properly. ;)

**Comment by noobanidus** [comment]
@Vaelzan What template? 🦘

**Comment by Vaelzan** [comment]
![hi-nooby](https://user-images.githubusercontent.com/6418846/104665803-6df3cc80-5726-11eb-8652-d2a9b12341b9.png)

**Comment by Vaelzan** [comment]
You'll have to try harder than that!

**Comment by noobanidus** [comment]
Sorry?
