### ISSUE TITLE
[1.16.4] Update for latest Minecraft version

### ISSUE THREAD

**Issue by SupGamerNL** [EpicSquid/Roots#662]
Would it be possible to update the mod to Minecraft 1.16.4? 'Cause, the mod is great, and I have played with it in multiple Modpacks with different playstyles. I really love this mod and I want to thank you for that (plus all your mods are great, to be honest).

This is just a suggestion, because of how great it would be if I can play the mod in Minecraft 1.16.4

**Comment by noobanidus** [comment]
The port will happen after the upcoming 3.1 release!
