### ISSUE TITLE
Apothecary Pouch item deletion

### ISSUE THREAD

**Issue by Laephis** [EpicSquid/Roots#663]
### General Information

**Describe the bug:**
When placing dewgonia into an apothecary pouch vial, if the amount exceeds 32, any amount over that will disappear.

**To Reproduce:**

1. Place 33+ pieces of dewgonia into an apothecary pouch vile
2. Close the pouch
3. Reopen the pouch and only 32 pieces will be available

**Expected behavior:**
Maximum amount should be similar to the other reagents (64).  Putting more than the maximum amount should not result in a loss of the extra reagents.

***

### Environment Versions

**Mystic Mods Versions**

- Roots-1.12.2-3.0.32
- mysticallib-1.12.2-1.9.0
- mysticalworld-1.12.2-1.9.2
- Patchouli-1.0-22

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- forge-1.12.2-14.23.5.2854-universal
- Minecraft: 1.12.2
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by noobanidus** [comment]
This is a known issue but unfortunately it won't be fixed until 3.1. I'd recommend taking the dewgonia out completely, closing the pouch, opening it again and then putting the entire stack in. I believe this will fix it.

**Comment by Laephis** [comment]
> 
> 
> This is a known issue but unfortunately it won't be fixed until 3.1. I'd recommend taking the dewgonia out completely, closing the pouch, opening it again and then putting the entire stack in. I believe this will fix it.

Thanks for the reply.  Yes, doing things in the order you described is an effective workaround.  I'll keep an eye out for 3.1.  Thanks for the great mod!

**Comment by noobanidus** [comment]
Apologies for the problem, it is frustrating! You can also enable "auto refill pouches" in the config on the server & client and it should help with topping things up without deleting htem (in theory).

**Comment by noobanidus** [comment]
This will hopefully be fixed as of March 31st with the release of 3.1.
