### ISSUE TITLE
[alpha15] Runestone for those who have drip

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#667]
![2021-02-12_21 25 20](https://user-images.githubusercontent.com/53404970/107820611-c2b95000-6d83-11eb-819a-c52cce6fcd5a.png)

**Comment by noobanidus** [comment]
That's a deliberate change this version. Do you think it works?

**Comment by guide-for-you** [comment]
https://user-images.githubusercontent.com/53404970/107846456-8ff77200-6dec-11eb-98b1-e35cfe9a4e95.mp4

**Comment by noobanidus** [comment]
I should clarify, I added diamonds, emeralds, glowstone dust, prismarine crystals, and redstone as suitable ingredients for making runestone deliberately.

**Comment by guide-for-you** [comment]
Ok,sorry
