### ISSUE TITLE
[alpha15] Overgrowth ritual doesn't check cobblestone under water

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#668]
https://user-images.githubusercontent.com/53404970/107821073-85a18d80-6d84-11eb-80c8-b91420853c2b.mp4

**Comment by noobanidus** [comment]
This was partially a deliberate choice that I might turn into a configuration option. When using terra spores, it only checks the 4 vertical faces (and possibly below). I'll double-check and make a decision.

**Comment by noobanidus** [comment]
I'm going to update this in the documentation but it very specifically says adjacent -- not above or below.
