### ISSUE TITLE
[alpha15]Bug with sound when using Time Stop 

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#669]
https://user-images.githubusercontent.com/53404970/108087134-d0225300-707f-11eb-8536-120df4fa58bf.mp4

**Comment by noobanidus** [comment]
That is odd, let me look into that.

**Comment by noobanidus** [comment]
Strangely, I can't replicate this, but I'm not happy with the sound.

**Comment by noobanidus** [comment]
I'm hoping to have alternate sounds made for these, for now I've just disabled them.
