### ISSUE TITLE
[alpha15] A bunch of unlocalized name of modifiers

### ISSUE THREAD

**Issue by guide-for-you** [EpicSquid/Roots#670]
![2021-02-16_17 21 24](https://user-images.githubusercontent.com/53404970/108087700-5f2f6b00-7080-11eb-8631-41de09dd3493.png)
![2021-02-16_17 21 29](https://user-images.githubusercontent.com/53404970/108087711-60609800-7080-11eb-8f29-1c862faef810.png)
![2021-02-16_17 33 59](https://user-images.githubusercontent.com/53404970/108087712-60f92e80-7080-11eb-8d9b-dd5ab9be7e31.png)
![2021-02-16_17 54 48](https://user-images.githubusercontent.com/53404970/108087714-60f92e80-7080-11eb-8f0a-9246399dc481.png)

**Comment by noobanidus** [comment]
Thank you!
