### ISSUE TITLE
Baubles support for Quiver

### ISSUE THREAD

**Issue by DoomRater** [EpicSquid/Roots#718]
Thanks to some snooping, I spotted that there's a quiver in Thaumic Periphery doing fine stuff with a Baubles slot. Doesn't look hacky at all, and I've tested it working on the Crystal Bow from Botania- works fine as long as I don't have a mana container (because the Periphery quiver checks to see if there's ammo first before applying its own effects).

Maybe it's time to give this another look?

Magic Quiver code for reference: https://github.com/the-realest-stu/Thaumic-Periphery/blob/master/src/main/java/thaumicperiphery/items/ItemMagicQuiver.java

**Comment by noobanidus** [comment]
Unfortunately, this isn't a feature I'm going to be implementing in 1.12. Sorry!
