### ISSUE TITLE
1.12.2 Issue: Petal Shell is OP.

### ISSUE THREAD

**Issue by toErIpNid** [EpicSquid/Roots#735]
### General Information

**Describe the bug:**
Petal shell is way too over powered and spammable. With enough spirit herbs you're basically immortal. Petal shell even blocks the effects of harmful potions, which is not something I would expect physical petals to block. 

**To Reproduce:**

1. Equip petal shell.
2. Profit.

**Expected behavior:**

I expected it to block physical damage not basically everything. 

### Environment Versions
1.12.2

**Mystic Mods Versions**

- MysticalLib: 1.12.2-1.10.0
- MysticalWorld: 1.12.2-1.9.8

**Other Versions:**
None.

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by guide-for-you** [comment]
It's can be actually solved by increasing cooldown.This spell places players that using Roots on the same level with other mods that have godlike equipment

**Comment by toErIpNid** [comment]
> It's can be actually solved by increasing cooldown.This spell places players that using Roots on the same level with other mods that have godlike equipment

Unfortunately you cannot configure petal shell's cool down in 1.12. Not sure if you can in the 1.17 alpha. Also, most mods do not have something that literally blocks any kind of damage form affecting you like petal shell does, thus the reason why it is insanely overpowered.

**Comment by noobanidus** [comment]
There's no 1.17 alpha, the next version will still be 1.12.

**Comment by noobanidus** [comment]
So, the CraftTweaker configuration of 3.1 will allow you to adjust the cooldown of Petal Shell.

Honestly, this has literally been the only complaint about the spell in the entirety of the 3.0 release cycle -- which has basically been two years. I'm not really sure that it's as big of an issue as you seem to feel, but you are more than welcome to use the code that disables spells (in the configuration) to prevent people from using it if you think it's overpowered (until 3.1 is released).
