### ISSUE TITLE
Wildfire's "Spiritual Duality" upgrade shows Growth description

### ISSUE THREAD

**Issue by SeriousCreeper** [EpicSquid/Roots#743]
### General Information

**Describe the bug:**

When checking the last page for the wildfire, it says that with spiritual duality you can grow crops in an area, when in reality it should be that it fires a 2nd jet of fire (like it says a few pages before)

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 1.11.0
- Roots 3.1.0

***

### Additional Information
**Screenshots (if available):**
![java_KY9nRPdpug](https://user-images.githubusercontent.com/571759/131785607-e92c965e-a879-4ed3-bbaf-f4407a713326.png)
![java_Sp4j7R0J0O](https://user-images.githubusercontent.com/571759/131785609-d8fdc923-8698-4a9a-b687-d1658097d632.png)

**Comment by noobanidus** [comment]
That looks like a bad link in the chapter. Whoops. I blame @GentlemanGnu
