### ISSUE TITLE
Runed wood creation gives wrong log types

### ISSUE THREAD

**Issue by DrTasslehoff** [EpicSquid/Roots#745]
### General Information

**Describe the bug:**
When creating runed wood for Roots rituals, this is what I found: Oak and acacia work properly. Birch, spruce, and jungle logs create runed oak. Dark oak creates runed acacia.

**To Reproduce:**

1. offhand wildroot and right click log with knife

**Expected behavior:**
Birch should create runed birch. Spruce should create runed spruce. jungle should create runed jungle. Dark oak should create runed dark oak.

***

### Environment Versions
Roots 3.1.1

**Mystic Mods Versions**
- MysticalLib: 1.11
- Mystical World: 1.10

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 14.23.5.2855
- Minecraft: 12.2
- Modpack (if available): 

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**
![MO0v25BON2](https://user-images.githubusercontent.com/42073120/132113022-982bb705-eeba-4c80-bcc3-e4185ca7045c.png)

**Comment by noobanidus** [comment]
I blame @SeriousCreeper for this one.

**Comment by SeriousCreeper** [comment]
![woops](https://c.tenor.com/-KdqIremkc8AAAAC/andy-chris-pratt.gif)
