### ISSUE TITLE
[3.1.1] SetSlot Packets Occasionally cause concurrent modificaiton error

### ISSUE THREAD

**Issue by PokeMaserJ** [EpicSquid/Roots#746]
### General Information

**Describe the bug:**

Reminder from Discord message
**To Reproduce:**

1. First Step
2. First Step
3. First Step

**Expected behavior:**

*** 

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 1.11.0
- Ecc...

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 14.23.52855
- Minecraft: 1.12.2
- Modpack (if available):

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

https://gist.github.com/PokeMaserJ/132dbf6bfd17e13f3958257d4bfb587c

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by noobanidus** [comment]
Thanks!
