### ISSUE TITLE
Bugged movement of silkworm entity

### ISSUE THREAD

**Issue by Jukabofy** [EpicSquid/Roots#747]
### General Information

**Describe the bug:**
it just move laggy, in every way, specially when it recive damage

**To Reproduce:**

1. just spwan them with eggs or commands
2. https://imgur.com/a/XqeSepU

**Comment by noobanidus** [comment]
This mob is from Mystical World, not Roots, please open the issue on that tracker with more information.

1. A static image doesn't help in the slightest, please provide a video detailing your concerns.
2. Please provide information about the modpack, server, RAM, etc.
3. Is the silkworm the only mob behaving like this?
4. Please clarify what version of Minecraft, Mystical World, etc, you are using.

**Comment by Jukabofy** [comment]
1. https://drive.google.com/file/d/1BpoH6QF3gwlXe6pWdKhX6ohalu80UkM-/view?usp=sharing
2. I'm in single player mode
3. my mods: https://imgur.com/a/ytyQ227       
4. 8GB RAM
4. Just the silkworm
5. 
mysticalworld-1.16.5-0.3.3.19.jar and 1.16.5 minecraft
OptiFine HD U G8, forge 36.2.4 
@noobanidus
