### ISSUE TITLE
RunicCrafter crash when running on server

### ISSUE THREAD

**Issue by warmthdawn** [EpicSquid/Roots#748]
### General Information

**Describe the bug:**
RunicCrafter crash when running on server

**To Reproduce:**
1.Start a Server
2.Place the crafter
3.place any item on it

### Environment Versions
Roots 3.1.0, forge-1.12.2-2854

**Mystic Mods Versions**

- MysticalLib: 1.11.0
- MysticalWorld: 1.10.0

***

### Logging Information
**Crash Report (if available):**
https://gist.github.com/warmthdawn/b97ccc27ea6ddecb0769cb1dd1b88f66

**Latest Log (if necessary):**
https://gist.github.com/warmthdawn/0f4752cef0dae94e807e6817b3687002

***

### Additional Information
I suppose that it may because of wrong call of some client-only functions on server

**Comment by MrMykas** [comment]
I had the same problem on a new server I am making with some friends (with Roots 3.1.0). 
In our case the crash happened immediately after placing the RunicCrafter on the world, without even using it.

**Comment by noobanidus** [comment]
Yep, that's on the docket for the 3.1.2 release! Hopefully I'll get it out some time today.
