### ISSUE TITLE
Comparator measuring Pyre craft causes ticking block crash

### ISSUE THREAD

**Issue by WaitingIdly** [EpicSquid/Roots#749]
### General Information

**Describe the bug:**
When detecting the comparator level of the Pyre, if the Pyre has a valid craft/ritual, the game crashes. This is consistently repeatable in isolated environments. Could not cause it to occur with the Fey Crafter. 

**To Reproduce:**
1. Load world with Roots & dependents.
2. Place Pyre
3. Toss ingredients required to craft something (or do a ritual) with the Pyre onto the Pyre
4. Place Comparator to measure the Pyre
5. Crash, and crash on attempting to reload the world.

**Expected behavior:**
Not crash

***

### Environment Versions

**Mystic Mods Versions**
- MysticalLib: 1.11.0
- MysticalWorld: 1.10.0
- Roots: 3.1.1

**Other Versions:**
- Other mods you think could cause issues: None, could reproduce with only Roots, dependents, and JEI.
- Forge: 14.23.5.28.55
- Minecraft: 1.12.2

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**
https://paste.ee/p/bqiOs

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

a person about to crash
![image](https://user-images.githubusercontent.com/25394029/133443419-5dd2ab3c-6782-4bf3-861a-e75fac865282.png)

**Additional context (optional):**

First identified here: https://github.com/Divine-Journey-2/main/issues/292, and then reproduced with only roots for this bug report.

**Comment by noobanidus** [comment]
That is ... weird.

**Comment by noobanidus** [comment]
This'll be fixed in the next release but there may be issues with the comparator output not being correct.

**Comment by noobanidus** [comment]
[3.1.2](https://www.curseforge.com/minecraft/mc-mods/roots/files/3461007) should contain all these fixes. Please let me know if there are further issues with the comparator.

One of those issues might be that the outputs aren't properly documented anywhere... and I'm not sure if the logic is correct, but I wanted to get the fix out on the runic crafter.
