### ISSUE TITLE
Unending bowl can fill up lots of different fluid inventorys

### ISSUE THREAD

**Issue by Katsuro27** [EpicSquid/Roots#759]
You can fill a lot of fluid inventorys with the unending bowl even though there is a liquid inside that isnt water. So you basically can create a creative tank with it (EnderIO Tanks work with this for example)

**Comment by noobanidus** [comment]
Hm, that shouldn't be happening. I'll double-check, and most likely blame SeriousCreeper for this one too! :D

**Comment by noobanidus** [comment]
Looks like I missed a check, whoops.
