### ISSUE TITLE
Game crashes when crafting on a pyre or fey crafter

### ISSUE THREAD

**Issue by Skorpiont** [EpicSquid/Roots#760]
### General Information

At the start of crafting items on a pyre or fey crafter the game crashes with a server connection error (I'm playing single player)
But the last time it issued such an error with a crash log (attached)
[crash-2021-10-06_23.42.06-client.txt](https://github.com/MysticMods/Roots/files/7295820/crash-2021-10-06_23.42.06-client.txt)

you put all the necessary items on the pyre, set it on fire - the game crashes
also with fey crafter

**Comment by noobanidus** [comment]
Can you try updating to 3.1.3?

**Comment by Skorpiont** [comment]
But where i can find it? latest version on curseforge it's 3.1.2

**Comment by noobanidus** [comment]
That's... strange, for some reason I thought 3.1.3 was the latest, my bad. It looks like I *did* miss an instance of Minecraft potentially being null, but I don't understand *why* the world is null. It doesn't make any sense. Are you using Optifine or a specific launcher?

**Comment by Skorpiont** [comment]
I use GDLauncher 
Without optifine

**Comment by noobanidus** [comment]
Can you try 3.1.4? I released 3.1.3 but it had a dependency issue, so it's been archived. The latest is now 3.1.4, which requires MysticalLib 1.13.
