### ISSUE TITLE
Server crash when opening the Creative Pouch

### ISSUE THREAD

**Issue by MrMykas** [EpicSquid/Roots#761]
### General Information

**Describe the bug:**
Server crash when you open the pouch interface (pressing P) having the Creative Pouch.

**To Reproduce:**
1. Equip the Creative Pouch
2. Press P

**Expected behavior:**
It should open the interface or show a message telling you that the Creative Puch doesn't have an inventory.

***

### Environment Versions
Roots 3.1.4, forge-1.12.2-2854

**Mystic Mods Versions**
- MysticalLib: 1.13.0
- MysticalWorld: 1.11.0

***

### Additional Information
**Screenshots (if available):**
![crash error](https://user-images.githubusercontent.com/90560981/137773210-a1584082-7663-432b-81c7-0508156ed880.jpg)

**Comment by noobanidus** [comment]
Honestly, creative items aren't really designed to be used outside of testing purposes, and development on 1.12 has basically halted. Unless there is another major issue, I don't intend to release another version for 1.12.
