### ISSUE TITLE
Floral Reproduction not working on Biomes o Plenty flowers

### ISSUE THREAD

**Issue by theavandiepen** [EpicSquid/Roots#763]
I'm not sure if this is a bug or something I haven't spotted in the config files, but the Floral Reproduction modifier seems not to work on any Biomes o Plenty flowers

**Comment by noobanidus** [comment]
I believe it may potentially be hardcoded to only work on Vanilla plants; getting it to work on other plants proved quite problematic. Given that we're diving pretty heavily into the 1.16.5 port, I don't know that there will be any intent to change this.
