### ISSUE TITLE
crash client at startup

### ISSUE THREAD

**Issue by avescarelo** [EpicSquid/Roots#769]
### General Information

**Describe the bug:**
I get a crash on client stratup

**Crash Report (if available):**
[https://gist.github.com/avescarelo/58edbe47e1aaa516939bf5525c56f446](https://gist.github.com/avescarelo/58edbe47e1aaa516939bf5525c56f446)

**Comment by noobanidus** [comment]
It looks like some mod is removing one of the default Minecraft items. [It should use jungle bark and beetroot seeds](https://github.com/MysticMods/Roots/blob/release/3.1.5/src/main/java/epicsquid/roots/init/ModRecipes.java#L170) but those don't appear to be valid.

No mod should be deleting/disabling items like that...

**Comment by noobanidus** [comment]
I'll need more information to be able to follow this up. If you are able to provide any, please respond to this thread and I'll re-open.
