### ISSUE TITLE
Armour render glitch with Epic Fight

### ISSUE THREAD

**Issue by GDrayn** [EpicSquid/Roots#770]
### General Information

**Describe the bug:**
Roots armour renders incorrectly while in battle mode with Epic Fight.

**To Reproduce:**
1. Install both mods
2. Equip armour
3. Look at yourself

**Mystic Mods Versions**
- MysticalLib: 1.12.2 - 1.13.0
- Roots 1.12.2 - 3.1.4

**Other Versions:**
- Epic Fight 2.2.8
- Forge: 14.23.5.2855
- Minecraft: 1.12.2

***

### Additional Information
![Armour Bug](https://user-images.githubusercontent.com/80633551/143215289-c4312ec0-8016-41fe-b341-51189346ed3c.png)

**Additional context:**
The Epic Fight developer posted a fix for other mod devs willing to make their armour compatible with his mod:
https://github.com/Yesssssman/epicfightmod/issues/536

**Comment by noobanidus** [comment]
At this point in time, 1.12.2 development is basically impossible.

EDIT: If there's a critical issue with Roots that needs a fix, I'll look at doing it, but at this point in time, 1.12.2 is both so far in the past and getting the development environment to function properly without spending hours recompiling and decompiling...

**Comment by noobanidus** [comment]
1.12 is utterly unworkable and I have no desire to go back to it; sorry.
