### ISSUE TITLE
Infinite Fluid Glitch with Unending Bowl

### ISSUE THREAD

**Issue by Realities5806** [EpicSquid/Roots#773]
### General Information

Hello! I'm one of the moderators for Divine Journey 2 and there seems to be a bug with the Unending Bowl that allows you to generate infinite amounts of any fluid fairly early-game.

**Describe the bug:**
By using an Unending Bowl on a EnderIO Fluid Tank, you can create infinite amounts of any fluid. This also works with the Meat Feeder from Industrial Foregoing, constantly refilling the feeder if you have a Bowl in your inventory

**To Reproduce:**
1. Place an EnderIO Fluid Tank
2. Put any amount of any fluid into the tank
3. Right-click the tank with an Unending Bowl

**Expected behavior:**
The expected behavior would be that the Bowl would only be able to provide water.

***

### Environment Versions

**Mystic Mods Versions**
- MysticalLib: 1.12.2-1.13.0
- Mystical World: 1.12.2-1.11.0
- Roots: 1.12.2-3.1.4

**Other Versions:**
- Conflicting mod (if regarding mod integration): EnderIO, but there could be others
- Other mods you think could cause issues: No other mods conflicts are currently known
- Forge: 14.23.5.2855
- Minecraft: 1.12.2
- Modpack (if available): Divine Journey 2

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**
No crash report

**Latest Log (if necessary):**
No log necessary

***

### Additional Information
**Screenshots (if available):**
![2022-01-22_13 52 46](https://user-images.githubusercontent.com/87582914/150653505-8a2ded03-7aa1-454d-82c5-bf996bc9e7c3.png)
![2022-01-22_13 53 08](https://user-images.githubusercontent.com/87582914/150653508-e8096c64-db70-4d2a-8efe-b975c51b2fc3.png)
![2022-01-22_13 53 11](https://user-images.githubusercontent.com/87582914/150653509-7a3115fc-3b5e-404e-876a-635e74a52821.png)

**Additional context (optional):**
I set up a Mechanical User to see if it was possible to automate using the bug and it turns out it is. I chose to use Liquid Starlight as an example because late-game uses a lot of it, along with some other fluids (including one that is used for Chaos Shards)

**Comment by noobanidus** [comment]
Unfortunately, I'm not able to build this mod any more, let alone get a development environment working for 1.12. I think the only option for you would be to disable the recipe for the Unending Bowl.

**Comment by noobanidus** [comment]
Okay, someone's managed to get the build environment to function again, so I'm going to try looking into this.

**Comment by noobanidus** [comment]
I've got this fixed on git. I'll see what else I can fix before making a new release.
