### ISSUE TITLE
1.12.2 Slime Monster Reanimation Crashes Game

### ISSUE THREAD

**Issue by ECubeD1** [EpicSquid/Roots#781]
### General Information

**Describe the bug:**

Whenever you perform the monster reanimation ritual for slimes in Minecraft 1.12.2 the altar glows purple for a few seconds and then crashes the whole game.

**To Reproduce:**

1. Set up altar with mundane and attuning stones surrounding the altar
2. Put incense burners with one containing a nether wart and the other coal and light with flint and steel (I have lit both before and after next step)
3. Place three slime balls on the altar and left click with no item in hand (this causes the purple light from altar and then game crash).

**Expected behavior:**

It is expected that a slime would spawn after the purple glowing light disappears.
***

### Environment Versions

I have only tried to do this with minecraft 1.12.2 (RootsClassic-1.12.2-1.1.5) and the hexxit modpack installed as well. I have not tried any other versions. 

**Mystic Mods Versions**

- I do not believe I have any installed as far as I can see should they contain the word mystic in the name

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: CurseForge
- Minecraft: 1.12.2
- Modpack (if available): Hexxit
I have a couple backpack mods, minihud, etc. installed as well, but none that I believe would conflict. 
***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

https://gist.github.com/ECubeD1/60a6340c306deef56282bdacebbf504e
(I believe I did this right)
**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

I can summon every other mob, but a slime crashes it. I have tried out in the open and below y = 39. I have also tried summoning them both above and below y = 39 in a slime chunk and with all other entities killed as well as them being there

**Comment by noobanidus** [comment]
Ah, I didn't realise this was for Roots Classic. I'm afraid this is only for Roots 3.1 and later.
