### ISSUE TITLE
how to compile/self compile bug

### ISSUE THREAD

**Issue by Juff-Ma** [EpicSquid/Roots#785]
this is maybe not a real bug (maybe i'm dumb) if someone read m issue from yesterday, i fixed something myself and the game crashed with "java.lang.IllegalAccessError: tried to access field net.minecraft.item.ItemHoe.field_185072_b from class epicsquid.roots.item.runed.ItemRunedHoe" so how to compile this mod corectly?

**Comment by noobanidus** [comment]
I'm not sure what you mean by this. Can you provide some more context?

Is this error occurring in-game? Is this happening when you try to compile the mod yourself? Is this happening with another mod installed?

**Comment by Juff-Ma** [comment]
If I compile the mod myself even if change nothing on the source (3.1.5) on starting Minecraft (just roots and it's dependencies) I get the error from top
I compile with jdk 8 and:
call gradlew.bat build

**Comment by Juff-Ma** [comment]
If I use the precompiled ones from curse this doesn't happen

**Comment by noobanidus** [comment]
Ah, the current release is 3.1.4. There might be an issue with 3.1.5. I'll look into it some time today, as I've been asked to do the 3.1.5 release.

**Comment by Juff-Ma** [comment]
Oh okay I'll try again I already have wondered why the 3.1.5 also is named 3.1.4
