### ISSUE TITLE
Client crash upon using the fire starter

### ISSUE THREAD

**Issue by Gronglegrowth** [EpicSquid/Roots#787]
### General Information

**Describe the bug:**
Upon using the fire starter, regardless of on what, the game crashes.

**To Reproduce:**
1. Get a fire starter
2. Right click on any block/pyre
3. Observe the game crash

**Expected behavior:**
A fire should be lit where used.

***

### Environment Versions

**Mystic Mods Versions**
- MysticalLib: 1.13.0
- MysticalWorld: 1.11.0
- Roots 3.1.5

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge: 14.23.5.2855
- Minecraft: 1.12.2
- Modpack (if available):

***

### Logging Information

**Crash Report (if available):** [here](https://pastebin.com/66R355as)

**Latest Log (if necessary):** [here](https://pastebin.com/WMXYfwpD)

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by noobanidus** [comment]
I don't understand why the access transformers aren't applying.

**Comment by santan666** [comment]
I had this same issue using mysticalworld-1.12.2-1.11.0.jar and Roots-1.12.2-3.1.5.jar in a mod pack i was throwing together. 

Eventually ended getting the mod working but had to revert to roots version Roots-1.12.2-3.1.4.jar. While keeping mysticalworld-1.12.2-1.11.0.jar

**Comment by noobanidus** [comment]
Reverting to 3.1.4 should be acceptable, there are only a few fixes. Something happened in the new development environment that has broken access transformers and I'm not able to figure out why.

**Comment by noobanidus** [comment]
This will be fixed in 3.1.6.
