### ISSUE TITLE
Crash with LagGoggles when using the spectator mode of Roots' Augment spell

### ISSUE THREAD

**Issue by osimon8** [EpicSquid/Roots#788]
### General Information

Reproducing the issue report [here ](https://github.com/Divine-Journey-2/Divine-Journey-2/issues/698) from the Divine Journey 2 repo

**Describe the bug:**

I selected the Augment Spell (which has the spectator augment) from my spell library and used it. I got into spectator mode, but when I exited spectator mode again, the game crashed and sent me back to the main menu. The screen informed me that Roots and LagGoggles were responsible for the crash. I rejoined the server and used the spell again. This time, I crashed immediately and the screen said that only Roots was responsible for the crash. After rejoining the server again, I was in spectator mode however. When the spell ended and I was set into survival mode again, the game crashed yet again saying that Roots and LagGoggles were responsible. From this point on, the game crashed every time I used the spell and when the spell ran out as described above.

**To Reproduce:**

1. Aquire a Roots Staff, aquire the Augment Spell and upgrade it with the Light Drifter Augment, aquire a Herb Pouch and put all the necessary herbs into it.
2. Use the Augment Spell in the Roots Staff
3. If it doesn't crash immediately, wait for the spectator timer to run out and observe the crash screen.

In my testing, I get the exit crash the first time I set the Augment spell to use Light Drifter and attempt to use it, and the following use upon reloading the world after the crash I get the enter crash. 

**Expected behavior:**

The augment spell functions with the Light Drifter Augment, allowing you to enter/exit spectator mode without crashing. 

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 1.13.0
- MysticalWorld: 1.11.0
- Roots: 3.1.5

**Other Versions:**
- Conflicting mod (if regarding mod integration): LagGoggles 5.8-132
- Other mods you think could cause issues:
- Forge: 14.23.5.2860
- Minecraft: 1.12.2
- Modpack (if available): Divine Journey 2 2.15.0

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

[Exiting - crash-2022-07-27_16.39.43-client.txt](https://gist.github.com/osimon8/f0a4ce720506ef38ef4a9cc844ab6dd5)

[Entering - crash-2022-07-27_16.43.42-client.txt](https://gist.github.com/osimon8/80538cd367dde418306c590acc2960f5)

**Latest Log (if necessary):**

[Exiting - latest.log](https://gist.github.com/osimon8/40d6fbfced7130f7b3c2d85314f5da84)

[Entering - latest.log](https://gist.github.com/osimon8/3a277b800ab573dc005d8495d521122d)

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

**Comment by noobanidus** [comment]
There are consistent issues with access transformers in the most recent release of Roots. While it does fix a number of issues, my suggestion would be to regress Roots back to the previous version. Beyond that, I've no way of solidly debugging what's going on with ForgeGradle & 1.12 in later versions.

**Comment by noobanidus** [comment]
This will be fixed in 3.1.6, please update when possible.
