### ISSUE TITLE
[Roots 3]Hard Crash from in world visualizer in Patchouli book

### ISSUE THREAD

**Issue by WaxilliumGlass** [EpicSquid/Roots#79]
Hard crash, full crash report: https://pastebin.com/TY79gm1E

Ways to reproduce it - Go to any of the pyre entries in the book that have a multi-block structures listed in its entry and hit the button that visualizes them in-world.

**Comment by Davoleo** [comment]
I can confirm, I just got it as well :P

**Comment by duely** [comment]
Suggestion: do a test multiblock entry without the Pyre, because I'm pretty sure that must be what's causing the rendering bug.

**Comment by duely** [comment]
As it doesn't appear to be going to be fixed for the new version, I'm just going to disable visualising multiblock structures for beta release.
