### ISSUE TITLE
Advancment not working?

### ISSUE THREAD

**Issue by VoidMage236** [EpicSquid/Roots#794]
### General Information

**Describe the bug:**
When I craft the guide book I don't get the advancement.

**To Reproduce:**

1. Get the wild root
2.  Grab a log 
3.  Craft the guide

**Expected behavior:**

I would expect the advancement to unlock, but it doesn't.
***

### Environment Versions

1.12.2-3.1.6
**Mystic Mods Versions**

- MysticalLib: 
- Ecc...

**Other Versions:**
- Conflicting mod (if regarding mod integration):
- Other mods you think could cause issues:
- Forge:
- Minecraft:
- Modpack (if available):
The mod packs I have been using are R.A.D and Enigmatica 2 Extended 
***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service**

**Crash Report (if available):**

**Latest Log (if necessary):**

***

### Additional Information
**Screenshots (if available):**

**Additional context (optional):**

I'm not sure if it roots, better advancements, or there is something really wrong with my minecraft account, but the bug seems to happen no matter which modpack I am playing.
Also everything is done in survival, but when I made the world I had cheats enabled each time.

**Comment by noobanidus** [comment]
Have you tried doing this in a world with just Roots? It may be that advancements have been changed by the pack.

Alternately, you should be able to grant yourself the advancement manually.

**Comment by VoidMage236** [comment]
I have not tryed roots by itself I was just really confused since it worked
in one world and not in any other world after I got it. I'lltry it by
itself and see if it works . I did check the advancements notepad in the
folder and it said I completed the criteria for it if that means anything.

**Comment by VoidMage236** [comment]
I have now tried it with just the mod alone and the book advancement still seems to be broken.

**Comment by VoidMage236** [comment]
Upon further testing in creative mode it just seems like the book advancement is broke, but the other ones still work.
