### ISSUE TITLE
Caelic Soil description in Guide does not mention that it needs to be able to see the sky

### ISSUE THREAD

**Issue by mycroftjr** [EpicSquid/Roots#795]
version 1.12.2-3.1.6
The in-game guide page on Caelic Soil fails to mention that it needs to be able to see the sky in order to transform (i.e. no opaque blocks anywhere above it). Please at least hint at this, or better yet, remove the requirement, as it conflicts with Botania's Open Crate (which can only drop downward).

**Comment by ByThePowerOfScience** [comment]
@noobanidus I agree with removing the requirement, but what do you think?

**Comment by noobanidus** [comment]
Removing that requirement should be fine; it works thematically, but obviously inhibits some automation functionality.
