### ISSUE TITLE
[BUG] Growth Infusion attempts to grow modded Grasses

### ISSUE THREAD

**Issue by anabsolutesloth** [EpicSquid/Roots#797]
### General Information

**Describe the bug:**
The Growth Infusion spell will target and attempt to grow modded Grass blocks, such as TConstruct's Slimy Grass, The Betweenlands' Swamp Grass, or even Thaumcraft's Ambient Grass.
This isn't much of a problem with the standard version of the spell, but when you introduce the AoE Modifier, it becomes a problem.

**To Reproduce:**

1. Install Roots and deps.
2. Get a Staff with Growth Infusion and cast it on a modded Grass block.
3. Experience bug.

**Expected behavior:**

***

### Environment Versions

**Mystic Mods Versions**

- MysticalLib: 1.13.0
- Mystical World: 1.11.0
- Roots 3.1.6

**Other Versions:**
- Forge: 14.23.5.2860
- Minecraft: 1.12.2
- Modpack: discovered in MC Eternal, also occurred in a more minimal instance

Other mods in more minimal instance:
- Advanced Rocketry 1.7.0-232
- Ancient Spellcraft 1.5.5
- Armory Expansion 1.4.2
- B.A.S.E 3.14.0
- Baubles 1.5.2
- Construct's Armory 1.2.5.10
- ContentTweaker 4.10.0
- CraftTweaker2 4.1.20.673
- Electroblob's Wizardry 4.3.7
- JEI 4.16.1.302
- LibVulpes 0.4.2-75
- LLibrary 1.7.20
- Mantle 1.3.3.55
- Mekanism 9.8.3.390
- ModTweaker 4.0.18
- MTLib 3.0.6
- Mystical World 1.11.0
- The One Probe 1.4.28
- Patchouli 1.0-23.6
- PlusTiC 8.0.5
- Thaumcraft 6.1.BETA26
- Thaumic JEI 1.6.0-27
- Thaumisc 1.1
- Tinkers Alloying Addon 1.3.4
- Tinkers' Construct 2.13.0.183
- Tweakers Construct 1.6.1

***

### Additional Information

https://user-images.githubusercontent.com/63694982/211470944-a2792c92-24e2-44e4-b716-03891d833984.mp4

**Comment by ByThePowerOfScience** [comment]
These blocks need to be added to a blacklist in the config, I'd imagine. I don't see anything hardcoded that disallows even vanilla grass, so it's just a configuration option.

**Comment by anabsolutesloth** [comment]
It appears to be that the former two implement `IGrowable,` which is [checked for by the `canGrow()` function of the `Growth` class](https://github.com/MysticMods/Roots/blob/953495a56f2412f05bc57b047090ddea4e10f122/src/main/java/epicsquid/roots/mechanics/Growth.java#L85), which is [invoked by the spell](https://github.com/MysticMods/Roots/blob/953495a56f2412f05bc57b047090ddea4e10f122/src/main/java/epicsquid/roots/spell/SpellGrowthInfusion.java#L288)
I would argue that it would still be valuable to have such blocks from commonly used mods as a default part of the blacklist, seeing as some other mods' items have been added to the [default blacklist for the Ritual of the Spreading Forest](https://github.com/MysticMods/Roots/blob/953495a56f2412f05bc57b047090ddea4e10f122/src/main/java/epicsquid/roots/config/GeneralConfig.java#L94C1-L98C4).

**Comment by ByThePowerOfScience** [comment]
> I would argue that it would still be valuable to have such blocks from commonly used mods as a default part of the blacklist, seeing as some other mods' items have been added to the [default blacklist for the Ritual of the Spreading Forest](https://github.com/MysticMods/Roots/blob/953495a56f2412f05bc57b047090ddea4e10f122/src/main/java/epicsquid/roots/config/GeneralConfig.java#L94C1-L98C4).

Sadly, it's not realistic to do that for everything.  You should ask the modpack developer to add those blocks to the blacklist.
