### ISSUE TITLE
Minecraft fails to load, "Roots" mod identified, while using Insane Craft Modpack

### ISSUE THREAD

**Issue by Setnour6** [EpicSquid/Roots#798]
### General Information
Running on an MSI laptop with RTX (it's fresh too), windows 11, using minecraft 1.12.2.
**Describe the bug:**

The bug is shown to be a crash, regarding Minecraft failing to start. Roots was identified as a potential cause.
I can't click the green URL for some reason, and the "get link" button failed.

**To Reproduce:**

1. Install the InsaneCraft modpack from CurseForge
2. Click "play" on the modpack
3. Check java version type, see if it is forge with the modpack, and click "play"
4. If minecraft fails to load because of missing mod dependencies, install the missing mods from curseforge
5. minecraft still fails to load, and "roots" is identified as the cause of the problem

**Expected behavior:**

Minecraft would work normally and everything would load
***

### Environment Versions

1.12.2 with InsaneCraft modpack and forge launcher type
**Mystic Mods Versions**

_n/a_

**Other Versions:**
- Conflicting mod (if regarding mod integration): _n/a_
- Other mods you think could cause issues: I don't know, there are 200 mods installed.
- Forge: Latest (14.23.5.2860 I think, according to one of the craft logs)
- Minecraft: 1.12.2
- Modpack (if available): InsaneCraft for MC 1.12.2

***

### Logging Information
**Please Use [gist](https://gist.github.com), [paste.ee](https://paste.ee), [pastebin](https://pastebin.com) or some other log sharing service** (sorry, I had to post it here, it's much easier for me and pastebin needs to be publically accessible anyways)

**Crash Report (if available):**

[crash-2023-01-26_19.23.25-client.txt](https://github.com/MysticMods/Roots/files/10514577/crash-2023-01-26_19.23.25-client.txt)
[crash-2023-01-26_19.45.10-client.txt](https://github.com/MysticMods/Roots/files/10514578/crash-2023-01-26_19.45.10-client.txt)
**Latest Log (if necessary):**

[latest.log](https://github.com/MysticMods/Roots/files/10514579/latest.log)

***

### Additional Information
**Screenshots (if available):**

![image](https://user-images.githubusercontent.com/70764728/214981371-89d38265-507b-4678-913a-eb5f514a8a72.png)
I can't click the green URL for some reason, and the "get link" button failed.
**Additional context (optional):**

**Comment by Setnour6** [comment]
I get it, it's an error that belongs to Insane Craft, but they only speak on discord and I don't have or use discord, and I am NOT planning on using discord

**Comment by noobanidus** [comment]
You have too many mods with potion effects installed and have exceeded the number of potion effects possible, which is 256.

**Comment by Setnour6** [comment]
> You have too many mods with potion effects installed and have exceeded the number of potion effects possible, which is 256.

Oh. They should make it so the number of potion effects is more
