### ISSUE TITLE
[Roots 3] Mossy cobblestone/dungeons/structures/etc

### ISSUE THREAD

**Issue by duely** [EpicSquid/Roots#80]
You can gain access to an inordinate amount of terra moss early in the game if you end up finding a dungeon or a barrow (what are we doing about world gen?). 

Any other form of mossy cobblestone generation could potentially give access to an unfair quantity of terra moss

**Comment by EpicSquid** [comment]
Doesn't really bother me. I would consider it a reward for adventuring. Terra moss isn't a critical ingredient for a reason

**Comment by duely** [comment]
OK
