### ISSUE TITLE
Spell Library GUI doesn't show up on Servers

### ISSUE THREAD

**Issue by ImTryingMyBestFR** [EpicSquid/Roots#801]
### General Information

**Describe the bug:**
Spell Library GUI doesn't show up when pressing the keybind on servers although the server recognizes the key is being pressed

**To Reproduce:**

1. Log in to a roots (3.1.7) supporting server and press the spell library keybind while holding a staff
2. Nothing shows up

### Environment Versions
Encountered while running roots 3.1.7

**Mystic Mods Versions**
-MysticalWorld v1.11.0
- MysticalLib:1.13

**Other Versions:**
- Forge: 14.23.5.2860
- Minecraft: 1.12.2

### Additional Information
-Changing keybind doesn't fix the issue
-The issue isn't in the server recognizing the input as not holding the staff prompts a message stating "you need a wand to access the spell library"
-The issue isn't present when playing single player

Update: downgrading to previous version fixes this.

**Comment by MatiasGermain** [comment]
Same issue here while joining the host using the Essentials mod. The host is able to use the staff just fine, but those who join are unable to. 

Version:
-  Roots 3.1.7 
-  Forge 14.23.5.2860 
-  Minecraft 1.12.2 

Again it works in single-player. Should I attach the mod list?

**Comment by abilliontrillionstars** [comment]
having this issue as well, with the added benefit of freezing while trying to render the library gui. specifically, I was running a LAN world that I couldn't access the library on, so I became the host of that world (by copying the save over to my machine) after which I could open the GUI, only for it to crash trying to render it. logs say it throws an exception with other mods mentioned. 

Here's what I assume is the culprit: 
[22:41:20] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Pre@2f24923e:
java.util.ConcurrentModificationException: null
	at java.util.ArrayList.sort(Unknown Source) ~[?:1.8.0_202]
	at epicsquid.roots.world.data.SpellLibraryData.asList(SpellLibraryData.java:146) ~[SpellLibraryData.class:?]
	at epicsquid.roots.world.data.SpellLibraryData.get(SpellLibraryData.java:157) ~[SpellLibraryData.class:?]

full log here:
[latest.log](https://github.com/MysticMods/Roots/files/12256611/latest.log)

**Comment by Castanea43** [comment]
Hi, same problem here when i used some part of the Roots book, on server
log here : https://mclo.gs/aV8XppZ

Roots 1.12.2-3.1.7
MC : 1.12.2
Forge 14.23.5.2860

MysticalLib : 1.13.0
Mystical World : 1.11.0

**Comment by noobanidus** [comment]
> Hi, same problem here when i used some part of the Roots book, on server log here : https://mclo.gs/aV8XppZ
> 
> Roots 1.12.2-3.1.7 MC : 1.12.2 Forge 14.23.5.2860
> 
> MysticalLib : 1.13.0 Mystical World : 1.11.0

This relates to Patchouli interacting with `git.jbredwards.fluidlogged_api.mod.asm.plugins.forge`, whichever library that is associated with, I presume, which provides the back-port of fluid logging in 1.12.

I can't see any way to resolve it easily.

**Comment by ByThePowerOfScience** [comment]
> Here's what I assume is the culprit: [22:41:20] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.client.event.GuiScreenEvent$DrawScreenEvent$Pre@2f24923e: java.util.ConcurrentModificationException: null at java.util.ArrayList.sort(Unknown Source) ~[?:1.8.0_202] at epicsquid.roots.world.data.SpellLibraryData.asList(SpellLibraryData.java:146) ~[SpellLibraryData.class:?] at epicsquid.roots.world.data.SpellLibraryData.get(SpellLibraryData.java:157) ~[SpellLibraryData.class:?]
> 
> full log here: [latest.log](https://github.com/MysticMods/Roots/files/12256611/latest.log)

That means that it's caused by the same issue as #800, which means the fix for that will fix this one too.

**Comment by SeriousCreeper** [comment]
Very similar issue here with 3.1.7, just gonna add my logs to this. 

https://pastebin.com/5Wr70sGh
