### ISSUE TITLE
Game crashes when using augment light soarer on DIvine Journey 2

### ISSUE THREAD

**Issue by Shatterdest** [EpicSquid/Roots#807]
### General Information

**Describe the bug:**
Using the augment spell with light soarer crashes the game. This happens either when the player first enters spectator mode or first leaves spectator mode. 

**To Reproduce:**
1. Use augment spell

**Expected behavior:**
Player enters spectator mode temporarily. 

***

### Environment Versions
Roots 1.12.2 3.1.8

**Mystic Mods Versions**
- MysticalLib: 1.12.2-1.13.0

**Other Versions:**
- Forge: 14.23.5.2860
- Minecraft: 1.12.2
- Modpack (if available): Divine Journey 2 2.20.1

***

### Logging Information

**Crash Report (if available):**
https://pastebin.com/eqdk5hne

***

### Additional Information
https://youtu.be/wzbMl4yC50Y

**Comment by ByThePowerOfScience** [comment]
Fixed in 3.1.9.1.
