### ISSUE TITLE
Server crash from Animal Harvest Ritual after updating Roots in Divine Journey 2 

### ISSUE THREAD

**Issue by Inferius77** [EpicSquid/Roots#811]
To resolve issue #805  I updated Roots to 3.1.9 on my Divine Journey 2 server and guided my players to update their clients as well.

**Describe the bug:**
When the Animal Harvest Ritual is started, the server crashes. It does not happen in single player.

**To Reproduce:**
A quote from one of my players:
> "You put a set of 5 or 6 items onto it by right clicking, 
> then it starts burning and a timer starts in the like, indicator thing for items, 
> but instead of doing that. as soon as it starts the ritual, half a second or two after. it crashes.
> 
> almost as if its having an issue when it selects an entity to do the effect to"

### Environment Versions
forge: 14.23.5.2860
Java Version: 1.8.0_371
Divine Journey 2 pack version: 2.20.1
Minecraft version: 1.12.2

**Mystic Mods Versions**
- MysticalLib: 1.12.12 - 1.13.0
- Roots version: 3.1.9

***

### Logging Information
**Crash Report (if available):**
https://gist.github.com/Inferius77/86d0f1f6174b3e2476b3058434eb276f

***

**Comment by noobanidus** [comment]
@ByThePowerOfScience Looks like another instance of access transformers not applying properly. :/

**Comment by ByThePowerOfScience** [comment]
Oh for the love of-
I'll take a look.

**Comment by ByThePowerOfScience** [comment]
Fixed in 3.1.9.1.
