### ISSUE TITLE
[Roots 3] progression is stalled without the book

### ISSUE THREAD

**Issue by onewithtehforce** [EpicSquid/Roots#82]
There is nothing in game (with just roots 3 and dependencies) that informs the player how to make the book.
A mod pack might give the book to the player and JEI/etc. can be used to show the book recipe and perhaps a wiki has the recipe but if playing without these scenarios and without having played with the mod before how should a player new to the mod find out how to make the book?

An advancement linked with obtaining a sapling or something similar might be useful to show the recipe.

**Comment by duely** [comment]
An advancement linked to wildroot could be good, reducing the recipe to paper + wildroot (instead of sticks) would allow something along the lines of an achievement "Combine wildroot and paper to obtain the Druidic Arts"?
