### ISSUE TITLE
[Roots 3] living knife?

### ISSUE THREAD

**Issue by onewithtehforce** [EpicSquid/Roots#83]
based on the lore in the book for the living tools it would fit to make a living knife with the same pyre recipe and a wooden knife, given the druid has learned to reinforce and extend wooden tools.
this might make the other knife recipes redundant though

**Comment by duely** [comment]
As it feels as though knives are intended to be a consumable item and have tiers, and while the limitations of "iron-pick only mining" etc (i.e., you can't use a living pick for obsidian-level stuff) work well for mining tools/vanilla tools, they don't really have any relevance to the knives.

Thus, it would definitely feel as though they would become redundant... Perhaps it could be "living" in the sense that it has greater durability, but it will not infinitely repair itself.

**Comment by Martacus** [comment]
Living knife is not something we will add to the mod noh

**Comment by Martacus** [comment]
When the knife becomes a more important item in druidry we might revalue the need to make a living tool for it.
