### ISSUE TITLE
[Roots 3] plants which need runic soil can plant upper already planted

### ISSUE THREAD

**Issue by Mefather** [EpicSquid/Roots#86]
other plants fine, but them.

**Comment by duely** [comment]
Can you clarify which build of Roots 3 you're using? Thanks!

**Comment by Mefather** [comment]
ver 3.0.0-4

**Comment by duely** [comment]
I noticed this behaviour in a previous version but I was led to believe by @EpicSquid that it had been fixed.

I presume by upper that you mean you can plant infernal blooms on top of other infernal blooms, in "mid-air" as it were?

**Comment by Mefather** [comment]
yup

**Comment by EpicSquid** [comment]
I can't replicate this in dev. When I put out the next build can you test it?

**Comment by Mefather** [comment]
As my pleasure.

**Comment by duely** [comment]
This appears to have been resolved at some point.
