### ISSUE TITLE
[Roots 3] crasher attempting to do animal harvest ritual

### ISSUE THREAD

**Issue by gchpaco** [EpicSquid/Roots#90]
I found the following crash bug while attempting to start the animal harvest ritual.  Nearby animals were chickens, horses, pigs, and probably a couple sheep on the periphery.

Version is custom built from 1478d92 of roots 3 and
https://github.com/EpicSquid/MysticalLib/commit/5f889f1b9552e5c3e16564a9e3f4762756c62961 of MysticalLib.

[crash-2019-03-20_23.19.30-client.txt](https://github.com/EpicSquid/Roots/files/2990819/crash-2019-03-20_23.19.30-client.txt)

**Comment by EpicSquid** [comment]
Feels bad, this is still broken. Lemme make sure I fix it for real this time

**Comment by gchpaco** [comment]
Vazkii has had this problem approximately 6,280 billion times and had some gradle magic that would fail the build if it found it.  I don't know if it is still updated or relevant, but it might be helpful.

**Comment by EpicSquid** [comment]
Fixed! yay
