### ISSUE TITLE
[Roots 3] crasher on attempting to use pestle on mortar containing only wheat

### ISSUE THREAD

**Issue by gchpaco** [EpicSquid/Roots#92]
This happened to me with 4b502785c9a48afe67d741031975bffe618bdb00 just now.

[crash-2019-03-22_10.25.53-client.txt](https://github.com/EpicSquid/Roots/files/2997170/crash-2019-03-22_10.25.53-client.txt)

**Comment by duely** [comment]
Make sure you've also build and updated Mystical Lib. I forgot to push my changes to it, oops!

**Comment by gchpaco** [comment]
Confirmed that a more up to date MysticalLib fixes the issue, thanks!

**Comment by duely** [comment]
My fault, it wasn't until super-late last night that I realised that code was a) part of Mystical Lib, and that b) I hadn't even committed let alone pushed it.
