### ISSUE TITLE
[Roots 3] Unending bowl interaction with Petal Apothecary

### ISSUE THREAD

**Issue by duely** [EpicSquid/Roots#93]
It would be a nice cross-over were a nearby unending bowl be able to automatically fill the petal apothecary.

**Comment by Birgliss** [comment]
seconding this, perhaps also being able to right-click the apothecary with the unending bowl to fill it?
and at that, maybe we wanna consider if the unending bowl should be a "static" fluid container?

**Comment by duely** [comment]
Honestly, I'd rather just steal the code from the EvilCraft eternal water block because it's A+.
