### ISSUE TITLE
server crashed

### ISSUE THREAD

**Issue by Mefather** [EpicSquid/Roots#94]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.5-1.12.2-anarchy.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b148.jar)
  LoadingPlugin (TickDynamic-1.12.2-1.0.1.jar)
  AstralCore (astralsorcery-1.12.2-1.10.1.jar)
  EECore (ExpandedEquivalence-1.12.2-11b.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  HCASM (HammerCore-1.12.2-2.0.4.1.jar)
Contact their authors BEFORE contacting forge

// You're mean.

Time: 3/25/19 7:59 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mystical Lib (mysticallib)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/model/ModelBiped
	at epicsquid.roots.init.ModItems.registerItems(ModItems.java:88)
	at epicsquid.roots.RegistryManager.init(RegistryManager.java:36)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_762_RegistryManager_init_RegisterContentEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at epicsquid.mysticallib.LibRegistry.initAll(LibRegistry.java:79)
	at epicsquid.mysticallib.proxy.CommonProxy.preInit(CommonProxy.java:17)
	at epicsquid.mysticallib.MysticalLib.preInit(MysticalLib.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.minecraft.client.model.ModelBiped
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 43 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer vazkii.quark.base.asm.ClassTransformer@97960b from coremod LoadingPlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:260)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 45 more
Caused by: java.lang.NullPointerException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at vazkii.quark.base.asm.ClassTransformer.transform(ClassTransformer.java:455)
	at vazkii.quark.base.asm.ClassTransformer.transformModelBiped(ClassTransformer.java:113)
	at vazkii.quark.base.asm.ClassTransformer.transform(ClassTransformer.java:104)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:256)
	... 47 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (x86) version 6.1
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 229243936 bytes (218 MB) / 689262592 bytes (657 MB) up to 1037959168 bytes (989 MB)
	JVM Flags: 2 total; -Xmx512m -Xmx1024m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2808 101 mods loaded, 101 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version                  | Source                                             | Signature                                |
	|:----- |:-------------------- |:------------------------ |:-------------------------------------------------- |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2                   | minecraft.jar                                      | None                                     |
	| LCH   | mcp                  | 9.42                     | minecraft.jar                                      | None                                     |
	| LCH   | FML                  | 8.0.99.99                | forge-1.12.2-14.23.5.2808.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2808             | forge-1.12.2-14.23.5.2808.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | foamfixcore          | 7.7.4                    | minecraft.jar                                      | None                                     |
	| LCH   | actuallyadditions    | 1.12.2-r133              | ActuallyAdditions-1.12.2-r133.jar                  | None                                     |
	| LCH   | baubles              | 1.5.2                    | Baubles-1.12-1.5.2.jar                             | None                                     |
	| LCH   | actuallybaubles      | 1.1                      | ActuallyBaubles-1.12-1.1.jar                       | None                                     |
	| LCH   | appliedenergistics2  | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCH   | bdlib                | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                       | None                                     |
	| LCH   | ae2stuff             | 0.7.0.4                  | ae2stuff-0.7.0.4-mc1.12.2.jar                      | None                                     |
	| LCH   | mantle               | 1.12-1.3.3.39            | Mantle-1.12-1.3.3.39.jar                           | None                                     |
	| LCH   | jei                  | 4.13.1.225               | jei_1.12.2-4.13.1.225.jar                          | None                                     |
	| LCH   | projecte             | 1.12-PE1.3.2h            | ProjectE-1.12-PE1.3.2h.jar                         | None                                     |
	| LCH   | redstoneflux         | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar            | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | chisel               | MC1.12.2-0.2.1.35        | Chisel-MC1.12.2-0.2.1.35.jar                       | None                                     |
	| LCH   | tweakersconstruct    | 1.12.2-1.2.0             | tweakersconstruct-1.12.2-1.2.0.jar                 | None                                     |
	| LCH   | tconstruct           | 1.12.2-2.12.0.115        | TConstruct-1.12.2-2.12.0.115.jar                   | None                                     |
	| LCH   | p455w0rdslib         | 2.0.36                   | p455w0rdslib-1.12.2-2.0.36.jar                     | None                                     |
	| LCH   | ae2wtlib             | 1.0.6                    | AE2WTLib-1.12.2-1.0.6.jar                          | None                                     |
	| LCH   | embers               | 1.12                     | EmbersRekindled-1.12.jar                           | None                                     |
	| LCH   | aetherworks          | 1.12.2-1.0.0.3           | AetherWorks-1.12.2-1.0.0.3.jar                     | None                                     |
	| LCH   | alcatrazcore         | 1.0.3                    | alcatrazcore-1.0.3.jar                             | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCH   | applecore            | 3.1.0                    | AppleCore-mc1.12.2-3.1.0.jar                       | None                                     |
	| LCH   | appleskin            | 1.0.9                    | AppleSkin-mc1.12-1.0.9.jar                         | None                                     |
	| LCH   | aroma1997core        | 2.0.0.0.b148             | Aroma1997Core-1.12.2-2.0.0.0.b148.jar              | dfbfe4c473253d8c5652417689848f650b2cbe32 |
	| LCH   | aroma1997sdimension  | 1.3.0.0.b37              | Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar  | None                                     |
	| LCH   | astralsorcery        | 1.10.1                   | astralsorcery-1.12.2-1.10.1.jar                    | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCH   | quark                | r1.4-123                 | Quark-r1.4-123.jar                                 | None                                     |
	| LCH   | autoreglib           | 1.3-16                   | AutoRegLib-1.3-16.jar                              | None                                     |
	| LCH   | betterbuilderswands  | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar    | None                                     |
	| LCH   | bibliocraft          | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar                  | None                                     |
	| LCH   | biomesoplenty        | 7.0.1.2417               | BiomesOPlenty-1.12.2-7.0.1.2417-universal.jar      | None                                     |
	| LCH   | guideapi             | 1.12-2.1.5-60            | Guide-API-1.12-2.1.5-60.jar                        | None                                     |
	| LCH   | bloodmagic           | 1.12.2-2.3.3-101         | BloodMagic-1.12.2-2.3.3-101.jar                    | None                                     |
	| LCH   | conarm               | 1.2.3                    | conarm-1.12.2-1.2.3.jar                            | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LCH   | bloodtinker          | 1.0.5                    | bloodtinker-1.0.5.jar                              | None                                     |
	| LCH   | bookshelf            | 2.3.577                  | Bookshelf-1.12.2-2.3.577.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | botania              | r1.10-358                | Botania+r1.10-358.jar                              | None                                     |
	| LCH   | hammercore           | 2.0.4.1                  | HammerCore-1.12.2-2.0.4.1.jar                      | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCH   | botanicadds          | 1r                       | BotanicAdditions-1.12.2-1r.jar                     | None                                     |
	| LCH   | codechickenlib       | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | brandonscore         | 2.4.9                    | BrandonsCore-1.12.2-2.4.9.195-universal.jar        | None                                     |
	| LCH   | chameleon            | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                           | None                                     |
	| LCH   | chickenchunks        | 2.4.1.71                 | ChickenChunks-1.12.2-2.4.1.71-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | cofhcore             | 4.6.1                    | CoFHCore-1.12.2-4.6.1.22-universal.jar             | None                                     |
	| LCH   | cofhworld            | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | cookingforblockheads | 6.4.69                   | CookingForBlockheads_1.12.2-6.4.69.jar             | None                                     |
	| LCH   | cyclopscore          | 1.0.2                    | CyclopsCore-1.12.2-1.0.2.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | waila                | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                        | None                                     |
	| LCH   | darkutils            | 1.8.223                  | DarkUtils-1.12.2-1.8.223.jar                       | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | thermalfoundation    | 2.6.1                    | ThermalFoundation-1.12.2-2.6.1.22-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | draconicevolution    | 2.3.18                   | Draconic-Evolution-1.12.2-2.3.18.329-universal.jar | None                                     |
	| LCH   | eleccore             | 1.8.434                  | ElecCore-1.12.2-1.8.434.jar                        | None                                     |
	| LCH   | ebwizardry           | 4.1.4                    | Electroblob's+Wizardry+-+4.1.4+-+MC+1.12.2.jar     | None                                     |
	| LCH   | elevatorid           | 1.3.6                    | ElevatorMod-1.12.2-1.3.6.jar                       | None                                     |
	| LCH   | enderstorage         | 2.4.2.126                | EnderStorage-1.12.2-2.4.2.126-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | evilcraft            | 0.10.66                  | EvilCraft-1.12.2-0.10.66.jar                       | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| LCH   | evilcraftcompat      | 1.0.0                    | EvilCraft-1.12.2-0.10.66.jar                       | None                                     |
	| LCH   | expequiv             | 11b                      | ExpandedEquivalence-1.12.2-11b.jar                 | 4d7b29cd19124e986da685107d16ce4b49bc0a97 |
	| LCH   | extracells           | 2.6.2                    | ExtraCells-1.12.2-2.6.2a.jar                       | None                                     |
	| LCH   | fastleafdecay        | v14                      | FastLeafDecay-v14.jar                              | None                                     |
	| LCH   | foamfix              | 0.9.5-1.12.2             | foamfix-0.9.5-1.12.2-anarchy.jar                   | None                                     |
	| LCH   | gravestone           | 1.10.1                   | gravestone-1.10.1.jar                              | None                                     |
	| LCH   | journeymap           | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                        | None                                     |
	| LCH   | malisiscore          | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                       | None                                     |
	| LCH   | malisisdoors         | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
	| LCH   | mcjtylib_ng          | 2.6.7                    | mcjtylib-1.12-2.6.7.jar                            | None                                     |
	| LCH   | roots                | 1.12.2-3.0.0-5           | Roots-1.12.2-3.0.0-5.jar                           | None                                     |
	| LCH   | mysticalworld        | 1.12.2-1.2.0             | MysticWorld-1.12.2-1.2.0.jar                       | None                                     |
	| LCH   | nei                  | 2.4.2                    | NotEnoughItems-1.12.2-2.4.2.240-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCH   | harvestcraft         | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zb.jar                    | None                                     |
	| LCH   | patchouli            | 1.0-17                   | Patchouli-1.0-17.jar                               | None                                     |
	| LCH   | plustic              | 6.5.4.2                  | plustic-6.5.4.2.jar                                | None                                     |
	| LCH   | reborncore           | 3.7.2.245                | RebornCore-1.12.2-3.7.2.245-universal.jar          | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCH   | rootsclassic         | 1.12.2-1.1.4             | RootsClassic-1.12.2-1.1.4.jar                      | 1bc8f8dbe770187a854cef35dad0ff40ba441bbe |
	| LCH   | rustic               | 1.0.15                   | rustic-1.0.15.jar                                  | None                                     |
	| LCH   | rusticbopwoods       | 1.0                      | rusticbopwoods-1.0.jar                             | None                                     |
	| LCH   | t3s4ebw              | 1.0                      | SeedsForWizardry+1.0+For+MC+Forge+1.12.2.jar       | None                                     |
	| LCH   | solar                | 1.0.3                    | Solar-1.0.3.jar                                    | None                                     |
	| LCH   | soot                 | 1.5                      | Soot-1.5.jar                                       | None                                     |
	| LCH   | storagedrawers       | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.6.jar                    | None                                     |
	| LCH   | storagedrawersextra  | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar                | None                                     |
	| LCH   | techreborn           | 2.13.2.561               | TechReborn-1.12.2-2.13.2.561-universal.jar         | 8727a3141c8ec7f173b87aa78b9b9807867c4e6b |
	| LCH   | thermalexpansion     | 5.5.2                    | ThermalExpansion-1.12.2-5.5.2.39-universal.jar     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | thermalcultivation   | 0.3.1                    | ThermalCultivation-1.12.2-0.3.1.8-universal.jar    | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | thermaldynamics      | 2.5.3                    | ThermalDynamics-1.12.2-2.5.3.16-universal.jar      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LCH   | tickdynamic          | 1.0.1                    | TickDynamic-1.12.2-1.0.1.jar                       | fc6c96880539df54ba847abda8844dabfcef307e |
	| LCH   | tinker_io            | release 2.6.1            | tinker_io-1.12.2-release 2.6.1.jar                 | None                                     |
	| LCH   | tinkersaddons        | 1.0.7                    | Tinkers'+Addons-1.12.1-1.0.7.jar                   | None                                     |
	| LCH   | tcomplement          | ${version}               | TinkersComplement-1.12.2-0.2.3b.jar                | None                                     |
	| LCH   | tinkersforging       | 1.0.7                    | tinkersforging-1.0.7.jar                           | 3c2d6be715971d1ed58a028cdb3fae72987fc934 |
	| LCH   | tinkersjei           | 1.0                      | tinkersjei-1.0.jar                                 | None                                     |
	| LCH   | tinkertoolleveling   | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                | None                                     |
	| LCH   | treechopper          | 1.2.4                    | TreeChopper-1.12.2-1.2.4.jar                       | None                                     |
	| LCH   | wawla                | 2.5.265                  | Wawla-1.12.2-2.5.265.jar                           | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCH   | wct                  | 3.11.88                  | WirelessCraftingTerminal-1.12.2-3.11.88.jar        | None                                     |
	| LCH   | woot                 | 1.12.2-1.0.1             | woot-1.12.2-1.0.1.jar                              | None                                     |
	| LCH   | zerocore             | 1.12-0.1.2.1             | zerocore-1.12-0.1.2.1.jar                          | None                                     |
	| LCH   | llibrary             | 1.7.17                   | llibrary-1.7.17-1.12.2.jar                         | b9f30a813bee3b9dd5652c460310cfcd54f6b7ec |
	| LCE   | mysticallib          | 1.12.2-1.1.2             | mysticallib-1.12.2-1.1.2.jar                       | None                                     |

	Loaded coremods (and transformers): 
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
AppleCore (AppleCore-mc1.12.2-3.1.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
llibrary (llibrary-core-1.0.10-1.12.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.5-1.12.2-anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
LoadingPlugin (Quark-r1.4-123.jar)
  vazkii.quark.base.asm.ClassTransformer
CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b148.jar)
  
LoadingPlugin (TickDynamic-1.12.2-1.0.1.jar)
  com.wildex999.patcher.TransformerPatcher
  com.wildex999.patcher.EntityInjector
AstralCore (astralsorcery-1.12.2-1.10.1.jar)
  
EECore (ExpandedEquivalence-1.12.2-11b.jar)
  com.zeitheron.expequiv.core.EETransformer
CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  team.chisel.ctm.client.asm.CTMTransformer
HCASM (HammerCore-1.12.2-2.0.4.1.jar)
  com.zeitheron.hammercore.asm.HammerCoreTransformer
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Hammer Core Information: FluidDictionary Info: Registered 2 fluids.
OreDictionary Info: Registered 737 names; 1081 stacks.
Configuration Info: IyBDb25maWd1cmF0aW9uIGZpbGUNCg0KY2xpZW50IHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSByZXBsYWNlIGVuY2hhbnRtZW50IGdsaW50IGNvbG9yIHdpdGggbW9yZSBtYXRjaGluZyBjb2xvcnMgZm9yIHNvbWUgdmFuaWxsYSBpdGVtcz8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQ3VzdG9tIEVuY2hhbnRtZW50IENvbG9ycyBmb3IgVmFuaWxsYSBJdGVtcyI9dHJ1ZQ0KICAgIEI6IkltcHJvdmVkIExBTiI9dHJ1ZQ0KDQogICAgIyBTaG91bGQgSGFtbWVyIENvcmUgcG9ydGZvcndhcmQgeW91ciBsb2NhbCB3b3JsZCB3aGVuIHlvdSBzaGFyZSB3aXRoIGl0IHRvIExBTj8NCiAgICAjIFRoaXMgZmVhdHVyZSBkb2Vzbid0IHdvcmsgb24gYWxsIGNsaWVudHMsIHlvdSBhcmUgZ29pbmcgdG8gZ2V0IGEgbWVzc2FnZSBpbiBjaGF0IGlmIGl0IHdhcyBzdWNjZXNzZnVsL3Vuc3VjY2Vzc2Z1bCBbZGVmYXVsdDogdHJ1ZV0NCiAgICBCOiJMQU4gVVBuUCI9dHJ1ZQ0KICAgIEI6Ik1vZCBCcm93c2VyIj10cnVlDQoNCiAgICAjIFJlcGxhY2UgdmFuaWxsYSBmdXJuYWNlIGFuZCBicmV3aW5nIHN0YW5kIHByb2dyZXNzIGJhcnMgdG8gdXNlIHNtb290aCByZW5kZXJpbmc/IFtkZWZhdWx0OiB0cnVlXQ0KICAgIEI6IlNtb290aCBWYW5pbGxhIEd1aXMiPXRydWUNCn0NCg0KDQpkZWJ1ZyB7DQogICAgQjpSYXl0cmFjZXI9ZmFsc2UNCiAgICBCOlphcHBlcj1mYWxzZQ0KfQ0KDQoNCml3cmVuY2ggew0KICAgICMgV2hhdCBpcyB0aGUgY29sb3Igd2hlbiB0aGUgaG92ZXJlZCBibG9jayBpcyB3cmVuY2hhYmxlPyAoY29sb3IgZW5jb2RlZCBpbiBoZXggZm9ybSBzdWNoIGFzIFJSR0dCQikNCiAgICBTOkdyZWVuPTIyRkYyMg0KDQogICAgIyBXaGF0IGlzIHRoZSBjb2xvciB3aGVuIHRoZSBob3ZlcmVkIGJsb2NrIGlzIE5PVCB3cmVuY2hhYmxlPyAoY29sb3IgZW5jb2RlZCBpbiBoZXggZm9ybSBzdWNoIGFzIFJSR0dCQikNCiAgICBTOlJlZD1GRjIyMjINCn0NCg0KDQoidmFuaWxsYSBpbXByb3ZlbWVudHMiIHsNCiAgICAjIFNob3VsZCBIYW1tZXIgQ29yZSBmb3JjZS1zcGF3biBFbmRlciBEcmFnb24gRWdnIG9uIEVuZGVyIERyYWdvbiBkZWF0aD8gW2RlZmF1bHQ6IHRydWVdDQogICAgQjoiQWx3YXlzIFNwYXduIERyYWdvbiBFZ2ciPXRydWUNCn0NCg0KDQo=
Pastebin Connection: Okay.
Dependent Mods:
    -Botanic Additions (botanicadds) @1r
    -Expanded Equivalence (expequiv) @11b

	Pulsar/tcomplement loaded Pulses: 
		- ModuleCommons (Enabled/Forced)
		- ModuleFeature (Enabled/Not Forced)
		- ChiselPlugin (Enabled/Not Forced)

	List of loaded APIs: 
		* actuallyadditionsapi (33) from ActuallyAdditions-1.12.2-r133.jar
		* ae2wtlib|api (1.1) from AE2WTLib-1.12.2-1.0.6.jar
		* AppleCoreAPI (3.1.0) from AppleCore-mc1.12.2-3.1.0.jar
		* appliedenergistics2|API (rv6) from appliedenergistics2-rv6-stable-6.jar
		* Baubles|API (1.4.0.2) from AE2WTLib-1.12.2-1.0.6.jar
		* BetterWithModsAPI (Beta 0.6) from Quark-r1.4-123.jar
		* bloodmagic-api (2.0.0) from BloodMagic-1.12.2-2.3.3-101.jar
		* BotaniaAPI (92) from Botania+r1.10-358.jar
		* Chisel-API (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* ChiselAPI|Carving (0.0.1) from Chisel-MC1.12.2-0.2.1.35.jar
		* cofhapi (2.5.0) from CoFHCore-1.12.2-4.6.1.22-universal.jar
		* ctm-api (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-events (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-models (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-textures (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* ctm-api-utils (0.1.0) from CTM-MC1.12.2-0.3.3.22.jar
		* DraconicEvolution|API (1.3) from Draconic-Evolution-1.12.2-2.3.18.329-universal.jar
		* ElecCoreAPI (1.0) from ElecCore-1.12.2-1.8.434.jar
		* ElecCore|Abilities (#API_VER#) from ElecCore-1.12.2-1.8.434.jar
		* EmbersAPI (0.1) from EmbersRekindled-1.12.jar
		* Guide-API|API (2.0.0) from Guide-API-1.12-2.1.5-60.jar
		* jeresources|API (0.8.6.28) from JustEnoughResources-1.12.2-0.8.6.28.jar
		* journeymap|client-api (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-display (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-event (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-model (1.4) from journeymap-1.12.2-5.5.2.jar
		* journeymap|client-api-util (1.4) from journeymap-1.12.2-5.5.2.jar
		* JustEnoughItemsAPI (4.13.0) from jei_1.12.2-4.13.1.225.jar
		* PatchouliAPI (6) from Patchouli-1.0-17.jar
		* projecteapi (1.12.2-1.1.0) from ProjectE-1.12-PE1.3.2h.jar
		* ProjectEAPI (1.9.4-1.0.0) from p455w0rdslib-1.12.2-2.0.36.jar
		* QuarkAPI (2) from Quark-r1.4-123.jar
		* reborncoreAPI (3.7.2.245) from RebornCore-1.12.2-3.7.2.245-universal.jar
		* reborncoreAPI|Power (3.7.2.245) from RebornCore-1.12.2-3.7.2.245-universal.jar
		* reborncoreAPI|Recipe (3.7.2.245) from RebornCore-1.12.2-3.7.2.245-universal.jar
		* reborncoreAPI|Tile (3.7.2.245) from RebornCore-1.12.2-3.7.2.245-universal.jar
		* redstonefluxapi (2.1.0) from RedstoneFlux-1.12-2.1.0.6-universal.jar
		* StorageDrawersAPI (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|event (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|registry (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|render (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|storage (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* StorageDrawersAPI|storage-attribute (2.1.0) from StorageDrawers-1.12.2-5.3.6.jar
		* techrebornAPI (2.13.2.561) from TechReborn-1.12.2-2.13.2.561-universal.jar
		* WailaAPI (1.3) from Hwyla-1.8.26-B41_1.12.2.jar
		* wct|api (1.1) from WirelessCraftingTerminal-1.12.2-3.11.88.jar
		* zerocore|API|multiblock (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar
		* zerocore|API|multiblock|rectangular (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar
		* zerocore|API|multiblock|tier (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar
		* zerocore|API|multiblock|validation (1.10.2-0.0.2) from zerocore-1.12-0.1.2.1.jar
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 3.7.2.245
		Runtime Debofucsation 1
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Davoleo** [comment]
I can't reproduce this :P 
I get a completely different crash that concerns patchouli

feel free to look into this one @duely

**Comment by duely** [comment]
I believe this was fixed.
