### ISSUE TITLE
Mod config

### ISSUE THREAD

**Issue by Davoleo** [EpicSquid/Roots#98]
Reason: It would be nice to have some way to change the values of spells, ritual, or other features in the mod configs

We could do it:
- Using the new @Config annotation system (It's so much simpler than the other one), or 
- Using the traditional system (allows more customized GUIs), or
- We could avoid doing it  ( ¯\_(ツ)_/¯ )

**Comment by EpicSquid** [comment]
We really do need to do it lol, we should use the config annotation system.

**Comment by Davoleo** [comment]
Do you prefer configs to be divided in different cfg files, or different categories in the same cfg file?
